Fix the readline 6.0 issue pointed out at http://bugs.python.org/issue5833.  We apply http://bugs.python.org/file14599/python-2.6-readline.patch.  See trac 6990.

diff --git a/build/pkgs/python/spkg-install b/build/pkgs/python/spkg-install
--- a/build/pkgs/python/spkg-install
+++ b/build/pkgs/python/spkg-install
@@ -43,6 +43,14 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+# Readline patch: http://bugs.python.org/file14599/python-2.6-readline.patch
+cp patches/readline.c-spacebug src/Modules/readline.c
+if [ $? -ne 0 ]; then
+    echo "Error copying patched readline.c"
+    exit 1
+fi
+
+
 # We are setting LDFLAGS and CPPFLAGS so that we pick up Sage's readline
 LDFLAGS="-L$SAGE_LOCAL/lib $LDFLAGS"
 export LDFLAGS
