Apply python patch http://bugs.python.org/issue1608818 fixing an incorrectly detected out of memory issue (#5278)

diff --git a/build/pkgs/python/spkg-install b/build/pkgs/python/spkg-install
--- a/build/pkgs/python/spkg-install
+++ b/build/pkgs/python/spkg-install
@@ -37,6 +37,12 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+cp patches/posixmodule.c src/Modules/posixmodule.c
+if [ $? -ne 0 ]; then
+    echo "Error copying patched posixmodule.c"
+    exit 1
+fi
+
 # We are setting LDFLAGS and CPPFLAGS so that we pick up Sage's readline
 LDFLAGS="-L$SAGE_LOCAL/lib $LDFLAGS"
 export LDFLAGS
