Fix another dumb buglet: copy modified header *before* exiting spkg-install

diff --git a/build/pkgs/python/spkg-install b/build/pkgs/python/spkg-install
--- a/build/pkgs/python/spkg-install
+++ b/build/pkgs/python/spkg-install
@@ -102,6 +102,16 @@ cd $SAGE_LOCAL/lib
 rm -rf python/python2.5 python/python python python2.4
 ln -s python2.5 python
 
+if [ `uname` = "Darwin" -a "$SAGE64" = "yes" ]; then
+    echo "Copying 64 bit OSX specific pymactoolbox.h"
+    cd $CUR
+    cp patches/pymactoolbox.h $SAGE_LOCAL/include/python2.5/
+    if [ $? -ne 0 ]; then
+        echo "Error copying patched pymactoolbox.h"
+        exit 1
+    fi
+fi
+
 # Make sure sufficient crypto support is available in the built python.  This is critical.
 python -c "import md5"
 
@@ -111,16 +121,5 @@ if [ $? -eq 0 -a -f "$SAGE_LOCAL/bin/python" ]; then
 else
     echo "md5 module failed to import"
     exit 1
-fi
-
-
-if [ `uname` = "Darwin" -a "$SAGE64" = "yes" ]; then
-    echo "Copying 64 bit OSX specific pymactoolbox.h"
-    cd $CUR
-    cp patches/pymactoolbox.h $SAGE_LOCAL/include/python2.5/
-    if [ $? -ne 0 ]; then
-        echo "Error copying patched pymactoolbox.h"
-        exit 1
-    fi
 fi
 
