Trac #14265: Compile with -D__C99FEATURES__ on Solaris.  * Remove workaround for http://bugs.python.org/issue6954    (which is fixed upstream).  * Rename environment variable EXTRAFLAGS to PYTHON_CONFIGURE for    consistency with other packages and allow it to be set by the user.  * Add check that the ctypes and readline modules can be imported.  * Don't add the -fwrapv flag (no longer needed since Python-2.7.3 adds    this flag for Clang).

diff --git a/build/pkgs/python/spkg-install b/build/pkgs/python/spkg-install
--- a/build/pkgs/python/spkg-install
+++ b/build/pkgs/python/spkg-install
@@ -32,22 +32,19 @@ done
 LDFLAGS="-L$SAGE_LOCAL/lib $LDFLAGS"
 export LDFLAGS
 
-# Extra flags for ./configure
-EXTRAFLAGS=
-
 if [ "$SAGE_DEBUG" = "yes" ]; then
     echo "Building Python with pydebug"
-    EXTRAFLAGS="$EXTRAFLAGS --with-pydebug"
+    PYTHON_CONFIGURE="$PYTHON_CONFIGURE --with-pydebug"
 fi
 
 # pymalloc screws with valgrind, so let's disable it
 if [ "$SAGE_VALGRIND" = "yes" ]; then
     echo "Building Python without pymalloc"
-    EXTRAFLAGS="$EXTRAFLAGS --without-pymalloc"
+    PYTHON_CONFIGURE="$PYTHON_CONFIGURE --without-pymalloc"
 fi
 
 if [ `uname` = "Darwin" ]; then
-    EXTRAFLAGS="$EXTRAFLAGS --disable-toolbox-glue"
+    PYTHON_CONFIGURE="--disable-toolbox-glue $PYTHON_CONFIGURE"
 fi
 
 if [ "$SAGE64" = yes ]; then
@@ -55,33 +52,19 @@ if [ "$SAGE64" = yes ]; then
     export CC="$CC -m64"
 fi
 
-# Add -fwrapv flag if supported by the compiler.
-# This is needed to support clang (#12430).
-export CFLAGS="$CFLAGS `testcflags.sh -fwrapv`"
-
-
-# Program around weird bug in build process:
-#      Apparently if you have this:
-#         export DISTUTILS_DEBUG=1
-#      in your environment variables, the build craps out.  No idea why this
-#       is.
-#       -- Yi Qiang
-#
-# This bug was fixed in Python, but not yet in Python 2.7.2. So this fix
-# can be removed the next time we upgrade our version of Python. See
-#
-#   http://bugs.python.org/issue6954
-#
-# for the fix.
-#
-unset DISTUTILS_DEBUG
-
+# Enable some C99 features on Solaris. This in particular enables the
+# isinf() and isfinite() functions. It works both for C and C++ code
+# (which is not true for -std=c99).
+# See http://trac.sagemath.org/sage_trac/ticket/14265
+if [ "$UNAME" = SunOS ]; then
+    export CFLAGS="-D__C99FEATURES__ $CFLAGS"
+fi
 
 
 build()
 {
-    ./configure $EXTRAFLAGS --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
-        --enable-unicode=ucs4 --enable-shared
+    ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
+        --enable-unicode=ucs4 --enable-shared $PYTHON_CONFIGURE
 
     if [ $? -ne 0 ]; then
         echo >&2 "Error configuring Python."
@@ -147,15 +130,13 @@ fi
 
 echo "Testing importing of various modules..."
 import_errors=false
-for module in math hashlib crypt ; do
-   "$SAGE_LOCAL/bin/python" -c "import $module"
-   if [ $? -eq 0 ] ; then
-      echo "$module module imported OK"
-   else
-      echo >&2 "$module module failed to import"
-      import_errors=true
-      # exit 1 # not yet
-   fi
+for module in ctypes math hashlib crypt readline socket ; do
+    if python -c "import $module"; then
+        echo "$module module imported OK"
+    else
+        echo >&2 "$module module failed to import"
+        import_errors=true
+    fi
 done
 
 if $import_errors; then
@@ -170,4 +151,3 @@ if $import_errors; then
     fi
     exit 1
 fi
-
