Trac 21087: tab -> 4 spaces

diff --git a/build/pkgs/sip/spkg-install b/build/pkgs/sip/spkg-install
--- a/build/pkgs/sip/spkg-install
+++ b/build/pkgs/sip/spkg-install
@@ -11,20 +11,20 @@ cd src/
 python configure.py
 if [ $? -ne 0 ]
 then
-	echo "Configuration of sip failed"
-	exit 1
+    echo "Configuration of sip failed"
+    exit 1
 fi
 
 ${MAKE}
 if [ $? -ne 0 ]
 then
-	echo "Build of sip failed"
-	exit 1
+    echo "Build of sip failed"
+exit 1
 fi
 
 ${MAKE} install
 if [ $? -ne 0 ]
 then
-	echo "Installation of sip failed"
-	exit 1
+    echo "Installation of sip failed"
+    exit 1
 fi
