Fixup finding crt dest dir

diff --git a/build/pkgs/gfortran/spkg-postinst b/build/pkgs/gfortran/spkg-postinst
--- a/build/pkgs/gfortran/spkg-postinst
+++ b/build/pkgs/gfortran/spkg-postinst
@@ -1,14 +1,18 @@
 # -*- mode: shell-script -*-
 
-# #27907: Symlink crt1.o and friends where gcc can find it.
+# #27907: Symlink crt1.o and friends where gfortran can find it.
 if [ -n "$SAGE_CRTI_DIR" ]; then
    INSTALLED_SCRIPTS_DEST="$SAGE_SPKG_SCRIPTS/$PKG_BASE"
-   LIBGCC=$(dirname -- $("$SAGE_LOCAL"/bin/gcc -print-libgcc-file-name))
+   LIBGCC=$(dirname -- $("$SAGE_LOCAL"/bin/gfortran -print-libgcc-file-name))
+   if [ -z "$LIBGCC" -o ! -d "$LIBGCC" ]; then
+       echo >&2 "Warning: Unable to locate LIBGCC directory, so cannot install crt symlinks"
+       exit
+   fi
    echo "Installing symlinks to crt files."
    echo "# Remove symlinks created by spkg-postinst" >> "$INSTALLED_SCRIPTS_DEST"/spkg-postrm
    for f in "$SAGE_CRTI_DIR"/*crt?.o; do
        if [ -r $f -a ! -r "$LIBGCC"/$f ]; then
-          ln -s $f "$LIBGCC"
+          ln -s $f "$LIBGCC"/
           fb=`basename $f`
           echo "rm -f \"$LIBGCC\"/$fb" >> "$INSTALLED_SCRIPTS_DEST"/spkg-postrm
        fi
