=== pari-2.4.3.alpha.p4 (Jeroen Demeyer, January 11th, 2010) ===  * Ticket #10430 (fixing also #9620, #10279, #10369, #10559)  * Use `patch` to apply patches (at -p0 level because this is how svn    gives the diffs).  * Apply patches for PARI bugs 1084, 1132, 1141, 1143, 1144.  * Move all comments about the patches to patches/README.txt  * Simplify the "install" part of spkg-install by doing "make install"    instead of copying everything by hand.  This requires a small patch    to config/Makefile.SH (install_doc_no_make.patch) to ensure that    "make install-doc" does not build the documentation.  * Add patch Makefile_mv.patch to fix race condition in parallel make    install, see    http://pari.math.u-bordeaux.fr/cgi-bin/bugreport.cgi?bug=1148  * Add patch perl_path.patch to change first line of all perl scripts    to "#!/usr/bin/env perl" (#10559).  * Add src/desc/pari.desc after config/get_MANIFEST in spkg-make to    remove build-time dependency on perl

diff --git a/build/pkgs/pari/spkg-install b/build/pkgs/pari/spkg-install
--- a/build/pkgs/pari/spkg-install
+++ b/build/pkgs/pari/spkg-install
@@ -10,60 +10,34 @@ if [ -z "$SAGE_LOCAL" ]; then
 fi
 
 TOP=`pwd`
-PATCHED="$TOP/patches/files"
 
-###########################################################
-## Patching src files.  See patches/README.txt for details.
-###########################################################
-
+#######################################################################
+# Apply all patches.  See patches/README.txt for details about the
+# patches.
+#######################################################################
 cd src
-
-# These two are needed so that Sage can catch PARI's error signals.
-# In addition, let PARI use "GMP internals" (access members of GMP
-# structures directly) *conditionally*. (We *don't* disable that by
-# default, since at least currently this is compatible with both GMP
-# *and* MPIR. To disable the use, add "-DPARI_DONT_USE_GMP_INTERNALS"
-# to CFLAGS. This is a trivial patch to mp.c only; see also the comment
-# there.):
-cp "$PATCHED/init.c"  src/language/init.c
-cp "$PATCHED/mp.c"    src/kernel/gmp/mp.c
-
-# cwitty: Disable -rpath:
-cp "$PATCHED/get_ld" config/
-
-# John Cremona: Copy over a lightly patched get_tests, so that "make
-# test-all" does not test ellglobalred (which requires the elldata
-# package Sage does not install, nor ship, since it is about 14 MB):
-cp "$PATCHED/get_tests" config/
-
-# leif: Catch invalid arguments to "--graphic" (and treat such as an error)
-# since otherwise strange compilation errors might occur (cf. #9722, too).
-cp "$PATCHED/get_config_options" config/
-
-# leif: Explicitly link against libstdc++ when using FLTK (for plotting) to
-# support Fedora 13, and do an extra check for the FLTK include dir (cf. #9722):
-cp "$PATCHED/get_fltk" config/
-
-# leif: Also search */lib64/* for X11 libraries (since on some systems this
-# is really a separate directory, i.e. neither a symbolic link to */lib/* nor
-# the target of a symbolic link */lib/*; cf. #9722, too):
-cp "$PATCHED/get_X11" config/
-
-# Add -fno-common to DLCFLAGS on all Darwin systems instead of
-# PPC/PPC64 only.
-cp "$PATCHED/get_dlcflags" config/
+for patch in ../patches/*.patch; do
+    patch -p0 <$patch
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying $patch"
+        exit 1
+    fi
+done
 
 
-# This is needed or there are weird locale problems involving rpath
-# with building Sage:
-LC_ALL=C
-export LC_ALL
-LANG=C
-export LANG
-
-
-build()
+# Prepare all variables for building PARI/GP, except for CFLAGS
+set_environment()
 {
+    # Save current working directory (the src directory)
+    CUR=`pwd`
+
+    # This is needed or there are weird locale problems involving rpath
+    # with building Sage:
+    LC_ALL=C
+    export LC_ALL
+    LANG=C
+    export LANG
+
     # Add the proper flags for 64-bit build mode on OS X and OpenSolaris x64.
     # Setting CFLAGS is not sufficient on Solaris since PARI 2.4.3, as this
     # flag is not being used when the checks for GMP and Readline are made,
@@ -80,18 +54,6 @@ build()
         CFLAGS="$CFLAGS $CFLAG64"
         CC="$CC $CFLAG64" && export CC
     fi
-
-    if [ "x$SAGE_DEBUG" = xyes ]; then
-       # Disable optimisation, add debug symbols. Good for debugging or
-       # working around compiler bugs:
-       CFLAGS="$CFLAGS -O0 -g"
-    else
-       CFLAGS="-O3 -g $CFLAGS" # Default optimisation, with debug symbols.
-                               # Prepend to not override user's setting.
-    fi
-    export CFLAGS
-
-    CUR=`pwd`
 
     # On my systems PARI does *not* build correctly with these set! (and
     # they are set by sage-env).  It builds, but doesn't run.  Something
@@ -185,7 +147,20 @@ build()
     # The following get set because we pass the respective parameters:
     # prefix kernel with_gmp with_readline
 
+    # Make flags for building (not installing) PARI/GP
+    PARI_MAKEFLAGS="-k"
+    if [ "$UNAME" = "CYGWIN" ]; then
+        # There are weird bugs in PARI's build process on Windows XP
+        # under Cygwin.
+        # Passing in these extra flags gets around the bug.
+        PARI_MAKEFLAGS="$PARI_MAKEFLAGS 'GMPINCLUDE=-I$SAGE_LOCAL/include' EXTRADLLDFLAGS=-lgmp"
+    fi
+}
 
+
+# Build PARI/GP
+build()
+{
     # Configure PARI/GP, forcing bash instead of /bin/sh.  It is not
     # strictly necessary to use bash, but it hopefully makes the script
     # less system-dependent.  Since Sage assumes the existence of bash
@@ -197,71 +172,40 @@ build()
         --kernel=gmp
 
     if [ $? -ne 0 ]; then
-        echo "Error: Configuring PARI with readline and GMP kernel failed."
+        echo >&2 "Error: Configuring PARI with readline and GMP kernel failed."
         exit 1
     fi
 
     if [ ! -f Makefile ]; then
-        echo "Error: Unable to configure PARI: No Makefile generated!"
+        echo >&2 "Error: Unable to configure PARI: No Makefile generated!"
         exit 1
     fi
 
-    echo "Building and installing PARI/GP..."
-    if [ "$UNAME" = "CYGWIN" ]; then
-        # There are weird bugs in PARI's build process on Windows XP
-        # under Cygwin.
-        # Passing in this extra flag gets around the bug.
-        $MAKE GMPINCLUDE="-I$SAGE_LOCAL/include" EXTRADLLDFLAGS=-lgmp gp
-    else
-        $MAKE gp
+    $MAKE $PARI_MAKEFLAGS gp
+    if [ $? -ne 0]; then
+        echo >&2 "Error: building PARI/GP failed."
     fi
+}
 
+
+install()
+{
+    echo "Installing PARI/GP..."
+
+    $MAKE install install-lib-sta
     if [ $? -ne 0 ]; then
-        echo "Error building GP"
+        echo >&2 "Error installing PARI"
         exit 1
     fi
-
-    cp -f gp "$SAGE_LOCAL/bin/"    # avoid "make install"
-
-    # Install documentation source (compressed), for use by gphelp:
-    mkdir -p "$SAGE_LOCAL/share/pari/doc/"
-    cp -f doc/usersch*.tex "$SAGE_LOCAL/share/pari/doc/"
-    bzip2 -9 -f "$SAGE_LOCAL/share/pari/doc/"usersch*.tex
-    cp -f doc/translations "$SAGE_LOCAL/share/pari/doc/"
-
-    # And install gphelp:
-    cp -f doc/gphelp "$SAGE_LOCAL/bin/"
-
-    $MAKE install-lib-sta
-
-    if [ $? -ne 0 ]; then
-        echo "Error installing PARI's static library"
-        exit 1
-    fi
-
-    # Instead of "make install" we do the following, to avoid building
-    # the PARI documentation (which requires latex; or more precisely,
-    # *hangs* under a default Cygwin with latex, since some fonts are missing):
-    cd "`config/objdir`"
-    $MAKE install-include
-
-    if [ $? -ne 0 ]; then
-        echo "Error installing PARI's include files"
-        exit 1
-    fi
-
-    cp -f libpari* "$SAGE_LOCAL/lib/"
-    cd "$CUR"
 
     # On Cygwin, we need the dll for PARI to be in the same
     # directory as the gp binary, or it doesn't find it.
     # Note that just using a symlink doesn't work.
     if [ "$UNAME" = "CYGWIN" ]; then
-        CUR=`pwd`
         cd "$SAGE_LOCAL"/bin/
         cp -f "$SAGE_LOCAL"/lib/*pari*.dll .
-        cd "$CUR"
     fi
+    cd "$CUR"
 
     if [ "$UNAME" = "Darwin" ]; then
         # The following is a hack to get the library installed correctly
@@ -269,37 +213,45 @@ build()
         echo "Applying Mac OS X hack -- deleting and reinstalling libpari.a ..."
         rm -f Odarwin-ppc/*lib*
         $MAKE install-lib-sta
-
         if [ $? -ne 0 ]; then
-            echo "Error reinstalling PARI's static libraries (OS X trick)"
+            echo >&2 "Error reinstalling PARI's static libraries (OS X trick)"
             exit 1
         fi
 
-        cd "`config/objdir`"
-        cp -f libpari* "$SAGE_LOCAL"/lib
+        cd "`config/objdir`" && cp -f libpari* "$SAGE_LOCAL/lib"
+        if [ $? -ne 0 ]; then
+            echo >&2 "Error copying PARI's libraries (OS X trick)"
+            exit 1
+        fi
         cd "$CUR"
-    fi
-
-    echo "Installing extra Galois groups data..."
-    $MAKE install-data
-    if [ $? -ne 0 ]; then
-        echo "Error installing extra Galois groups data."
-        exit 1
     fi
 
     # Copy gprc.expect to $SAGE_LOCAL/etc
     cp -f "$TOP/gprc.expect" "$SAGE_LOCAL/etc"
     if [ $? -ne 0 ]; then
-        echo "Error installing gprc.expect"
+        echo >&2 "Error installing gprc.expect"
         exit 1
     fi
 }
 
-build
 
-# All (previous) errors are catched in build(), so we don't test $? here.
-# Although we perhaps should also check success of the numerous copy commands
-# inside build().
+set_environment
+
+# Set CFLAGS
+if [ "$SAGE_DEBUG" = yes ]; then
+    # Disable optimisation, add debug symbols.
+    CFLAGS="$CFLAGS -O0 -g"
+else
+    # Use PARI's default CFLAGS (with -g added).
+    # PARI's Configure adds -O3 to the CFLAGS, so we don't need to add
+    # it explicitly.
+    CFLAGS="-g $CFLAGS"
+fi
+
+export CFLAGS
+build
+install
+
 
 if [ "$UNAME" = "Darwin" ]; then
     pari_shlib="libpari.dylib"
@@ -310,4 +262,3 @@ if [ ! -f "$SAGE_LOCAL/lib/$pari_shlib" ]; then
     echo "Error: PARI's shared library $pari_shlib has not been installed!"
     exit 1
 fi
-
