#9959: Add gprc.expect file to be installed in $SAGE_LOCAL/etc #9959: Remove $detex = 1; from gphelp.in patch

diff --git a/build/pkgs/pari/spkg-install b/build/pkgs/pari/spkg-install
--- a/build/pkgs/pari/spkg-install
+++ b/build/pkgs/pari/spkg-install
@@ -306,6 +306,13 @@ build()
         echo "Error installing extra Galois groups data."
         exit 1
     fi
+
+    # Copy gprc.expect to $SAGE_LOCAL/etc
+    cp -f "$TOP/gprc.expect" "$SAGE_LOCAL/etc"
+    if [ $? -ne 0 ]; then
+        echo "Error installing gprc.expect"
+        exit 1
+    fi
 }
 
 build
