#11686: Avoid race conditions when creating directories.
Document how Sage overrides the user's setting of the environment
variable MPLCONFIGDIR.

Use 'patch' for installing patches.

Replaced the 'src' directory with a freshly downloaded copy of the
source.

diff --git a/build/pkgs/matplotlib/spkg-install b/build/pkgs/matplotlib/spkg-install
--- a/build/pkgs/matplotlib/spkg-install
+++ b/build/pkgs/matplotlib/spkg-install
@@ -15,9 +15,28 @@ fi
 # Write a configuration file to src/setup.cfg
 python make-setup-config.py
 
-# Use patched versions.  See SPKG.txt for why and what.
-$CP patches/setupext.py src
 cd src
+
+# Apply patches for all platforms.  See SPKG.txt for information about
+# what each patch does.
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
+# Apply patches for OS X.
+if [ "$UNAME" = "Darwin" ]; then
+    for patch in ../patches/Darwin/*.patch; do
+	patch -p1 <"$patch"
+	if [ $? -ne 0 ]; then
+            echo >&2 "Error applying '$patch'"
+            exit 1
+	fi
+    done
+fi
 
 # Now build
 python setup.py build
@@ -31,3 +50,15 @@ rm -rf "$SAGE_LOCAL"/lib/python/site-packages/matplotlib
 
 # Finally install
 python setup.py install
+
+# Print value of MPLCONFIGDIR
+MPLINITFILE="$SAGE_LOCAL/lib/python/site-packages/matplotlib/__init__.py"
+if [ -f "$MPLINITFILE" ]; then
+    MPLVERSION=`sed -n "/^__version__[ ]*=/s/[^']*'\([^']*\)'.*$/\1/p" "$MPLINITFILE"`
+    echo
+    echo "When Sage runs, MPLCONFIGDIR will be set to '\$DOT_SAGE/matplotlib-$MPLVERSION'."
+    echo
+else
+    echo "$MPLINITFILE not found.  What happened?"
+    exit 1
+fi
