polymake: Set ARCHFLAGS instead of using our broken patch

diff --git a/build/pkgs/polymake/spkg-install b/build/pkgs/polymake/spkg-install
--- a/build/pkgs/polymake/spkg-install
+++ b/build/pkgs/polymake/spkg-install
@@ -7,12 +7,22 @@ die () {
 
 cd src
 
-patch -p1 < ../patches/polymake_sage.patch || die "Error: Couldn't apply patch."
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
 more_configure_options=
 
 if [ `uname` = Darwin ]; then
     more_configure_options="$more_configure_options --without-fink"
+    # Setting the following variable changes the output of "perl
+    # -MExtUtils::Embed -e ldopts" and "perl -MExtUtils::Embed -e ccflags"
+    # so that they do not contain -arch flags.
+    export ARCHFLAGS=
 fi
 
 ./configure --without-java \
