Handle errors. Remove old installation before installing

diff --git a/build/pkgs/polymake/spkg-install b/build/pkgs/polymake/spkg-install
--- a/build/pkgs/polymake/spkg-install
+++ b/build/pkgs/polymake/spkg-install
@@ -1,5 +1,10 @@
 #!/usr/bin/env bash
 
+die () {
+    echo "$@" 1>&2
+    exit 1
+}
+
 cd src
 
 patch -p1 < ../patches/polymake_sage.patch || die "Error: Couldn't apply patch."
@@ -17,6 +22,9 @@ fi
             --includedir="$SAGE_LOCAL"/include \
             --bindir="$SAGE_LOCAL"/bin \
             --libdir="$SAGE_LOCAL"/lib \
-	    $more_configure_options
-make
-make install
+	    $more_configure_options || die "Error configuring Polymake"
+make || die "Error building polymake"
+# Remove old stuff. Polymake loads whatever it finds in
+# its installation directory.
+rm -Rf $SAGE_LOCAL/lib/polymake
+make install || die "Error installing polymake"
