#13844: Install manifest file on Cygwin for Windows 7

diff --git a/build/pkgs/patch/spkg-install b/build/pkgs/patch/spkg-install
--- a/build/pkgs/patch/spkg-install
+++ b/build/pkgs/patch/spkg-install
@@ -1,18 +1,9 @@
 #!/usr/bin/env bash
 
-if [ -z $SAGE_LOCAL ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
-fi
-
-if [ "x$UNAME" = xCYGWIN ] ; then
-   if ! patch --version | grep >/dev/null 'patch '; then
-      echo "On Cygwin you must have patch installed"
-      echo "via the Cygwin setup.exe program"
-      exit 1
-   fi
-   exit 0
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "Error: SAGE_LOCAL undefined - exiting..."
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
 # Let the user define the environment variable CFLAG64 to
@@ -20,14 +11,12 @@ fi
 # -m64 to build 64-bit objects. This would be the case with IBM's
 # compiler on AIX and HP's compiler on HP-UX. But -m64 works
 # with both GCC and SunStudio.
-
 if [ -z $CFLAG64 ] ; then
    CFLAG64="-m64"
 fi
 
 # Create a 64-bit build if the environment variable SAGE64 is set to
 # "yes".
-
 if [ "x$SAGE64" = xyes ] ; then
    echo "Creating a 64-bit version of GNU patch"
    CFLAGS="$CFLAGS $CFLAG64"
@@ -39,7 +28,6 @@ fi
 # Disable debugging information on AIX, as this causes link errors. See:
 # http://www.ibm.com/developerworks/forums/thread.jspa?threadID=348558
 # http://gcc.gnu.org/bugzilla/show_bug.cgi?id=46072
-
 if [ "x$UNAME" = xAIX ] ; then
    CFLAGS="$CFLAGS -g0"
    export CFLAGS
@@ -48,29 +36,30 @@ fi
 cd src
 
 ./configure --prefix="$SAGE_LOCAL"
-
 if [ $? -ne 0 ]; then
-    echo "Error configuring GNU patch"
+    echo >&2 "Error configuring GNU patch"
     exit 1
 fi
 
 $MAKE
-
 if [ $? -ne 0 ]; then
-    echo "Error building GNU patch"
+    echo >&2 "Error building GNU patch"
     exit 1
 fi
 
 $MAKE install
-
 if [ $? -ne 0 ]; then
-    echo "Error installing GNU patch"
+    echo >&2 "Error installing GNU patch"
     exit 1
+fi
+
+if [ "$UNAME" = "CYGWIN" ] ; then
+    cp ../patch.exe.manifest "$SAGE_LOCAL/bin/"
 fi
 
 # Sanity check that we have the correct version of patch
 # in our PATH.
 if ! patch --version | grep >/dev/null 'patch 2\.5\.9'; then
-    echo "Cannot find the patch program we just installed"
+    echo >&2 "Cannot find the patch program we just installed"
     exit 1
 fi
