Updated SPKG.txt and spkg-check.

diff --git a/build/pkgs/sagetex/spkg-check b/build/pkgs/sagetex/spkg-check
--- a/build/pkgs/sagetex/spkg-check
+++ b/build/pkgs/sagetex/spkg-check
@@ -2,20 +2,30 @@
 
 # this runs Sage on the generated .sage files to see if they work ok
 
+function checkdotsage
+{
+    # this is kinda lame, that we run the script twice, but I'm not sure
+    # how to check for failures. Having trac #2861 work would make this
+    # easy.
+    sage $1.sage
+    if [ $(sage $1.sage 2>&1 | grep -c 'failed') -gt 0 ]
+    then
+        echo "Error running Sage on $1.sage!"
+        exit 1
+    else
+        echo "No problem (that this script can detect) running Sage on $1.sage."
+    fi
+}
+
 if [ "$(which latex)" != "" ]
 then
     cd src
-    for F in example sagetexpackage
-    do
-	latex $F
-	if [ $(sage $F.sage 2>&1 | grep -c 'failed') -gt 0 ]
-	then
-	    echo "Error running Sage on $F.sage!"
-	    exit 1
-	else
-	    echo "No problem (that this script can detect) running Sage on $F.sage."
-	fi
-    done
+
+    latex example.tex > /dev/null
+    checkdotsage example
+
+    latex sagetexpackage.dtx > /dev/null
+    checkdotsage sagetexpackage
 else
     echo "LaTeX isn't installed (or isn't in \$PATH); skipping test."
 fi
