skip checks if we do not use the system pkg-config

diff --git a/build/pkgs/pkgconf/spkg-check b/build/pkgs/pkgconf/spkg-check
--- a/build/pkgs/pkgconf/spkg-check
+++ b/build/pkgs/pkgconf/spkg-check
@@ -1,5 +1,16 @@
 #!/usr/bin/env bash
 
+# Skip checks if we don't use the system pkg-config
+grep 'exec pkgconf ' "$SAGE_LOCAL/bin/pkg-config" >/dev/null
+if [ $? -eq 0 ]; then
+    echo "Skipping the tests, since no system-wide 'pkg-config' was present"
+    echo "when 'pkgconf' got installed."
+    echo "Remember to afterwards reinstall Sage's 'pkgconf' if you later decide"
+    echo "to install a system-wide version of 'pkg-config'."
+    exit 0
+fi
+
+
 # PC files that we do not ship but are likely available (mostly GUI stuff)
 pc_files="fontconfig gtk+-3.0 harfbuzz x11"
 
@@ -16,7 +27,7 @@ for dir in $search_dirs; do
                 echo "    +-- $pc found, using it for the pkg-config test."
                 pkg-config --exists "$pc"
                 if [ $? -ne 0 ]; then
-                    echo >&2 "Our pkg-config script failed to pick up $pc"
+                    echo >&2 "Error: Our pkg-config script failed to pick up $pc"
                     exit 1
                 fi
             else
