Do not hardcode the non-posix install program

diff --git a/build/pkgs/pkgconf/spkg-install b/build/pkgs/pkgconf/spkg-install
--- a/build/pkgs/pkgconf/spkg-install
+++ b/build/pkgs/pkgconf/spkg-install
@@ -2,6 +2,15 @@
 
 cd src
 
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
 # Workaround for bugs with -D_FORTIFY_SOURCE=2 on antiques
 export CPPFLAGS='-U_FORTIFY_SOURCE'
 
