#11666: Let MPFR read CFLAGS in MPIR headers, remove MAKE trick.

diff --git a/build/pkgs/mpfr/spkg-install b/build/pkgs/mpfr/spkg-install
--- a/build/pkgs/mpfr/spkg-install
+++ b/build/pkgs/mpfr/spkg-install
@@ -1,29 +1,21 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+if [ -z "$SAGE_LOCAL" ]; then
+    echo "Error: SAGE_LOCAL undefined - exiting..."
+    echo "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
-# unset RM since it messes with libtool for "make check"
+# unset RM since it messes with libtool
 unset RM
 
-build()
+mpfr_patch()
 {
-    if [ "$SAGE64" = "yes" ]; then
-         echo "64 bit build"
-         CFLAGS="-O2 -g -m64 "; export CFLAGS
-         CXXFLAGS="-O2 -g -m64 "; export CXXFLAGS
-         CPPFLAGS="-O2 -g -m64 "; export CPPFLAGS
-    fi
-
-    EXTRA=""
     # Apply a patch on Solaris, but only on the sun4v architecture
-    # by default. On other Solaris systems, it can be over-ridden
+    # by default. On other Solaris systems, it can be overridden
 
     # The patch to the C code was developed by Paul Zimmermann, the patch
-    # to the spkg-install by David Kirkby. See  Ticket #6453
+    # to the spkg-install by David Kirkby. See Ticket #6453
 
     if [ `uname` = "SunOS" ]; then
        # Add a patch to MPFR on Solaris if either:
@@ -82,27 +74,161 @@ build()
           cp ../patches/mpn_exp.c mpn_exp.c
        fi
     fi
+
+}
+
+mpfr_get_upstream_selected_cflags() # Get MPFR's choice on empty CC and CFLAGS.
+{
+    if [ $# -ne 1 ]; then
+        echo "Error: mpfr_get_upstream_selected_cflags() requires 'file' parameter."
+        exit 1
+    fi
+    header_file=$1
+    mpfr_cc_pat="s/^CC='\([^']*\)'/\1/p"
+    mpfr_cflags_pat="s/^CFLAGS='\([^']*\)'/\1/p"
+    if ! [ -f "$header_file" ]; then
+        upstream_cc=""
+        upstream_cflags=""
+        return 1
+    fi
+    upstream_cc=`sed -n -e "$mpfr_cc_pat" "$header_file"`
+    upstream_cflags=`sed -n -e "$mpfr_cflags_pat" "$header_file"`
+    return 0
+}
+
+mpfr_configure()
+{
+    sage_cc=$CC # Save Sage CC, because we need to unset it later.
+    user_cflags=$CFLAGS # Save them. 'sage-env' sets CC, but not CFLAGS.
+    required_cflags="" # Additional mandatory settings required by Sage, accumulated below.
+    default_cflags="" # Spkg defaults that can and might get overridden.
+
+    if [ "$SAGE_DEBUG" = yes ]; then
+        # Disable optimization, add debug symbols:
+        required_cflags="$required_cflags -g -O0"
+        echo "Warning: Building MPFR with SAGE_DEBUG=yes disables optimization."
+    else
+        # Add debug symbols by default, enable optimization, but do not (yet)
+        # add processor-specific flags (these are eventually added later):
+        default_cflags="$default_cflags -g -O3"
+    fi
+
+    if [ "$SAGE64" = "yes" ]; then
+        echo "Building a 64-bit version of MPFR."
+        default_cflags="$default_cflags -m64"
+    else
+        default_cflags="$default_cflags"
+    fi
+
+    SAGE_CONF_OPTS=--libdir="$SAGE_LOCAL/lib"
     if [ ! -f "$SAGE_LOCAL/include/gmp.h" ]; then
-         EXTRA="--disable-static --enable-shared"
+         SAGE_CONF_OPTS="$SAGE_CONF_OPTS --disable-static --enable-shared"
     fi
 
     if [ $UNAME = "CYGWIN" ]; then
-         EXTRA="--disable-static --enable-shared"
+         SAGE_CONF_OPTS="$SAGE_CONF_OPTS --disable-static --enable-shared"
+
     fi
 
-    ./configure --prefix=$SAGE_LOCAL --libdir="$SAGE_LOCAL/lib" --with-gmp=$SAGE_LOCAL \
-                 CFLAGS="$CFLAGS $SHAREDFLAGS -O2" CXX="$CXX" \
-                 CXXFLAGS="$CXXFLAGS $SHAREDFLAGS" LDFLAGS="$LDFLAGS" \
-                 GMP_PREFIX="$SAGE_LOCAL" $EXTRA
+    # Pre-configure MPFR to get the settings it would use if CC and CFLAGS were empty:
+    echo "Checking what CC and CFLAGS MPFR would use if they were empty..."
+    if (unset CC CFLAGS CPPFLAGS CXXFLAGS &&
+        ./configure --with-gmp="$SAGE_LOCAL" $SAGE_CONF_OPTS $MPFR_EXTRA_OPTS) &>/dev/null;
+    then
+        if mpfr_get_upstream_selected_cflags config.status; then
+            mpfr_cflags=$upstream_cflags
+            mpfr_cc=$upstream_cc
+            echo "Settings chosen by MPFR when configuring with CC and CFLAGS unset:"
+            echo "  CC:      $mpfr_cc"
+            echo "  CFLAGS:  $mpfr_cflags"
+        else
+            echo "Warning: Couldn't determine MPFR-selected CC and CFLAGS from 'mpfr.h'"
+        fi
+    else
+        # We ignore errors in the first place, since we redirected all
+        # messages to /dev/null. (The messages can be found in the 'config.log'
+        # files if someone really wants to read them.)
+        :;
+    fi
+    find . -name config.cache -o -name config.status -exec rm -f {} \;
+    CC=$sage_cc
+
+    echo "Settings required to properly build MPFR, taking into account SAGE_DEBUG etc.:"
+    echo "  CFLAGS:  $required_cflags"
+    echo "  LDFLAGS: $LDFLAGS" # Might be empty, or specified by the user.
+    echo "  ABI:     $ABI" # Might be empty, or specified by the user.
+    echo "Settings from the \"global\" environment:"
+    echo "  CC:      $CC" # Set by Sage, maybe overridden by the user.
+    echo "  CFLAGS:  $user_cflags"
+    echo "  (CPPFLAGS, CXX and CXXFLAGS are listed below; these don't get modified.)"
+
+    if [ -z "$user_cflags" ]; then
+        # No CFLAGS specified by user => Use either MPFR's or our default ones,
+        # plus those required by Sage for the package to build properly:
+        if [ -n "$mpfr_cflags" ]; then
+            # Fine. Use upstream settings.
+            echo "Using MPFR's settings (plus mandatory ones)."
+            CFLAGS="$mpfr_cflags $required_cflags"
+        else # Use spkg's defaults.
+            echo "Using the spkg's (i.e. Sage's) default (plus mandatory) settings."
+            CFLAGS="$default_cflags $required_cflags"
+        fi
+    else
+        # CFLAGS were specified by the user, so don't override them (unless
+        # necessary).
+        echo "Using user-specified settings (overriding defaults), with some additions."
+        CFLAGS="$default_cflags $user_cflags $required_cflags"
+    fi
+
+    echo "Finally using the following settings:"
+    echo "  CC=$CC"
+    echo "  CFLAGS=$CFLAGS"
+    echo "  CPPFLAGS=$CPPFLAGS"
+    echo "  CXX=$CXX"
+    echo "  CXXFLAGS=$CXXFLAGS"
+    echo "  LDFLAGS=$LDFLAGS"
+    echo "  ABI=$ABI"
+    echo "(These settings may still get overridden by 'configure' or Makefiles.)"
+
+    ###############################################################################
+    # Now really configure MPFR with proper settings:
+    ###############################################################################
+    if [ -z "$MPFR_EXTRA_OPTS" ]; then
+        echo "Configuring MPFR with the following options:"
+        echo "    --prefix=\"$SAGE_LOCAL\" --with-gmp=\"$SAGE_LOCAL\" $SAGE_CONF_OPTS"
+        echo "You can set MPFR_EXTRA_OPTS to pass additional parameters."
+    else
+        echo "Using additional 'configure' options as specified with" \
+            "MPFR_EXTRA_OPTS:"
+        echo "    $MPFR_EXTRA_OPTS"
+        echo "Configuring MPFR with the following options:"
+        echo "    --prefix=\"$SAGE_LOCAL\" --with-gmp=\"$SAGE_LOCAL\" $SAGE_CONF_OPTS $MPFR_EXTRA_OPTS"
+    fi
+
+    ./configure --prefix="$SAGE_LOCAL" --with-gmp="$SAGE_LOCAL" $SAGE_CONF_OPTS $MPFR_EXTRA_OPTS
+}
+
+mpfr_build()
+{
+    echo "Patching MPFR"
+    mpfr_patch
     if [ $? -ne 0 ];  then
-        echo >&2 "Error configuring mpfr."
+        echo >&2 "Error patching MPFR."
+        exit 1
+    fi
+
+    echo "Configuring MPFR"
+    mpfr_configure
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error configuring MPFR."\
+            "(See above for the options passed to it.)"
         exit 1
     fi
 
     echo "Building MPFR"
     $MAKE
     if [ $? -ne 0 ];  then
-        echo >&2 "Error building mpfr."
+        echo >&2 "Error building MPFR."
         exit 1
     fi
 
@@ -115,11 +241,11 @@ build()
     echo "Installing MPFR"
     $MAKE install
     if [ $? -ne 0 ];  then
-        echo >&2 "Error installing mpfr."
+        echo >&2 "Error installing MPFR."
         exit 1
     fi
 }
 
 cd src
 
-build
+mpfr_build
