Added package names in spkg-install

diff --git a/build/pkgs/tides/spkg-install b/build/pkgs/tides/spkg-install
--- a/build/pkgs/tides/spkg-install
+++ b/build/pkgs/tides/spkg-install
@@ -4,18 +4,18 @@ cd src
 
 ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib"
 if [ $? -ne 0 ]; then
-    echo >&2 "Error configuring PACKAGE_NAME."
+    echo >&2 "Error configuring TIDES."
     exit 1
 fi
 
 $MAKE
 if [ $? -ne 0 ]; then
-    echo >&2 "Error building PACKAGE_NAME."
+    echo >&2 "Error building TIDES."
     exit 1
 fi
 
 $MAKE -j1 install
 if [ $? -ne 0 ]; then
-    echo >&2 "Error installing PACKAGE_NAME."
+    echo >&2 "Error installing TIDES."
     exit 1
 fi
