Trac #12909: don't look in /sw or /usr/local for include files or libraries

diff --git a/build/pkgs/gdmodule/spkg-install b/build/pkgs/gdmodule/spkg-install
--- a/build/pkgs/gdmodule/spkg-install
+++ b/build/pkgs/gdmodule/spkg-install
@@ -1,23 +1,33 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage --sh'?"
+    exit 1
+fi
 
-# Used patched versions.  See SAGE.txt for why and what.
-$CP patches/_gdmodule.c src/
+cd src
 
-$CP patches/Setup.py src/
+# Apply patches.
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
 # Now build and install.
-cd src/
 python Setup.py build
 
 if [ $? -ne 0 ]; then
-    echo "Failure to build gdmodule"
+    echo >&2 "Error building gdmodule."
     exit 1
 fi
 
 python Setup.py install
 
 if [ $? -ne 0 ]; then
-    echo "Failure to install gdmodule"
+    echo >&2 "Error installing gdmodule."
     exit 1
 fi
