Trac #14662: Add symbolic link local/lib/ecl/ecl -> local/include/ecl

diff --git a/build/pkgs/ecl/spkg-install b/build/pkgs/ecl/spkg-install
--- a/build/pkgs/ecl/spkg-install
+++ b/build/pkgs/ecl/spkg-install
@@ -112,12 +112,17 @@ if [ $? -ne 0 ]; then
 fi
 
 # Create symbolic link to lib/ecl-version directory.
-# This is important when the Sage install is moved.
+# Also create a symbolic link lib/ecl/ecl -> include/ecl.
+# This is important when the Sage install is moved, see Trac #14662.
 cd "$SAGE_LOCAL/lib/" && rm -f ecl && ln -s ecl-* ecl
-
-# It is very important that the above line worked.
 if [ $? -ne 0 ]; then
     echo >&2 "Error - Failed to create symbolic link to ECL library"
+    echo >&2 "directory ... exiting"
+    exit 1
+fi
+cd "$SAGE_LOCAL/lib/ecl" && rm -f ecl && ln -s ../../include/ecl ecl
+if [ $? -ne 0 ]; then
+    echo >&2 "Error - Failed to create symbolic link to ECL include"
     echo >&2 "directory ... exiting"
     exit 1
 fi
