#11884:   * General clean-up: remove unneeded patches, remove some source     files (as described in "Special Update/Build Instructions"), etc.   * Check the error code when running 'patch' in spkg-install.   * Run configure with the option "--enable-unicode=no" -- this was     the default in previous versions of ecl, and using the new default     of "yes" causes problems with some strings.   * Run configure with the option "--with-gmp-prefix=$SAGE_LOCAL".

diff --git a/build/pkgs/ecl/spkg-install b/build/pkgs/ecl/spkg-install
--- a/build/pkgs/ecl/spkg-install
+++ b/build/pkgs/ecl/spkg-install
@@ -1,33 +1,27 @@
 #!/usr/bin/env bash
 
-if [ "x$SAGE_LOCAL" = x ] ; then
-   echo "Error - SAGE_LOCAL undefined ... exiting"
-   echo "Maybe run 'sage -sh'?"
+if [ -z "$SAGE_LOCAL" ] ; then
+   echo >&2 "Error - SAGE_LOCAL undefined ... exiting"
+   echo >&2 "Maybe run 'sage -sh'?"
    exit 1
 fi
 
-###############################################################
-# apply patch for the problem acknowledged upstream in
-# http://www.mail-archive.com/ecls-list@lists.sourceforge.net/msg00671.html
-# The patch itself comes from the following commit:
-# http://ecls.git.sourceforge.net/git/gitweb.cgi?p=ecls/ecl;a=commit;h=ce19c67a1b9f63cd232e7c0a621b6ca87aaa7214
-###############################################################
 cd src
-patch -p0 < ../patches/ecls-11.1.1-cmploc.lisp.patch
+# For some of the patches, Cygwin also has upstream fixes that are
+# closely related, keep track.  See Trac 11119, for example.
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
-# apply patches for Cygwin build
-# these patches is in ECL CVS, remove upon upgrade
-# Cygwin also has upstream fixes that are closely related, keep track
-# See Trac 11119
-patch -p0 < ../patches/libraries.d.patch
-patch -p0 < ../patches/unixint.d.patch
-patch -p0 < ../patches/math_fenv.h.patch
-
-if [ "x$CFLAG64" = x ] ; then
+if [ -z "$CFLAG64" ] ; then
    CFLAG64=-m64
 fi
 
-if [ "x$CXXFLAG64" = x ] ; then
+if [ -z "$CXXFLAG64" ] ; then
    CXXFLAG64=-m64
 fi
 
@@ -36,8 +30,6 @@ fi
 
 CPPFLAGS="$CPPFLAGS -I$SAGE_LOCAL/include"
 LDFLAGS="$LDFLAGS -L$SAGE_LOCAL/lib"
-
-
 
 # Compile for 64-bit if SAGE64 is set to 'yes'
 if [ "x$SAGE64" = "xyes" ]  ; then
@@ -56,7 +48,7 @@ else
 fi
 
 if [ "`uname -sm`" = "Darwin Power Macintosh" ] ; then
-# disbaling altivec instructions (trac 11297)
+# Disabling altivec instructions (trac 11297)
     CFLAGS="$CFLAGS -mno-altivec -mabi=no-altivec"
     export CFLAGS
 fi
@@ -86,8 +78,10 @@ export LDFLAGS
 # 'export MAKE='make -j n' where n>1, breaks ECL builds, so use only one thread
 MAKE="$MAKE -j1"
 
-# We clear MAKEFLAGS to fix building multiple spkgs in parallel on OS X.
-export MAKEFLAGS=
+# We clear MAKEFLAGS because of issues on OS X.
+if [ "$UNAME" = "Darwin" ]; then
+    export MAKEFLAGS=
+fi
 
 if [ "x`uname -sm`" = "xSunOS i86pc" ] && [ "x$SAGE64" = xyes ]  ; then
    # Need to add --with-dffi=no to disable assembly code on OpenSolaris x64.
@@ -96,13 +90,15 @@ if [ "x`uname -sm`" = "xSunOS i86pc" ] && [ "x$SAGE64" = xyes ]  ; then
    # 1) Solaris, Solaris Express or OpenSolaris (SunOS)
    # 2) Intel or AMD CPU
    # 3) 64-bit build
-   ./configure --prefix="$SAGE_LOCAL" --with-dffi=no
+   ./configure --prefix="$SAGE_LOCAL" --enable-unicode=no --with-dffi=no \
+       --with-gmp-prefix=$SAGE_LOCAL
 else
-   ./configure --prefix="$SAGE_LOCAL"
+   ./configure --prefix="$SAGE_LOCAL" --enable-unicode=no \
+       --with-gmp-prefix=$SAGE_LOCAL
 fi
 
 if [ $? -ne 0 ]; then
-   echo "Error - Failed to configure ECL ... exiting"
+   echo >&2 "Error - Failed to configure ECL ... exiting"
    exit 1
 fi
 
@@ -111,20 +107,20 @@ touch build/TAGS
 
 $MAKE
 if [ $? -ne 0 ]; then
-   echo "Error - Failed to build ECL ... exiting"
+   echo >&2 "Error - Failed to build ECL ... exiting"
    exit 1
 fi
 
 # Remove old install of ECL, if any.
 rm -rf "$SAGE_LOCAL/lib/ecl-"*
 if [ $? -ne 0 ]; then
-   echo "Error - Failed to remove old ECL install ... exiting"
+   echo >&2 "Error - Failed to remove old ECL install ... exiting"
    exit 1
 fi
 
 $MAKE install
 if [ $? -ne 0 ]; then
-   echo "Error - Failed to install ECL ... exiting"
+   echo >&2 "Error - Failed to install ECL ... exiting"
    exit 1
 fi
 
@@ -134,6 +130,7 @@ cd "$SAGE_LOCAL/lib/" && rm -f ecl && ln -s ecl-* ecl
 
 # It is very important that the above line worked.
 if [ $? -ne 0 ]; then
-   echo "Error - Failed to create ECL library symbolic link ... exiting"
+   echo >&2 "Error - Failed to create symbolic link to ECL library"
+   echo >&2 "directory ... exiting"
    exit 1
 fi
