build/pkgs/sage_setup/spkg-install: Install via setup.py bdist_wheel

diff --git a/build/pkgs/sage_setup/spkg-install b/build/pkgs/sage_setup/spkg-install
--- a/build/pkgs/sage_setup/spkg-install
+++ b/build/pkgs/sage_setup/spkg-install
@@ -1,6 +1,14 @@
 #!/usr/bin/env bash
-cd src
-. sage-dist-helpers
-# We install directly with setuptools, not with pip, because pip does not handle our symlinks correctly.
-# An alternative would be to build an sdist and then to install the sdist using pip.
-sage-python23 -u setup.py --no-user-cfg install --single-version-externally-managed --root=/
+# From sage-spkg.
+# For type=script packages, the build rule in build/make/Makefile sources
+# sage-env but not sage-dist-helpers.
+lib="$SAGE_ROOT/build/bin/sage-dist-helpers"
+source "$lib"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error: failed to source $lib"
+    echo >&2 "Is $SAGE_ROOT the correct SAGE_ROOT?"
+    exit 1
+fi
+# We build the wheel directly with "setup.py bdist_wheel", not with "pip wheel",
+# because pip does not handle our symlinks correctly.
+cd src && sage-python23 -u setup.py --no-user-cfg bdist_wheel && sdh_store_and_pip_install_wheel .
