Autotoolify bzip2 based on Suse patch.

diff --git a/build/pkgs/bzip2/spkg-install b/build/pkgs/bzip2/spkg-install
--- a/build/pkgs/bzip2/spkg-install
+++ b/build/pkgs/bzip2/spkg-install
@@ -17,12 +17,9 @@ fi
 
 export CFLAGS="-O2 -g $CFLAGS"
 
-cd src
+cd src/src
 
-########################################################################
 # Patch bzip2
-########################################################################
-
 for patch in ../patches/*.patch; do
     [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
     patch -p1 <"$patch"
@@ -32,45 +29,22 @@ for patch in ../patches/*.patch; do
     fi
 done
 
-########################################################################
-# Build bzip2
-########################################################################
+# Autotoolify bzip2
+cp -f ../autotools/* ./
 
-# Since bzip2 doesn't use configure, we need to pass flags as arguments
-# to make.
+./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error configuring bzip2"
+    exit 1
+fi
 
-# Static build
-$MAKE CC="$CC" CFLAGS="$CFLAGS"
+$MAKE
 if [ $? -ne 0 ]; then
     echo >&2 "Error building bzip2"
     exit 1
 fi
 
-$MAKE install PREFIX="$SAGE_LOCAL" CC="$CC" CFLAGS="$CFLAGS"
-if [ $? -ne 0 ]; then
-    echo >&2 "Error installing bzip2"
-    exit 1
-fi
-
-# Shared build
-case "$UNAME" in
-    "CYGWIN")
-        Makefile=Makefile-libbz2_dll
-        ;;
-    "Darwin")
-        Makefile=Makefile-libbz2_dylib
-        ;;
-    *)
-        Makefile=Makefile-libbz2_so
-        ;;
-esac
-$MAKE -f $Makefile CC="$CC" CFLAGS="$CFLAGS"
-if [ $? -ne 0 ]; then
-    echo >&2 "Error building bzip2"
-    exit 1
-fi
-
-$MAKE -f $Makefile install PREFIX="$SAGE_LOCAL" CC="$CC" CFLAGS="$CFLAGS"
+$MAKE install
 if [ $? -ne 0 ]; then
     echo >&2 "Error installing bzip2"
     exit 1
