3.8.p6: detect tuning error (#1532):

diff --git a/build/pkgs/atlas/spkg-install b/build/pkgs/atlas/spkg-install
--- a/build/pkgs/atlas/spkg-install
+++ b/build/pkgs/atlas/spkg-install
@@ -48,6 +48,13 @@ config
 
 build
 
+cd $CUR/ATLAS-build
+if [ -f error* ]; then
+    echo "ATLAS failed to build because your system is too heavily loaded to obtain accurate timing."
+    echo "Please restart the build by typing make, when the load on your system has decreased."
+    exit 1
+fi
+
 cd $CUR
 sh ./make_correct_shared.sh
 
