Trac #10226: rewrite spkg-install

diff --git a/build/pkgs/atlas/spkg-check b/build/pkgs/atlas/spkg-check
--- a/build/pkgs/atlas/spkg-check
+++ b/build/pkgs/atlas/spkg-check
@@ -1,40 +1,22 @@
 #!/usr/bin/env bash
 
-###########################################
-## ATLAS
-###########################################
+######################################################################
+### Sanity check
+######################################################################
 
 if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting"
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+    echo "SAGE_LOCAL undefined ... exiting"
+    echo "Maybe run sage -sh?"
+    exit 1
 fi
 
-check()
-{
-	# make sure everything builds correctly
-	cd $CUR/ATLAS-build
-	make check
-        if [ $? -ne 0 ]; then
-            echo "An error occurred when running the ATLAS self-tests."
-            exit 1
-        else
-           echo "The ATLAS self-tests successfully passed"
-        fi
+######################################################################
+### Skip building ATLAS on specific systems
+######################################################################
 
-
-	# and we should collect some timings
-	make time
-        if [ $? -ne 0 ]; then
-            echo "The ATLAS timing data failed to be collected"
-            exit 1
-        else
-           echo "The ATLAS timing data was successfully collected"
-           exit 0
-        fi
-}
-
-CUR=`pwd`
+if [ `uname` = "CYGWIN" ]; then
+    exit 0
+fi
 
 if [ `uname` = "Darwin" ]; then
     exit 0
@@ -45,4 +27,40 @@ if [ "x$SAGE_ATLAS_LIB" != "x" ]; then
     exit 0
 fi
 
-check
+
+######################################################################
+### check and collect timings
+######################################################################
+
+make_check()
+{
+    # make sure everything builds correctly
+    cd ATLAS-build
+    make check
+        if [ $? -ne 0 ]; then
+            echo "An error occurred when running the ATLAS self-tests."
+            exit 1
+        else
+            echo "The ATLAS self-tests successfully passed."
+        fi
+    cd ..
+}
+
+
+make_time()
+{
+    # collect some timings
+    cd ATLAS-build
+    make time
+        if [ $? -ne 0 ]; then
+            echo "The ATLAS timing data failed to be collected."
+            exit 1
+        else
+            echo "The ATLAS timing data was successfully collected."
+        fi
+    cd ..
+}
+
+
+make_check
+make_time
