Packaging polish.

diff --git a/build/pkgs/curl/spkg-install b/build/pkgs/curl/spkg-install
--- a/build/pkgs/curl/spkg-install
+++ b/build/pkgs/curl/spkg-install
@@ -1,6 +1,21 @@
 #!/usr/bin/env bash
 
+if [ -z "$SAGE_LOCAL" ] ; then
+    echo >&2 "Error - SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
+fi
 cd src
+
+# Patch sources.
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
 ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib"
 if [ $? -ne 0 ]; then
@@ -8,13 +23,13 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-$MAKE
+$MAKE V=1
 if [ $? -ne 0 ]; then
     echo >&2 "Error building curl."
     exit 1
 fi
 
-$MAKE install
+$MAKE install V=1
 if [ $? -ne 0 ]; then
     echo >&2 "Error installing curl."
     exit 1
