Update gd to version 2.1.0.
The Sage scripts have been cleaned up.
Our tarball is autoreconfed so that it supports Cygwin64.

diff --git a/build/pkgs/gd/spkg-install b/build/pkgs/gd/spkg-install
--- a/build/pkgs/gd/spkg-install
+++ b/build/pkgs/gd/spkg-install
@@ -1,18 +1,9 @@
 #!/usr/bin/env bash
 
-if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
+if [ -z "$SAGE_LOCAL" ]; then
+   echo >&2 "SAGE_LOCAL undefined ... exiting"
+   echo >&2 "Maybe run 'sage -sh'?"
    exit 1
-fi
-
-if [ $UNAME = "CYGWIN" ]; then
-    cp patches/expr "$SAGE_LOCAL/bin"
-fi
-
-if [ $UNAME = "Darwin" ]; then
-    # OSX does not have fontconfig, often causes problems with 3rd party distributions
-    LIBGD_CONFIGURE="--without-fontconfig $LIBGD_CONFIGURE"
 fi
 
 # Critical to get rid of old versions, since they will break the install, since
@@ -22,39 +13,48 @@ rm "$SAGE_LOCAL"/lib/libgd.*
 
 cd src
 
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
 # Needed to correctly pickup libiconv on FreeBSD
-if [ `uname` = "FreeBSD" ] ; then
-   LDFLAGS="-L/usr/local/lib"; export LDFLAGS
+if [ "$UNAME" = "FreeBSD" ] ; then
+   LDFLAGS="-L/usr/local/lib $LDFLAGS"
 fi
 
-# needed to pick up zlib.h
-if [ "x$SAGE64" = xyes ]; then
-   CFLAGS=" -m64 $CFLAGS -fPIC -g -I\"$SAGE_LOCAL/include\" -I$SAGE_LOCAL/include/freetype2/"
-   LDFLAGS="-m64 -L$SAGE_LOCAL/lib"; export LDFLAGS
+if [ "$SAGE64" = "yes" ]; then
+   CFLAGS=" -m64 -fPIC -g $CFLAGS"
+   LDFLAGS="-m64 $LDFLAGS"
 else
-   CFLAGS="$CFLAGS -fPIC -g -I\"$SAGE_LOCAL/include\" -I$SAGE_LOCAL/include/freetype2/"
+   CFLAGS="-fPIC -g $CFLAGS"
 fi
-export CFLAGS
 
-# We explicitly disable X support, since (1) X is not a SAGE dependency,
+export CFLAGS LDFLAGS
+
+# We explicitly disable X and fontconfig support, since (1) X is not a SAGE dependency,
 # and (2) the gd build fails on a lot of OS X PPC machines when X is enabled.
-./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" --without-jpeg --without-x --with-zlib="$SAGE_LOCAL" --with-freetype="$SAGE_LOCAL" --without-xpm $LIBGD_CONFIGURE
-
+./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
+  --without-jpeg --without-xpm --without-x --without-fontconfig \
+  --with-zlib="$SAGE_LOCAL" --with-freetype="$SAGE_LOCAL" \
+  $LIBGD_CONFIGURE
 if [ $? -ne 0 ]; then
-    echo "Error configuring gd."
+    echo >&2 "Error configuring gd."
     exit 1
 fi
 
 $MAKE
-
 if [ $? -ne 0 ]; then
-    echo "Error building gd."
+    echo >&2 "Error building gd."
     exit 1
 fi
 
 $MAKE install
-
 if [ $? -ne 0 ]; then
-    echo "Error installing gd."
+    echo >&2 "Error installing gd."
     exit 1
 fi
