build/pkgs/sagemath_objects/spkg-install: Build and store the wheel, use it for testing with tox

diff --git a/build/pkgs/sagemath_objects/spkg-install b/build/pkgs/sagemath_objects/spkg-install
--- a/build/pkgs/sagemath_objects/spkg-install
+++ b/build/pkgs/sagemath_objects/spkg-install
@@ -1,8 +1,27 @@
-#!/usr/bin/env bash
+#!/usr/bin/env bash -x
+# From sage-spkg.
+# For type=script packages, the build rule in build/make/Makefile sources
+# sage-env but not sage-dist-helpers.
+lib="$SAGE_ROOT/build/bin/sage-dist-helpers"
+source "$lib"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error: failed to source $lib"
+    echo >&2 "Is $SAGE_ROOT the correct SAGE_ROOT?"
+    exit 1
+fi
 cd src
 
+# First build the sdist, then build the wheel from the sdist.
+# https://pypa-build.readthedocs.io/en/latest/#python--m-build
+# (Important because sagemath-objects uses MANIFEST.in for filtering.)
+# Do not install the wheel.
+DIST_DIR="$(mktemp -d)"
+python3 -m build --outdir "$DIST_DIR"/dist .
+
+wheel=$(cd "$DIST_DIR" && sdh_store_wheel . && echo $wheel)
+
 if [ "$SAGE_CHECK" != no ]; then
-    tox
+    tox --installpkg $wheel
 fi
-# We skip the install for now.
+
 exit 0
