Added the ability for packages to have a post-install script called spkg-postinst.
It is run after all the package's files have been installed to SAGE_LOCAL, but before the stamp
file has been written.

diff --git a/build/bin/sage-spkg b/build/bin/sage-spkg
--- a/build/bin/sage-spkg
+++ b/build/bin/sage-spkg
@@ -714,7 +714,7 @@ __EOF__
 }
 
 
-for script in build install check; do
+for script in build install check postinst; do
     script="spkg-$script"
     if [ -f "$script" ]; then
         if [ "$USE_LOCAL_SCRIPTS" = "yes" ]; then
@@ -896,6 +896,18 @@ if [ -d "$SAGE_DESTDIR" ]; then
     # Remove the $SAGE_DESTDIR entirely once all files have been moved to their
     # final location.
     rm -rf "$SAGE_DESTDIR"
+fi
+
+# Run the post-install script, if any
+if [ -f spkg-postinst ]; then
+    time ./spkg-postinst
+    if [ $? -ne 0 ]; then
+        # TODO: It would be good if this also rolled back the failed
+        # installation.  This will have to be done once there is an uninstall
+        # script.
+        error_msg "Error running the postinst script for $PKG_BASE."
+        exit 1
+    fi
 fi
 
 if [ "$UNAME" = "CYGWIN" ]; then
