Implement SAGE_CHECK=warn, sage-spkg -w

diff --git a/build/bin/sage-spkg b/build/bin/sage-spkg
--- a/build/bin/sage-spkg
+++ b/build/bin/sage-spkg
@@ -11,6 +11,10 @@
 #       installing; instead simply overwrite existing files.
 #   -c: after installing, run the test suite for the spkg. This should
 #       override the settings of SAGE_CHECK and SAGE_CHECK_PACKAGES.
+#       Exit with an error if the test suite fails.
+#   -w: after installing, run the test suite for the spkg. This should
+#       override the settings of SAGE_CHECK and SAGE_CHECK_PACKAGES.
+#       Print a warning if the test suite fails.
 #   -d: only download the package
 #   -y: automatically reply "y" for all prompts regarding
 #       experimental and old-style packages
@@ -78,7 +82,10 @@ found, install it.
 
 Options:
    -s: do not delete the temporary build directory
-   -c: after installing, run the test suite for the package
+   -c: after installing, run the test suite for the package;
+       exit with an error on test suite failures
+   -w: after installing, run the test suite for the package;
+       print a warning on test suite failures
    -d: only download the package
    -y: automatically reply "y" for all prompts regarding
        experimental and old-style packages; warning: there
@@ -220,6 +227,9 @@ while true; do
         -c|--check)
             SAGE_CHECK_PACKAGES=x  # nonempty, so not set to default later
             export SAGE_CHECK=yes;;
+        -w|--check-warning-only)
+            SAGE_CHECK_PACKAGES=x  # nonempty, so not set to default later
+            export SAGE_CHECK=warn;;
         -k|--keep-existing)
             KEEP_EXISTING=yes;;
         -*)
@@ -1009,15 +1019,21 @@ fi
 # spkg-check scripts were written before use of DESTDIR installs, and so
 # fail in many cases.  This might be good to change later.
 
-if [ "$SAGE_CHECK" = "yes" ]; then
+if [ "$SAGE_CHECK" = "yes" -o "$SAGE_CHECK" = "warn" ]; then
     if [ -f spkg-check ]; then
         echo "Running the test suite for $PKG_NAME..."
         time ./spkg-check
         if [ $? -ne 0 ]; then
-            error_msg "Error testing package $PKG_NAME" "make check"
-            exit 1
+            TEST_SUITE_RESULT="failed"
+            if [ "$SAGE_CHECK" = "warn" ]; then
+                error_msg "Warning: Error testing package $PKG_NAME (ignored)" "make check"
+            else
+                error_msg "Error testing package $PKG_NAME" "make check"
+                exit 1
+            fi
+        else
+            TEST_SUITE_RESULT="passed"
         fi
-        TEST_SUITE_RESULT="passed"
     else
         echo "Package $PKG_NAME has no test suite."
         TEST_SUITE_RESULT="not available"
