build/bin/sage-logger: In V=0 mode, print tail of log on errors

diff --git a/build/bin/sage-logger b/build/bin/sage-logger
--- a/build/bin/sage-logger
+++ b/build/bin/sage-logger
@@ -77,7 +77,9 @@ if [ -n "$SAGE_SILENT_BUILD" -a ${use_prefix} = true ]; then
     ( exec>> $logfile 2>&1 ; eval "$cmd" )
     status=$?
     if [[ $status != 0 ]]; then
-        echo "  [$logname] error installing, exit status $status. Log file: $logfile"
+        echo "  [$logname] error installing, exit status $status. End of log file:"
+        tail -n 20 "$logfile" | sed "s;^;  [$logname]   ;" >&2
+        echo "  [$logname] Full log file: $logfile"
     else
         echo "  [$logname] successfully installed."
     fi
