As suggested, rename sdh_check_common_vars to sdh_guard
Add it to the standard script header. Not 100% sure if it would be better there, or
explicitly in every script file.  In the automatic header it's mostly redundant--if
sage-env succeeded then it's not very likely needed, unless sage-env itself is broken.

So it probably doesn't hurt to check as a last defense.

diff --git a/build/bin/sage-spkg b/build/bin/sage-spkg
--- a/build/bin/sage-spkg
+++ b/build/bin/sage-spkg
@@ -687,6 +687,12 @@ for lib in env dist-helpers; do
     fi
 done
 
+sdh_guard
+if [ \$? -ne 0 ]; then
+    echo >&2 "Error: sdh_guard not found; Sage environment was not set up properly"
+    exit 1
+fi
+
 cd "\$SAGE_PKG_DIR"
 if [ \$? -ne 0 ]; then
     echo >&2 "Error: could not cd to the package build directory \$SAGE_PKG_DIR"
