Deprecate old-style packages

diff --git a/build/bin/sage-spkg b/build/bin/sage-spkg
--- a/build/bin/sage-spkg
+++ b/build/bin/sage-spkg
@@ -274,7 +274,6 @@ elif [ -z "$PKG_HAS_PATH" ]; then
 
         # Warning for experimental packages
         if [ x`cat "$PKG_SCRIPTS/type"` = x"experimental" ]; then
-            echo # The following message appears twice in this file
             echo "=========================== WARNING ==========================="
             echo "You are about to download and install an experimental package."
             echo "This probably won't work at all for you! There is no guarantee"
@@ -373,23 +372,46 @@ if [ ! -f "$PKG_SRC" ]; then
                     else
                         # Warn and ask the user if downloading an
                         # experimental or archive package.
+                        # Add a deprecation note for other packages,
+                        # since old-style packages are deprecated.
                         if [ $repo = experimental ]; then
-                            echo # The following message appears twice in this file
-                            echo "=========================== WARNING ==========================="
-                            echo "You are about to download and install an experimental package."
-                            echo "This probably won't work at all for you! There is no guarantee"
-                            echo "that it will build correctly, or behave as expected."
-                            echo "Use at your own risk!"
-                            echo "==============================================================="
+                            echo "================================ WARNING ================================="
+                            echo "You are about to download and install an unmaintained experimental"
+                            echo "package. This probably won't work at all for you! There is no guarantee"
+                            echo "that it will build correctly, or behave as expected. Use at your own risk!"
+                            echo
+                            echo "This package will be removed in future versions of SageMath. If you care"
+                            echo "about this package, you should make a proper new-style package instead."
+                            echo "For more information about making Sage packages, see"
+                            echo "http://doc.sagemath.org/html/en/developer/packaging.html"
+                            echo "=========================================================================="
                             ask_download=yes
                         elif [ $repo = archive ]; then
-                            echo "=========================== WARNING ==========================="
-                            echo "You are about to download and install an archived package."
-                            echo "This means the package is likely to be outdated and it probably"
-                            echo "won't work at all for you! Use at your own risk!"
-                            echo "==============================================================="
+                            echo "================================ WARNING ================================="
+                            echo "You are about to download and install an unmaintained archived package."
+                            echo "This probably won't work at all for you! There is no guarantee that it"
+                            echo "will build correctly, or behave as expected. Use at your own risk!"
+                            echo
+                            echo "This package will be removed in future versions of SageMath. If you care"
+                            echo "about this package, you should make a proper new-style package instead."
+                            echo "For more information about making Sage packages, see"
+                            echo "http://doc.sagemath.org/html/en/developer/packaging.html"
+                            echo "=========================================================================="
                             ask_download=yes
                         else
+                            # Deprecated since Sage 6.9, Trac #19158
+                            echo "================================== NOTE =================================="
+                            echo "You are about to download and install an old-style package. While this"
+                            echo "might still work fine, old-style packages are unmaintained and deprecated."
+                            echo
+                            echo "This package will be removed in future versions of SageMath. If you care"
+                            echo "about this package, you should make a proper new-style package instead."
+                            echo "For more information about making Sage packages, see"
+                            echo "http://doc.sagemath.org/html/en/developer/packaging.html"
+                            echo "=========================================================================="
+                            echo
+                            echo "Continuing in 30 seconds, press CTRL-C to abort"
+                            sleep 30
                             ask_download=no
                         fi
 
@@ -406,7 +428,9 @@ if [ ! -f "$PKG_SRC" ]; then
             done
 
             if [ -z "$PKG_URL" ]; then
-                echo >&2 "Error: could not find a package matching $PKG_NAME on $MIRROR"
+                echo >&2 "Error: could not find a package matching $PKG_NAME"
+                echo >&2 "       Try 'sage --package list' to see the available packages"
+                echo >&2 "       $(sage-package apropos $PKG_NAME)"
                 exit 1
             fi
 
