Use the correct python in sage-pip-install

diff --git a/build/bin/sage-pip-install b/build/bin/sage-pip-install
--- a/build/bin/sage-pip-install
+++ b/build/bin/sage-pip-install
@@ -31,8 +31,18 @@ if [ "$1" != "." ]; then
     exit 1
 fi
 
+
+if [ "$SAGE_PYTHON3" = yes ]; then
+    PYTHON=python3
+    PIP=pip3
+else
+    PYTHON=python2
+    PIP=pip2
+fi
+
+
 # Find out the name of the package that we are installing
-name="$(python setup.py --name)"
+name="$($PYTHON setup.py --name)"
 
 if [ $? -ne 0 ]; then
     echo >&2 "Error: could not determine package name"
@@ -47,47 +57,35 @@ if [ $(echo "$name" | wc -l) -gt 1 ]; then
 fi
 
 
-install()
-{
-    # Pass pip2 or pip3 as argument
-    pip=$1
-    
-    # We should avoid running pip2/3 while uninstalling a package because that
-    # is prone to race conditions. Therefore, we use a lockfile while
-    # running pip. This is implemented in the Python script pip2/3-lock.
-    
-    # Keep uninstalling as long as it succeeds
-    while true; do
-        out=$($pip-lock uninstall --disable-pip-version-check -y "$name" 2>&1)
-        if [ $? -ne 0 ]; then
-            break
-        fi
-        echo "$out"
-    done
-    
-    # Not ideal, but this is the easiest way to check if the package
-    # was not installed to begin with (which pip2/3 treats as an error).
-    # If it wasn't, then we proceed quietly; if it was installed show the
-    # uninstallation output and error out.
-    if [[ "$out" != *"not installed" ]]; then
-        echo >&2 "$out"
-        exit 1
-    fi
-    
-    # Finally actually do the installation (the "SHARED" tells pip2/3-lock
-    # to apply a shared lock)
-    echo "Installing package $name using $pip"
-    
-    $pip-lock SHARED install $pip_install_flags .
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error: installing with $pip failed"
-        exit 3
-    fi
-}
+# We should avoid running pip2/3 while uninstalling a package because that
+# is prone to race conditions. Therefore, we use a lockfile while
+# running pip. This is implemented in the Python script pip2/3-lock.
 
-if [ "$SAGE_PYTHON3" = yes ]; then
-    install pip3
-else
-    install pip2
+# Keep uninstalling as long as it succeeds
+while true; do
+    out=$($PIP-lock uninstall --disable-pip-version-check -y "$name" 2>&1)
+    if [ $? -ne 0 ]; then
+        break
+    fi
+    echo "$out"
+done
+
+# Not ideal, but this is the easiest way to check if the package
+# was not installed to begin with (which pip2/3 treats as an error).
+# If it wasn't, then we proceed quietly; if it was installed show the
+# uninstallation output and error out.
+if [[ "$out" != *"not installed" ]]; then
+    echo >&2 "$out"
+    exit 1
+fi
+
+# Finally actually do the installation (the "SHARED" tells pip2/3-lock
+# to apply a shared lock)
+echo "Installing package $name using $PIP"
+
+$PIP-lock SHARED install $pip_install_flags .
+if [ $? -ne 0 ]; then
+    echo >&2 "Error: installing with $PIP failed"
+    exit 3
 fi
 
