Install both pip2 and pip3, otherwise your python2 + python3 isn't that useful.
Fix all py3 dependencies for sagelib

diff --git a/build/bin/sage-pip-install b/build/bin/sage-pip-install
--- a/build/bin/sage-pip-install
+++ b/build/bin/sage-pip-install
@@ -46,29 +46,48 @@ if [ $(echo "$name" | wc -l) -gt 1 ]; then
     echo >&2 "line as the package name: $name"
 fi
 
-# We should avoid running pip while uninstalling a package because that
-# is prone to race conditions. Therefore, we use a lockfile while
-# running pip. This is implemented in the Python script pip-lock.
 
-# Keep uninstalling as long as it succeeds
-while true; do
-    out=$(pip-lock uninstall --disable-pip-version-check -y "$name" 2>&1)
-    if [ $? -ne 0 ]; then
-        break
+install()
+{
+    # Pass pip2 or pip3 as argument
+    pip=$1
+    
+    # We should avoid running pip2/3 while uninstalling a package because that
+    # is prone to race conditions. Therefore, we use a lockfile while
+    # running pip. This is implemented in the Python script pip2/3-lock.
+    
+    # Keep uninstalling as long as it succeeds
+    while true; do
+        out=$($pip-lock uninstall --disable-pip-version-check -y "$name" 2>&1)
+        if [ $? -ne 0 ]; then
+            break
+        fi
+        echo "$out"
+    done
+    
+    # Not ideal, but this is the easiest way to check if the package
+    # was not installed to begin with (which pip2/3 treats as an error).
+    # If it wasn't, then we proceed quietly; if it was installed show the
+    # uninstallation output and error out.
+    if [[ "$out" != *"not installed" ]]; then
+        echo >&2 "$out"
+        exit 1
     fi
-    echo "$out"
-done
+    
+    # Finally actually do the installation (the "SHARED" tells pip2/3-lock
+    # to apply a shared lock)
+    echo "Installing package $name using $pip"
+    
+    $pip-lock SHARED install $pip_install_flags .
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error: installing with $pip failed"
+        exit 3
+    fi
+}
 
-# Not ideal, but this is the easiest way to check if the package
-# was not installed to begin with (which pip treats as an error).
-# If it wasn't, then we proceed quietly; if it was installed show the
-# uninstallation output and error out.
-if [[ "$out" != *"not installed" ]]; then
-    echo >&2 "$out"
-    exit 1
+if [ "$SAGE_PYTHON3" = yes ]; then
+    install pip3
+else
+    install pip2
 fi
 
-# Finally actually do the installation (the "SHARED" tells pip-lock
-# to apply a shared lock)
-echo "Installing package $name using pip"
-exec pip-lock SHARED install $pip_install_flags .
