Parse sage-spkg options in sage-spkg

diff --git a/build/bin/sage-spkg b/build/bin/sage-spkg
--- a/build/bin/sage-spkg
+++ b/build/bin/sage-spkg
@@ -175,38 +175,31 @@ if [ $# -eq 0 ]; then
    exit 0
 fi
 
-# Options have to come in a specific order,
-# this is ensured by spkg/bin/sage.
+# Parse options
 INFO=0
-if [ "$1" = '--info' ]; then
-    INFO=1
-    shift
-fi
-
 FORCE=0
-if [ "$1" = '-f' ]; then
-    FORCE=1
-    shift
-fi
-
 DOWNLOAD_ONLY=0
-if [ "$1" = '-d' ]; then
-    DOWNLOAD_ONLY=1
+while true; do
+    case "$1" in
+        --info)
+            INFO=1;;
+        -f)
+            FORCE=1;;
+        -d)
+            DOWNLOAD_ONLY=1;;
+        -s)
+            export SAGE_KEEP_BUILT_SPKGS=yes;;
+        -c|--check)
+            SAGE_CHECK_PACKAGES=x  # nonempty, so not set to '!python' later
+            export SAGE_CHECK=yes;;
+        -*)
+            echo >&2 "Error: unknown option '$1'"
+            exit 2;;
+        *) break;;
+    esac
     shift
-elif [ -n "$SAGE_INSTALL_FETCH_ONLY" ]; then
-    DOWNLOAD_ONLY=1
-fi
+done
 
-if [ "$1" = '-s' ]; then
-    export SAGE_KEEP_BUILT_SPKGS=yes
-    shift
-fi
-
-if [ "$1" = '-c' ]; then
-    export SAGE_CHECK=yes
-    SAGE_CHECK_PACKAGES=x  # nonempty, so not set to '!python' later
-    shift
-fi
 
 ##################################################################
 # Figure out the package filename, download it if needed.
