Pass write_script_wrapper the absolute path to the script it's writing
Use the absolute path to also cd into the directory that the script is meant to run from at the
beginning of the script so that it runs correctly.

diff --git a/build/bin/sage-spkg b/build/bin/sage-spkg
--- a/build/bin/sage-spkg
+++ b/build/bin/sage-spkg
@@ -652,12 +652,19 @@ cd ..
 
 write_script_wrapper() {
     local script="$1"
+    local pkgdir="$(dirname "$script")"
     local header="\
 #!/usr/bin/env bash
 
 source \"$SAGE_SRC/bin/sage-env\"
 if [ $? -ne 0 ]; then
     echo >&2 \"Error: failed to source sage-env; is $SAGE_ROOT the correct SAGE_ROOT?\"
+    exit 1
+fi
+
+cd \"$pkgdir\"
+if [ $? -ne 0 ]; then
+    echo >&2 \"Error: could not cd to the package build directory $pkgdir\"
     exit 1
 fi
 "
@@ -685,7 +692,7 @@ for script in build install check; do
             echo >&2 "in the build/pkgs directory."
         fi
 
-        write_script_wrapper "spkg-$script"
+        write_script_wrapper $(pwd)/"spkg-$script"
     fi
 done
 
