Singular 4.x (#17254):  Restore setting defaults for CFLAGS and CXXFLAGS in spkg-install, minor fixes.

diff --git a/build/pkgs/singular/spkg-install b/build/pkgs/singular/spkg-install
--- a/build/pkgs/singular/spkg-install
+++ b/build/pkgs/singular/spkg-install
@@ -8,8 +8,8 @@ SRC=`pwd`/src/latest
 SHARED=`pwd`/src/shared
 PATCHES=`pwd`/patches
 
-if [ "$SAGE_LOCAL" = "" ]; then
-    echo >&2 "SAGE_LOCAL undefined ... exiting";
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "Error: SAGE_LOCAL undefined -- exiting..."
     echo >&2 "Maybe run 'sage -sh'?"
     exit 1
 fi
@@ -37,16 +37,25 @@ if [ "x$SAGE_DEBUG" = "xyes" ]; then
     rm -rf "$SRC/omalloc"
     mv "$SRC/xalloc" "$SRC/omalloc"
 
-    CFLAGS="-O0 -g $CFLAGS"
-    CXXFLAGS="-O0 -g $CXXFLAGS"
+    CFLAGS="$CFLAGS -O0 -g"
+    CXXFLAGS="$CXXFLAGS -O0 -g"
+else
+    # Singular 4.x (mostly) does not longer set defaults for CFLAGS and CXXFLAGS
+
+    OPTIMIZATION_FLAGS="-O2"
+
+    CFLAGS="$OPTIMIZATION_FLAGS -g $CFLAGS"
+    CXXFLAGS="$OPTIMIZATION_FLAGS -g $CXXFLAGS"
 fi
+
+export CFLAGS CXXFLAGS
 
 if [ "x$SAGE64" = xyes ]; then
     echo "Building a 64-bit version of Singular"
-    CFLAGS="$CFLAGS -m64 "
+    CFLAGS="$CFLAGS -m64"
     CXXFLAGS="$CXXFLAGS -m64"
-    CPPFLAGS="$CPPFLAGS -m64"
-    LDFLAGS="$LDFLAGS -m64 "; export LDFLAGS
+    CPPFLAGS="$CPPFLAGS -m64"; export CPPFLAGS
+    LDFLAGS="$LDFLAGS -m64"; export LDFLAGS
     if [ "x`uname`" = xSunOS ] ; then
         export CC="$CC -m64"
         export CXX="$CXX -m64"
@@ -97,13 +106,13 @@ build_singular()
 {
     $MAKE
     if [ $? -ne 0 ]; then
-        echo >&2 "Error building Singular"
+        echo >&2 "Error building Singular."
         exit 1
     fi
 
     $MAKE install
     if [ $? -ne 0 ]; then
-        echo >&2 "Error installing Singular"
+        echo >&2 "Error installing Singular."
         exit 1
     fi
 
