Trac #10903: singular-3-1-3-3.p1 (Jeroen Demeyer, 10 October 2011)  * Trac #10903: Add a patch os_x_ppc.patch to fix building on OS X PPC.  * Make all patches apply at -p1 level and apply some patches for Cygwin    on all systems for consistency.  * Remove unused files in patches/: Singular.configure, Singular.configure.in,    Singular.configure.in.patch  * Exit when `patch` fails.  We do not print an error message, patch is    verbose enough by itself.

diff --git a/build/pkgs/singular/spkg-install b/build/pkgs/singular/spkg-install
--- a/build/pkgs/singular/spkg-install
+++ b/build/pkgs/singular/spkg-install
@@ -98,22 +98,23 @@ clean_headers()
 apply_patches()
 {
     pushd $SRC
-    # work-around patches
-    patch -p2 < ../patches/assert.h.diff
+
+    patches="assert.h.diff sing_win.cc.diff Minor.h.patch os_x_ppc.patch Singular.configure.patch"
 
     if [ "$UNAME" = "CYGWIN" ]; then
-        # Fine to make this patch on any system, because it is code that is only compiled on Windows.
-        patch -p2 < ../patches/sing_win.cc.diff
-        patch -p2 < ../patches/IntegerProgramming-Makefile.in.diff
-        patch -p1 < ../patches/Minor.h.patch
+        patches="$patches IntegerProgramming-Makefile.in.diff"
     fi
-
-    patch -p1 < ../patches/Singular.configure.patch
 
     if [ "x$SAGE_DEBUG" = "xyes" ]; then
-        patch -p1 < ../patches/kernel.Makefile.in.debug.patch
-        patch -p1 < ../patches/Singular.Makefile.in.debug.patch
+        patches="$patches kernel.Makefile.in.debug.patch Singular.Makefile.in.debug.patch"
     fi
+
+    for patch in $patches; do
+        if ! patch -p1 <../patches/$patch; then
+            echo >&2 "Error: patch $patch failed to apply."
+            exit 1
+        fi
+    done
 
     popd
 }
