trac 12712: fix spkg-install following the deletion of 'newest_version' script (trac #10492).

diff --git a/build/pkgs/database_gap/spkg-install b/build/pkgs/database_gap/spkg-install
--- a/build/pkgs/database_gap/spkg-install
+++ b/build/pkgs/database_gap/spkg-install
@@ -1,61 +1,72 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage --sh'?"
+    exit 1
+fi
 
 touch "$SAGE_LOCAL"/bin/gap_stamp
 
-HERE=`pwd`
+GAP=`echo 'Print(Concatenation("gap-", GAPInfo.Version));' | gap -q`
+if [ -z "$GAP" ]; then
+    echo >&2 "Error determining the version of GAP installed in Sage."
+    exit 1
+fi
+# GAP should now be set to installed gap version - eg, GAP=gap-4.4.12
 
-cd $SAGE_ROOT/spkg
-#${gapver:=$SAGE_ROOT/spkg/standard/newest_version gap}
-#GAP0=`$gapver`
-GAP0=`$SAGE_ROOT/spkg/standard/newest_version gap`
-GAP=`echo $GAP0 | cut -f 1,2,3 -d "."`
-# returns latest gap version - eg, GAP=gap-4.4.12
 echo "********************************************************************"
 echo "Installing optional GAP databases, which may not be open source."
-echo "Installing GAP $GAP packages to $HERE/... "
+echo "Installing GAP packages to $SAGE_LOCAL/lib/$GAP/..."
 echo "Please see SPKG.txt for license details."
 echo "********************************************************************"
 
-cd $HERE
 cd src/
 
 rm -rf "$SAGE_ROOT"/local/lib/$GAP/small
 mv small "$SAGE_ROOT"/local/lib/$GAP/
 
 if [ $? -ne 0 ]; then
-    echo "Error installing small group database."
+    echo >&2 "Error installing small group database."
     exit 1
 fi
-echo "installed small group database"
+echo "Installed small group database."
 
 rm -rf "$SAGE_ROOT"/local/lib/$GAP/prim
 
 mv prim "$SAGE_ROOT"/local/lib/$GAP/
 
 if [ $? -ne 0 ]; then
-    echo "Error installing prim database."
+    echo >&2 "Error installing prim database."
     exit 1
 fi
-echo "installed prim database"
+echo "Installed prim database."
 
 rm -rf "$SAGE_ROOT"/local/lib/$GAP/trans
 mv trans "$SAGE_ROOT"/local/lib/$GAP/
 
 if [ $? -ne 0 ]; then
-    echo "Error installing trans database."
+    echo >&2 "Error installing trans database."
     exit 1
 fi
 
-echo "installed trans database"
+echo "Installed trans database."
 
 rm -rf "$SAGE_ROOT"/local/lib/$GAP/pkg/tomlib
 mv pkg/tomlib "$SAGE_ROOT"/local/lib/$GAP/pkg/
 
 if [ $? -ne 0 ]; then
-    echo "Error installing tomlib database."
+    echo >&2 "Error installing tomlib database."
     exit 1
 fi
 
-echo "installed tomlib database"
+echo "Installed tomlib database."
 
-echo "gap_reset_workspace()" | sage
+sage -c "gap_reset_workspace()"
+
+# Test taken from Simon King's p-group cohomology spkg:
+SMALL_GROUPS=`echo "SmallGroup(13,1); quit;" | $SAGE_ROOT/sage -gap -b -T | grep "13"`
+if [ "$SMALL_GROUPS" = "" ]; then
+    echo >&2 "Error installing the database_gap spkg."
+    exit 1
+fi
