Trac #9906: use standard template for spkg-install

diff --git a/build/pkgs/rpy2/spkg-install b/build/pkgs/rpy2/spkg-install
--- a/build/pkgs/rpy2/spkg-install
+++ b/build/pkgs/rpy2/spkg-install
@@ -1,14 +1,28 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-cp patches/setup.py src/
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage --sh'?"
+    exit 1
+fi
 
 cd src
 
-RHOMES="$SAGE_LOCAL"/lib/R; export RHOMES
+# Apply patches.  See SPKG.txt for information about what each patch
+# does.
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
+export RHOMES="$SAGE_LOCAL"/lib/R
 
 python setup.py install
 
 if [ $? -ne 0 ]; then
-   echo "Error building RPY -- Python interface to R."
-   exit 1
+    echo >&2 "Error building RPY -- Python interface to R."
+    exit 1
 fi
