#10423 jinja2-2.5.5.p0: Upgrade to latest upstream, dependencies added, some clean-up.
=== 2.5.5 (Leif Leonhardy, December 3rd, 2010) ===
 * #10423: Upgrade to version 2.5.5, as Sphinx (1.0.4) requires a version >=2.2
   (cf. #10350).
 * Some clean-up, dependencies added.


== Dependencies ==

 * Python (>= 2.4)
 * setuptools (or distribute)
 * Pygments (according to 'spkg/standard/deps')
 * docutils (dito, as a note only)

diff --git a/build/pkgs/jinja2/spkg-install b/build/pkgs/jinja2/spkg-install
--- a/build/pkgs/jinja2/spkg-install
+++ b/build/pkgs/jinja2/spkg-install
@@ -1,27 +1,25 @@
 #!/usr/bin/env bash
 
-if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+if [ -z "$SAGE_LOCAL" ]; then
+    echo "Error: SAGE_LOCAL undefined - exiting ..."
+    echo "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
 success() {
     if [ $? -ne 0 ]; then
-        echo "Error building Jinja2: '$1'"
+        echo $1
         exit 1
     fi
 }
 
-set +e
+rm -rf "$SAGE_LOCAL"/lib/python/site-packages/Jinja2-*
+success 'Error deleting previous version(s) of Jinja2'
 
-rm -rf "$SAGE_LOCAL"/lib/python/site-packages/Jinja2-2.1.1*
-success 'Error deleting previous version'
+# Install new version:
 
-#Install new version
 cd src
 
 python setup.py install
 success 'Error installing Jinja2'
 
-set -e
