trac #17552: Introduced bliss patch and made the additional error checkings

diff --git a/build/pkgs/bliss/spkg-install b/build/pkgs/bliss/spkg-install
--- a/build/pkgs/bliss/spkg-install
+++ b/build/pkgs/bliss/spkg-install
@@ -6,11 +6,18 @@ if [ "$SAGE_LOCAL" = "" ]; then
    exit 1
 fi
 
-cd "src" &&
-$MAKE &&
-mv libbliss.a "$SAGE_LOCAL/lib"
-mv graph.hh "$SAGE_LOCAL/include"
-mv kqueue.hh "$SAGE_LOCAL/include"
+cd "src"
+
+for patch in patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
+$MAKE && mv libbliss.a "$SAGE_LOCAL/lib" && mv *.hh "$SAGE_LOCAL/include"
 
 if [ $? -ne 0 ]; then
     echo "An error occurred whilst building bliss"
