#12912: Support for Cygwin and further changes to build system

diff --git a/build/pkgs/coxeter3/spkg-check b/build/pkgs/coxeter3/spkg-check
--- a/build/pkgs/coxeter3/spkg-check
+++ b/build/pkgs/coxeter3/spkg-check
@@ -1,16 +1,15 @@
 #!/usr/bin/env bash
 
 if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
+   echo >&2 "SAGE_LOCAL undefined ... exiting";
+   echo >&2 "Maybe run 'sage -sh'?"
    exit 1
 fi
 
-coxeter < test.input > test.output
+cd src
 
-if ! diff test.output.expected test.output > /dev/null; then
-   echo "Error testing coxeter on test.input:"
-   diff test.output.expected test.output
+$MAKE check
+if [ $? -ne 0 ]; then
+   echo >&2 "Error running coxeter testsuite"
    exit 1
 fi
-rm test.output
diff --git a/build/pkgs/coxeter3/spkg-install b/build/pkgs/coxeter3/spkg-install
--- a/build/pkgs/coxeter3/spkg-install
+++ b/build/pkgs/coxeter3/spkg-install
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
+   echo >&2 "SAGE_LOCAL undefined ... exiting";
+   echo >&2 "Maybe run 'sage -sh'?"
    exit 1
 fi
 
@@ -15,18 +15,19 @@ sed -i "s|SAGE_LOCAL|$SAGE_LOCAL|g" directories.tmpl
 cd ../src
 cp ../patches/directories.tmpl directories.h
 cp ../patches/sage.cpp ../patches/sage.h .
-patch < ../patches/makefile.patch
+cp ../patches/test.input ../patches/test.output.expected .
+patch -p1 < ../patches/makefile.patch
 
 # Build
 $MAKE all
 if [ $? -ne 0 ]; then
-   echo "Error building coxeter3"
+   echo >&2 "Error building coxeter3"
    exit 1
 fi
 
 # Install
 $MAKE install
 if [ $? -ne 0 ]; then
-   echo "Error installing coxeter3"
+   echo >&2 "Error installing coxeter3"
    exit 1
 fi
