#12682 (ratpoints-2.1.3.p3): Fix "hardcoded" `gcc`, use `$MAKE`, some clean-up.
=== ratpoints-2.1.3.p3 (Leif Leonhardy, March 17th 2012) ===
 * #12682: Patch `Makefile` such that the `CC` (and `INSTALL_DIR`) environment
   variable(s) override(s) the setting in the Makefile.
 * Some clean-up; use `$MAKE` instead of `make`, also install the library
   with `make` (i.e., `$MAKE`) rather than "by hand".
 * TODO:
   - The Makefile has a `test` target; don't know whether we should
     run some tests, and whether it's worth an `spkg-check` script (for
     which we'd presumably have to duplicate the whole `CCFLAGS*` setup).

diff --git a/build/pkgs/ratpoints/spkg-install b/build/pkgs/ratpoints/spkg-install
--- a/build/pkgs/ratpoints/spkg-install
+++ b/build/pkgs/ratpoints/spkg-install
@@ -1,12 +1,11 @@
 #!/usr/bin/env bash
 
-if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+if [[ -z $SAGE_LOCAL ]]; then
+    echo >&2 "Error: SAGE_LOCAL undefined - exiting..."
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
-cd src
 
 PRIME_SIZE=7
 
@@ -14,11 +13,12 @@ CCFLAGS_NO_SSE="-I$SAGE_LOCAL/include -Wall -O2 -fPIC -DRATPOINTS_MAX_BITS_IN_PR
 CCFLAGS2="-L$SAGE_LOCAL/lib -lgmp -lm"
 CCFLAGS3="-L. -lratpoints"
 
-if [ `uname` = "Darwin" ]; then
+if [[ "$UNAME" = "Darwin" ]]; then
     CCFLAGS1="$CCFLAGS_NO_SSE"
-    echo "Building without SSE2 instructions (OS X)."
+    echo "Building without SSE2 instructions (MacOS X)."
 else
     CCFLAGS1="$CCFLAGS_NO_SSE -DUSE_SSE"
+    echo "Attempting to build ratpoints making use of SSE2 instructions."
 fi
 
 # Copy CFLAGS set externally to CCFLAGS.
@@ -26,13 +26,13 @@ fi
 CCFLAGS="`testcflags.sh -fnested-functions` $CFLAGS"
 
 # When CFLAG64 is not set, set it to the default -m64
-if [ -z $CFLAG64 ]; then
+if [[ -z $CFLAG64 ]]; then
     CFLAG64=-m64
 fi
 
-if [ "x$SAGE64" = xyes ]; then
-    echo "Building with extra 64-bit flags for OS X and Open Solaris"
-    CCFLAGS="$CFLAG64 $CCFLAGS"
+if [[ "$SAGE64" = yes ]]; then
+    echo "Building with extra 64-bit flags for MacOS X and Open Solaris."
+    CCFLAGS="$CCFLAGS $CFLAG64"
 fi
 
 export CCFLAGS1
@@ -41,24 +41,58 @@ export CCFLAGS3
 export CCFLAGS
 
 
-# PLEASE, don't break this again by deleting "libratpoints.a".  See trac 8267.
-make libratpoints.a
+cd src/
 
-if [ $? -ne 0 ]; then
-    if [ "$UNAME" != "Darwin" ]; then
-        echo "Build failed. Trying without SSE2 instructions."
-        CCFLAGS1="$CCFLAGS_NO_SSE"; export CCFLAGS1
-        make libratpoints.a
-    else
-        echo "Error building ratpoints"
+###########################
+# Apply patches (if any): #
+###########################
+
+echo "Applying patches to upstream source..."
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [[ $? -ne 0 ]]; then
+        echo >&2 "Error applying '$patch'."
         exit 1
     fi
-    if [ $? -ne 0 ]; then
-        echo "Error building ratpoints"
+done
+
+#############################
+# Build (just) the library: #
+#############################
+
+# PLEASE, don't break this again by deleting "libratpoints.a".  See trac 8267.
+$MAKE libratpoints.a
+
+if [[ $? -ne 0 ]]; then
+    if [[ "$UNAME" = "Darwin" ]]; then
+        echo >&2 "Error building ratpoints."
+        exit 1
+    fi
+    echo "Build failed. Trying without SSE2 instructions."
+    CCFLAGS1="$CCFLAGS_NO_SSE"
+    $MAKE libratpoints.a
+    if [[ $? -ne 0 ]]; then
+        echo >&2 "Error building ratpoints."
         exit 1
     fi
 fi
 
-cp libratpoints.a "$SAGE_LOCAL"/lib/
-cp ratpoints.h "$SAGE_LOCAL"/include/
+##############################################
+# Install (just) the library and its header: #
+##############################################
+
+# cp libratpoints.a "$SAGE_LOCAL"/lib/
+# cp ratpoints.h "$SAGE_LOCAL"/include/
+
+# The following requires that the Makefile got patched;
+# otherwise one could pass 'INSTALL_DIR=...' on the 'make'
+# command line:
+export INSTALL_DIR="$SAGE_LOCAL"
+$MAKE install-lib
+if [[ $? -ne 0 ]]; then
+    echo >&2 "Error installing ratpoints library."
+    exit 1
+fi
+
+# TODO: How about 'make test'? Do we need an spkg-check script?
 
