shortened patch

diff --git a/build/pkgs/sympy/spkg-install b/build/pkgs/sympy/spkg-install
--- a/build/pkgs/sympy/spkg-install
+++ b/build/pkgs/sympy/spkg-install
@@ -8,6 +8,20 @@ fi
 
 cd src/
 
+mv sympy/mpmath/tests/__init__.py tmp
+rm -rf sympy/mpmath
+mkdir -p sympy/mpmath/tests
+mv tmp sympy/mpmath/tests/__init__.py
+
+echo "Applying patches to upstream sources..."
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error: '$patch' failed to apply."
+        exit 1
+    fi
+done
+
 # sympy imports itself, and therefore it indirectly imports sage in
 # setup.py.  We need to set PYTHONPATH=. and use the -S option to avoid
 # importing the currently installed version of sympy, and to avoid
