add patch to preparse %prun, %timeit, and %time magics.  See https://github.com/ipython/ipython/pull/2403

diff --git a/build/pkgs/ipython/spkg-install b/build/pkgs/ipython/spkg-install
--- a/build/pkgs/ipython/spkg-install
+++ b/build/pkgs/ipython/spkg-install
@@ -8,6 +8,19 @@ fi
 
 cd src
 
+# Apply patches.  See SPKG.txt for information about what each patch
+# does.
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    else
+        echo "Successfully applied patch $patch"
+    fi
+done
+
 python setup.py build
 if [ $? -ne 0 ]; then
     echo >&2 "Error building IPython."
