#11460: reinstated the patch for src/IPython/rlineimpl.py.
Also, use 'patch' to install patches.

diff --git a/build/pkgs/ipython/spkg-install b/build/pkgs/ipython/spkg-install
--- a/build/pkgs/ipython/spkg-install
+++ b/build/pkgs/ipython/spkg-install
@@ -6,13 +6,34 @@ if [ "$SAGE_LOCAL" = "" ]; then
    exit 1
 fi
 
-rm -rf "$SAGE_LOCAL/lib/python/site-packages/IPython"
-
 cd src
 
-"$SAGE_ROOT"/local/bin/python setup.py install
+# Apply patches
+echo "Patching IPython..."
+for p in ../patches/*.patch; do
+    patch -p1 <"$p"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+echo
 
+python setup.py build
 if [ $? -ne 0 ]; then
-    echo "Error installing Ipython"
+    echo >&2 "Error building IPython."
+    exit 1
+fi
+
+echo "Removing old version of IPython..."
+rm -rf "$SAGE_LOCAL/lib/python/site-packages/IPython"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error deleting previous version"
+    exit 1
+fi
+
+python setup.py install
+if [ $? -ne 0 ]; then
+    echo >&2 "Error installing IPython"
     exit 1
 fi
