Pillow: re-resolve #9864

diff --git a/build/pkgs/Pillow/spkg-install b/build/pkgs/Pillow/spkg-install
--- a/build/pkgs/Pillow/spkg-install
+++ b/build/pkgs/Pillow/spkg-install
@@ -8,6 +8,15 @@ fi
 
 cd src
 
+# PATCH
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error: Patch \"$patch\" failed to apply."
+        exit 1
+    fi
+done
+
 python setup.py install
 
 if [ $? -ne 0 ]; then
