Trac #13123: Move extcode to SAGE_ROOT/devel/ext: reviewer patch

diff --git a/src/ext/spkg-dist b/src/ext/spkg-dist
--- a/src/ext/spkg-dist
+++ b/src/ext/spkg-dist
@@ -1,30 +1,33 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+set -e  # Automatically exit on errors
+
+
 if [ $# -ne 2 ]; then
-    echo "Usage: $0 <SAGE_VERSION> <SAGE_ROOT>"
-    echo "Build SAGE package in the extcode directory."
-    exit 0
+    echo >&2 "Usage: $0 <SAGE_VERSION> <SAGE_ROOT>"
+    echo >&2 "Build SAGE package in the extcode directory."
+    exit 2
 fi
 
-E=extcode
 SAGE_VERSION=$1
 SAGE_ROOT=$2
-DIR=$E-$SAGE_VERSION
+SAGE_EXTCODE=`pwd`
+DIR="extcode-$SAGE_VERSION"
 
-cd "$SAGE_ROOT/data/"
-if [ -d $DIR ]; then
-   rm -rf $DIR
-fi
-mkdir $DIR
+# Copy the extcode repo to ${SAGE_EXTCODE}/../extcode-${SAGE_VERSION}
+rm -rf ../$DIR
+mkdir ../$DIR
 
-cd $E
-cp -pr * .hg .hgignore .hgtags "../$DIR/"
-cd "../$DIR"
+cp -pR * .hg* ../$DIR
+
+# Delete some unneeded files
+cd ../$DIR
 rm -f *.spkg
 rm -f magma/*.dat magma/*.sig magma/*/*.dat magma/*/*.sig magma/*/*/*.dat magma/*/*/*.sig
-rm -rf octave/user/tmp
 rm -rf octave/user/*
 
+# Make the spkg and store it inside $SAGE_EXTCODE
 cd ..
-$SAGE_ROOT/sage -pkg $DIR
-rm -rf $DIR
-mv $DIR.spkg extcode
+"$SAGE_ROOT/sage" --pkg $DIR
+rm -r $DIR
+mv $DIR.spkg $SAGE_EXTCODE
diff --git a/src/ext/spkg-install b/src/ext/spkg-install
--- a/src/ext/spkg-install
+++ b/src/ext/spkg-install
@@ -1,8 +1,7 @@
-#!/bin/sh
-# This is the spkg-install script which will be emplaced within the SPKG for
-# the extcode repository whenever it is packaged.
+#!/usr/bin/env bash
 
-echo "Copying Extcode package to '$SAGE_ROOT/devel/ext-main'..."
+# This is the spkg-install script which will be emplaced within the SPKG for
+# the Extcode repository whenever it is packaged.
 
 if [ -d "$SAGE_ROOT/devel/ext-main" ]; then
     echo "Moving old Extcode package to '$SAGE_ROOT/devel/ext-main-old'..."
@@ -14,25 +13,27 @@ if [ -d "$SAGE_ROOT/devel/ext-main" ]; then
     fi
 fi
 
-rm -f "$SAGE_ROOT/devel/ext" # Delete just the link itself (if it exists)
+echo "Copying Extcode package to '$SAGE_ROOT/devel/ext-main'..."
 
 mkdir -p "$SAGE_ROOT/devel/ext-main"
-cp -pR * "$SAGE_ROOT/devel/ext-main/" # Creates new ext-main dir
+cp -pR * .hg* "$SAGE_ROOT/devel/ext-main/"
 if [ $? -ne 0 ]; then
-    echo >&2 "Error copying the new extcode package."
+    echo >&2 "Error copying the new Extcode package."
     exit 1
 fi
 
-cp -pR .hg* "$SAGE_ROOT/devel/ext-main/" || exit $?
 # Create an appropriate hgrc file for the target
 echo -e "[diff]\ngit = true" > "$SAGE_ROOT/devel/ext-main/.hg/hgrc"
 
-ln -s ext-main "$SAGE_ROOT/devel/ext" # Create new symbolic link (deleted above)
+# Create the symbolic link ext -> ext-main
+rm -f "$SAGE_ROOT/devel/ext"
+ln -s ext-main "$SAGE_ROOT/devel/ext"
 if [ $? -ne 0 ]; then
     echo >&2 "Error creating symbolic link to '$SAGE_ROOT/devel/ext-main'."
     exit 1
 fi
 
-rm -f "$SAGE_EXTCODE"
+# Create a symbolic link from SAGE_ROOT/local/share/sage/ext to SAGE_ROOT/devel/ext
 mkdir -p "$SAGE_SHARE/sage"
+rm -f "$SAGE_EXTCODE"
 ln -s ../../../devel/ext "$SAGE_EXTCODE"
