Trac #13123: move SAGE_DATA to SAGE_LOCAL/share

diff --git a/src/ext/spkg-install b/src/ext/spkg-install
--- a/src/ext/spkg-install
+++ b/src/ext/spkg-install
@@ -2,35 +2,37 @@
 # This is the spkg-install script which will be emplaced within the SPKG for
 # the extcode repository whenever it is packaged.
 
-CUR=`pwd`
-DIR="$SAGE_ROOT"/data/extcode
+echo "Copying Extcode package to '$SAGE_ROOT/devel/ext-main'..."
 
-#check() {
-#   if [ $? -ne 0 ]; then
-#      echo "Something went wrong merging in the extcode repo."
-#      echo "Stopping the build."
-#      echo "Please get your extcode repository in good shape and checked in,"
-#      echo "then retry the upgrade/package install."
-#   fi
-#}
-
-
-if [ ! -d "$DIR" ]; then
-   # Brand new install.
-   mkdir "$DIR"
-   cp -pR * .hg* "$DIR"/ || exit $?
-else
-   # Doing an upgrade, so merge changes.
-   cd "$DIR"
-   hg ci
-   hg pull "$CUR"
-   hg merge tip
-   hg ci -m "Check-in during upgrade of Sage."
-   hg update
+if [ -d "$SAGE_ROOT/devel/ext-main" ]; then
+    echo "Moving old Extcode package to '$SAGE_ROOT/devel/ext-main-old'..."
+    rm -rf "$SAGE_ROOT/devel/ext-main-old"
+    mv "$SAGE_ROOT/devel/ext-main" "$SAGE_ROOT/devel/ext-main-old"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error moving the old 'ext-main' branch."
+        exit 1
+    fi
 fi
 
+rm -f "$SAGE_ROOT/devel/ext" # Delete just the link itself (if it exists)
+
+mkdir -p "$SAGE_ROOT/devel/ext-main"
+cp -pR * "$SAGE_ROOT/devel/ext-main/" # Creates new ext-main dir
+if [ $? -ne 0 ]; then
+    echo >&2 "Error copying the new extcode package."
+    exit 1
+fi
+
+cp -pR .hg* "$SAGE_ROOT/devel/ext-main/" || exit $?
 # Create an appropriate hgrc file for the target
-cat > "$DIR/.hg/hgrc" <<"HEREDOC"
-[diff]
-git = true
-HEREDOC
+echo -e "[diff]\ngit = true" > "$SAGE_ROOT/devel/ext-main/.hg/hgrc"
+
+ln -s ext-main "$SAGE_ROOT/devel/ext" # Create new symbolic link (deleted above)
+if [ $? -ne 0 ]; then
+    echo >&2 "Error creating symbolic link to '$SAGE_ROOT/devel/ext-main'."
+    exit 1
+fi
+
+rm -f "$SAGE_EXTCODE"
+mkdir -p "$SAGE_SHARE/sage"
+ln -s ../../../devel/ext "$SAGE_EXTCODE"
