#10682: Reviewer patch, replaced tabs by spaces in spkg-install

diff --git a/build/pkgs/maxima/spkg-install b/build/pkgs/maxima/spkg-install
--- a/build/pkgs/maxima/spkg-install
+++ b/build/pkgs/maxima/spkg-install
@@ -8,10 +8,10 @@ fi
 
 check_error() {
     if [[ $? -ne 0 ]]; then
-	echo >&2 "***********************************************************"
-	echo >&2 "Error:" $@
-	echo >&2 "***********************************************************"
-	exit 1
+        echo >&2 "***********************************************************"
+        echo >&2 "Error:" $@
+        echo >&2 "***********************************************************"
+        exit 1
     fi
 }
 
