#12433 (zn_poly-0.9.p8): Work around GCC 4.7.0 bug on ia64; avoid ulong typedef clash; further improvements.
=== zn_poly-0.9.p8 (Leif Leonhardy, April 20th, 2012) ===
 * #12433: Further reviewer changes / additions.
 * Work around GCC 4.7.0 bug on ia64 (by almost completely disabling optimi-
   zation if the compiler is GCC 4.7.x, of course only on that platform); cf.
   #12751, #12765.
 * Add a patch to avoid conflicting definitions (i.e., redundant `typedefs`)
   of `ulong`, by changing `ulong` to a macro.
 * Don't hardcode the zn_poly version number in `spkg-install`; instead read
   it from the file `VERSION`, like the generated `makefile` does.
 * Remove some of the code previously just commented out, as well as some
   obsolete comments.
 * Document patches (and correct ticket reference in an old changelog entry).

diff --git a/build/pkgs/zn_poly/spkg-install b/build/pkgs/zn_poly/spkg-install
--- a/build/pkgs/zn_poly/spkg-install
+++ b/build/pkgs/zn_poly/spkg-install
@@ -16,6 +16,12 @@ fi
 # Set up environment variables:
 ###############################################################################
 
+zn_poly_version=`cat src/VERSION` # Only used in 'spkg-install'.
+if [ -z "$zn_poly_version" ]; then
+    echo >&2 "Error: Couldn't retrieve zn_poly's version from '`pwd`/src/VERSION'."
+    exit 1
+fi
+
 if [ "$SAGE64" = yes ]; then
     echo "Building a 64-bit version of zn_poly."
     if [ -z "$CFLAG64" ]; then
@@ -25,12 +31,6 @@ if [ "$SAGE64" = yes ]; then
     CPPFLAGS="$CPPFLAGS $CFLAG64"
     CXXFLAGS="$CXXFLAGS $CFLAG64"
     LDFLAGS="$LDFLAGS $CFLAG64"
-    # We now do this unconditionally below (actually by patching):
-    # cp -f patches/makemakefile.py src/makemakefile.py
-    # if [ $? -ne 0 ]; then
-    #     echo >&2 "Error copying over patched 'makemakefile.py'."
-    #     exit 1
-    # fi
 fi
 
 if [ "$SAGE_DEBUG" = yes ]; then
@@ -41,31 +41,52 @@ else
     CFLAGS="-O3 -g $CFLAGS -fPIC"
     CXXFLAGS="-O3 -g $CXXFLAGS -fPIC"
 fi
-# LDFLAGS="-L. $LDFLAGS" # Not needed. (-leif, 04/2012)
+
+# Work around a bug in GCC 4.7.0 which breaks the build on Itanium CPUs with
+# '-O3', '-O2' and '-O1' (cf. #12765, #12751, and the bug URL below.)
+if [ "`uname -m`" = ia64 ] && [ "`testcc.sh $CC`" = GCC ]; then
+    gcc_version=`$CC -dumpversion`
+    case "$gcc_version" in
+      4.7.*)
+        CFLAGS="$CFLAGS -O0 -finline-functions -fschedule-insns"
+        CXXFLAGS="$CXXFLAGS -O0 -finline-functions -fschedule-insns"
+        echo >&2 "Warning: Disabling almost all optimization due to a bug in (at least)"
+        echo >&2 "         GCC 4.7.0 on Itanium, which otherwise would break the build."
+        echo >&2 "         See http://gcc.gnu.org/bugzilla/show_bug.cgi?id=48496"
+        echo >&2 "         for current status and further details."
+        echo >&2 "         (And please report to e.g. sage-devel in case you feel this bug"
+        echo >&2 "          should already be fixed in GCC $gcc_version.)"
+    esac
+fi
 
 export CFLAGS CPPFLAGS CXXFLAGS LDFLAGS # Partially redundant, but safe.
 
-# (Actually the currently generated Makefile won't use any of them from the
+# (Actually the currently generated Makefile won't use any of the above from the
 # environment; instead we have to pass them with special options to 'configure',
 # which we do below.  Furthermore, CPPFLAGS and CXXFLAGS are only supported by
 # our patched 'makemakefile.py', which is called by 'configure'.)
+
+case "$UNAME" in
+    SunOS)
+      if ! (ld --version  2>&1 | grep GNU >/dev/null); then
+          # Assume it's the Sun linker; change '-soname' to '-h':
+          # The following is only supported by the Makefile generated by our
+          # patched 'makemakefile.py':
+          export SONAME_FLAG=-h
+      fi;;
+    *) unset SONAME_FLAG # Leave the Makefile default; for safety.
+esac
+
+unset SHARED_FLAG # Currently leave the Makefile default ('-shared'); for safety.
 
 ###############################################################################
 # Apply patches (if any):
 ###############################################################################
 
-# cp patches/mpn_mulmid-tune.c patches/mul-tune.c patches/mulmid-tune.c src/tune
-# if [ $? -ne 0 ]; then
-#     echo >&2 "Error copying over patched upstream source files."
-#     exit 1
-# fi
-
-# We now also always patch 'makemakefile.py' below, since the changes are
-# independent of the setting of SAGE64.
-
 cd src/
 
-echo "Applying patches (if any) to upstream sources..."
+ls ../patches/*.patch &>/dev/null &&
+echo "Applying patches to upstream sources..." &&
 for patch in ../patches/*.patch; do
     basename "$patch"
     patch -p1 <"$patch"
@@ -73,26 +94,8 @@ for patch in ../patches/*.patch; do
         echo >&2 "Error: '$patch' failed to apply."
         exit 1
     fi
-done
-
-case "$UNAME" in SunOS)
-    if ! (ld --version  2>&1 | grep GNU >/dev/null); then
-        # Assume it's the Sun linker; change '-soname' to '-h':
-        # echo "Patching 'makemakefile.py' for the Sun linker..."
-        # sed 's/-soname/-h/g' makemakefile.py > makemakefile.py.$$ &&
-        # mv -f makemakefile.py.$$ makemakefile.py
-        # if [ $? -ne 0 ]; then
-        #     echo >&2 "Error patching 'makemakefile.py' (with 'sed')."
-        #     exit 1
-        # fi
-        # The following is only supported by the Makefile generated by our
-        # patched 'makemakefile.py':
-        export SONAME_FLAG=-h
-    fi;;
-    *) unset SONAME_FLAG # Leave the Makefile default; for safety.
-esac
-
-unset SHARED_FLAG # Currently leave the Makefile default ('-shared'); for safety.
+done &&
+echo
 
 ###############################################################################
 # Configure, tune, build and test zn_poly:
@@ -113,12 +116,14 @@ if [ $? -ne 0 ] || [ ! -f makefile ]; then
 fi
 
 # Run the tuning program, only takes 1 minute or so:
+echo
 echo "Now building zn_poly's self-tuning program..."
-$MAKE tune # CC="$CC"
+$MAKE tune # CC="$CC" CXX="$CXX"
 if [ $? -ne 0 ] || [ ! -x tune/tune ]; then
     echo >&2 "Error building zn_poly's tuning program."
     exit 1
 fi
+echo
 echo "Now running zn_poly's self-tuning program..."
 tune/tune > src/tuning.c
 if [ $? -ne 0 ]; then
@@ -126,16 +131,18 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+echo
 echo "Now building zn_poly with its tuning parameters..."
-$MAKE # CC="$CC"
+$MAKE # CC="$CC" CXX="$CXX"
 if [ $? -ne 0 ]; then
     echo >&2 "Error building zn_poly."
     exit 1
 fi
 
 # Run the brief test suite:
+echo
 echo "Now building and running zn_poly's quick self-test..."
-$MAKE check # CC="$CC"
+$MAKE check # CC="$CC" CXX="$CXX"
 if [ $? -ne 0 ]; then
     echo >&2 "Error running zn_poly's quick test suite ('make check')."
     exit 1
@@ -151,17 +158,18 @@ fi
 # Build and manually install the shared library:
 ###############################################################################
 
+echo
 echo "Now building and installing zn_poly's shared library..."
 
 if [ "$UNAME" != Darwin ]; then
     # Linux, SunOS/Solaris, Cygwin etc.:
-    $MAKE libzn_poly.so # CC="$CC"
+    $MAKE libzn_poly.so # CC="$CC" CXX="$CXX"
     if [ $? -ne 0 ]; then
         echo >&2 "Error building zn_poly's shared library."
         exit 1
     fi
-    cp -f libzn_poly-0.9.so "$SAGE_LOCAL"/lib/ &&
-    (cd "$SAGE_LOCAL"/lib/ && ln -sf libzn_poly-0.9.so libzn_poly.so)
+    cp -f libzn_poly-"$zn_poly_version".so "$SAGE_LOCAL"/lib/ &&
+    (cd "$SAGE_LOCAL"/lib/ && ln -sf libzn_poly-"$zn_poly_version".so libzn_poly.so)
     if [ $? -ne 0 ]; then
         echo >&2 "Error installing zn_poly's shared library."
         exit 1
@@ -186,7 +194,7 @@ else
     #     target=libzn_poly.dylib
     # fi
     # $MAKE $target # CC="$CC"
-    $MAKE libzn_poly.dylib # CC="$CC"
+    $MAKE libzn_poly.dylib # CC="$CC" CXX="$CXX"
     if [ ! -f libzn_poly.dylib ]; then
         echo >&2 "Error building zn_poly's dylib (shared library)."
         exit 1
@@ -202,6 +210,7 @@ fi
 # Manually install the header files:
 ###############################################################################
 
+echo
 echo "Now installing zn_poly's header files..."
 
 mkdir -p "$SAGE_LOCAL"/include/zn_poly/ &&
