updated SPKG.txt and spkg-install for version 0.8

diff --git a/build/pkgs/zn_poly/spkg-install b/build/pkgs/zn_poly/spkg-install
--- a/build/pkgs/zn_poly/spkg-install
+++ b/build/pkgs/zn_poly/spkg-install
@@ -18,7 +18,20 @@ cd src
 ./configure --gmp-prefix="$SAGE_LOCAL/" --ntl-prefix="$SAGE_LOCAL/" \
             --prefix="$SAGE_LOCAL/" --cflags="-fPIC -O3"
 
-make tune    # optional, but only takes 20 seconds or so
+# optionally run tuning program, only takes 1 minute or so
+make tune
+./tune > tuning.c
+
+
+# optionally run test suite, takes perhaps 10 minutes
+# (shouldn't be run in real release)
+make test
+./test all
+if [ $? -ne 0 ]; then
+    echo "zn_poly test suite failed."
+    exit 1
+fi
+
 
 # UNIX
 if [ $UNAME != "Darwin" ]; then
