#8477: Avoid GNUmakefile problem with GNU make.  SPKG.txt cleanup.

diff --git a/build/pkgs/palp/spkg-install b/build/pkgs/palp/spkg-install
--- a/build/pkgs/palp/spkg-install
+++ b/build/pkgs/palp/spkg-install
@@ -1,5 +1,12 @@
 #!/bin/sh
 
+mv -f src/GNUmakefile src/Makefile
+
+if [ $? -ne 0 ]; then
+    echo "Error patching PALP."
+    exit 1
+fi
+
 cd src
 
 make
