Trac #12055: Upgrade to PALP 2.0

diff --git a/build/pkgs/palp/spkg-install b/build/pkgs/palp/spkg-install
--- a/build/pkgs/palp/spkg-install
+++ b/build/pkgs/palp/spkg-install
@@ -18,17 +18,31 @@ if [ $? -ne 0 ]; then
 fi
 
 cd src
+mv Global.h Global.h-template
 
-make
+for dim in 4 5 6 11; do
+    echo Building PALP optimized for $dim dimensions
 
-if [ $? -ne 0 ]; then
-    echo "Error building PALP."
-    exit 1
-fi
+    sed "s/^#define\s*POLY_Dmax.*/#define POLY_Dmax $dim/" Global.h-template > Global.h
 
-cp poly.x class.x cws.x nef.x "$SAGE_LOCAL/bin/"
+    make
+    if [ $? -ne 0 ]; then
+	echo "Error building PALP."
+	exit 1
+    fi
 
-if [ $? -ne 0 ]; then
-    echo "Error installing PALP."
-    exit 1
-fi
+    for file in poly class cws nef; do
+	install ${file}.x "$SAGE_LOCAL"/bin/${file}-${dim}d.x
+	if [ $? -ne 0 ]; then
+	    echo "Error installing PALP."
+	    exit 1
+	fi
+    done
+done
+
+# symlinks for the default dimension
+cd "$SAGE_LOCAL"/bin
+for file in poly class cws nef; do
+    ln -sf ${file}-6d.x ${file}.x
+done
+
