Trac 21086: check for errors in spkg-install

diff --git a/build/pkgs/database_kohel/spkg-install b/build/pkgs/database_kohel/spkg-install
--- a/build/pkgs/database_kohel/spkg-install
+++ b/build/pkgs/database_kohel/spkg-install
@@ -10,7 +10,24 @@ cd src
 
 TARGET="${SAGE_SHARE}/kohel/"
 rm -rf ${TARGET}
-mkdir ${TARGET}
-mv PolMod ${TARGET}
-mv PolHeeg ${TARGET}
 
+mkdir ${TARGET}
+if [ $? -ne 0 ]
+then
+    echo "Error creating repertory ${TARGET}"
+    exit 1
+fi
+
+mv PolMod ${TARGET}
+if [ $? -ne 0 ]
+then
+    echo "Error moving PolMod to ${TARGET}"
+    exit 1
+fi
+
+mv PolHeeg ${TARGET}
+if [ $? -ne 0 ]
+then
+    echo "Error moving PolHeeg to ${TARGET}"
+    exit 1
+fi
