#11886: get scipy to build on OS X 10.7 Lion, using the patches from https://github.com/scipy/scipy/commit/effa6f68f8ada57b79864852b609ff06d2527306

diff --git a/build/pkgs/scipy/spkg-install b/build/pkgs/scipy/spkg-install
--- a/build/pkgs/scipy/spkg-install
+++ b/build/pkgs/scipy/spkg-install
@@ -36,6 +36,14 @@ rm -rf "$SAGE_LOCAL"/lib/python/site-packages/scipy
 
 cd src/
 
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
 if [ $? -ne 0 ]; then
     echo "Error patching setup.py"
     exit 1
