#11886 (scipy-0.9.p1): Reviewer changes (mostly cosmetic).

diff --git a/build/pkgs/scipy/spkg-install b/build/pkgs/scipy/spkg-install
--- a/build/pkgs/scipy/spkg-install
+++ b/build/pkgs/scipy/spkg-install
@@ -1,10 +1,18 @@
 #!/usr/bin/env bash
-# These flags confuse numpy's distutils.   In particular,
+
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "Error: SAGE_LOCAL undefined - exiting..."
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
+fi
+
+# These flags confuse numpy's distutils.  In particular,
 # if they are set empty bad things happen.
-
 unset CFLAGS CXXFLAGS SHAREDFLAGS
+echo "Note: CFLAGS, CXXFLAGS and SHAREDFLAGS are taken from distutils,"
+echo "      so their current settings are ignored."
 
-if [ `uname` = "Darwin" ]; then
+if [ "$UNAME" = "Darwin" ]; then
     unset ATLAS
     unset BLAS
     unset LAPACK
@@ -23,43 +31,38 @@ export F77="$SAGE_LOCAL/bin/sage_fortran"
 export F90="$SAGE_LOCAL/bin/sage_fortran"
 export F95="$SAGE_LOCAL/bin/sage_fortran"
 
-
-# This avoid problems on some systems -- until we officially
-# support umfpack (which we will likely do, since cvxopt
-# I think includes it).
-#   http://projects.scipy.org/pipermail/scipy-user/2006-July/008661.html
-# (Currently swig gets invoked by scipy when building the umfpack interace,
+# This avoids problems on some systems -- until we officially
+# support umfpack (which we will likely do, since cvxopt I think includes it):
+UMFPACK="None"; export UMFPACK
+# See http://projects.scipy.org/pipermail/scipy-user/2006-July/008661.html
+# (Currently SWIG gets invoked by scipy when building the umfpack interface,
 # which is bad.)
 
-UMFPACK="None"; export UMFPACK
+
+# Remove previous installation (if any):
 rm -rf "$SAGE_LOCAL"/lib/python/site-packages/scipy
 
 cd src/
 
+# Apply patches (if any):
 for patch in ../patches/*.patch; do
     patch -p1 <"$patch"
     if [ $? -ne 0 ]; then
-        echo >&2 "Error applying '$patch'"
+        echo >&2 "Error applying '$patch'."
         exit 1
     fi
 done
 
-if [ $? -ne 0 ]; then
-    echo "Error patching setup.py"
-    exit 1
-fi
-
-# Build
+# Build:
 python setup.py build
 if [ $? -ne 0 ]; then
-    echo "Error building scipy."
+    echo >&2 "Error building scipy."
     exit 1
 fi
 
-# Intall
+# Install:
 python setup.py install
 if [ $? -ne 0 ]; then
-    echo "Error installing scipy."
+    echo >&2 "Error installing scipy."
     exit 1
 fi
-
