trac 13541: update scipy to version 0.11.0

diff --git a/build/pkgs/scipy/spkg-install b/build/pkgs/scipy/spkg-install
--- a/build/pkgs/scipy/spkg-install
+++ b/build/pkgs/scipy/spkg-install
@@ -45,13 +45,13 @@ rm -rf "$SAGE_LOCAL"/lib/python/site-packages/scipy
 cd src/
 
 # Apply patches (if any):
-for patch in ../patches/*.patch; do
-    patch -p1 <"$patch"
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error applying '$patch'."
-        exit 1
-    fi
-done
+# for patch in ../patches/*.patch; do
+#     patch -p1 <"$patch"
+#     if [ $? -ne 0 ]; then
+#         echo >&2 "Error applying '$patch'."
+#         exit 1
+#     fi
+# done
 
 # Build:
 python setup.py build
