#12171: Update to MPFI 1.5.1. Remove old patch for Cygwin which is not needed anymore. Forget src/configure.ac which is now the vanilla one.

diff --git a/build/pkgs/mpfi/spkg-install b/build/pkgs/mpfi/spkg-install
--- a/build/pkgs/mpfi/spkg-install
+++ b/build/pkgs/mpfi/spkg-install
@@ -17,19 +17,17 @@ fi
 
 cd src
 
-./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" --with-mpfr-dir="$SAGE_LOCAL" --with-gmp-dir="$SAGE_LOCAL"
+./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" --with-mpfr="$SAGE_LOCAL" --with-gmp="$SAGE_LOCAL"
 
 if [ $? -ne 0 ]; then
-    echo "Error configuring mpfi"
+    echo "Error configuring MPFI"
     exit 1
 fi
 
-echo "Building and installint mpfi"
+echo "Building and installing MPFI"
 $MAKE install
 
-if [ $? -eq 0 -a -f $SAGE_LOCAL/include/mpfi.h ]; then
-    exit 0
-else
-    echo "An error occurred while building mpfi."
+if ! [ $? -eq 0 -a -f $SAGE_LOCAL/include/mpfi.h ]; then
+    echo "An error occurred while building MPFI."
     exit 1
 fi
