Trac #13290: minor corrections

diff --git a/build/pkgs/mpc/spkg-check b/build/pkgs/mpc/spkg-check
--- a/build/pkgs/mpc/spkg-check
+++ b/build/pkgs/mpc/spkg-check
@@ -6,4 +6,10 @@ if [ "$SAGE_LOCAL" = "" ]; then
     exit 1
 fi
 
-cd src && $MAKE check
+cd src
+
+$MAKE check
+if [ $? -ne 0 ]; then
+    echo >&2 "Error checking MPC."
+    exit 1
+fi
diff --git a/build/pkgs/mpc/spkg-install b/build/pkgs/mpc/spkg-install
--- a/build/pkgs/mpc/spkg-install
+++ b/build/pkgs/mpc/spkg-install
@@ -9,14 +9,15 @@ fi
 cd src
 
 # Apply patches.  See SPKG.txt for information about what each patch
-# does.  Currently, there are no patches.
-#for patch in ../patches/*.patch; do
-#    patch -p1 <"$patch"
-#    if [ $? -ne 0 ]; then
-#        echo >&2 "Error applying '$patch'"
-#        exit 1
-#    fi
-#done
+# does.
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
 
 # Unset CC and CFLAGS.  This will make mpc use the same configuration
