Trac #12515: add no_fortify_source.patch to remove -D_FORTIFY_SOURCE=2 flag.

diff --git a/build/pkgs/mpc/spkg-install b/build/pkgs/mpc/spkg-install
--- a/build/pkgs/mpc/spkg-install
+++ b/build/pkgs/mpc/spkg-install
@@ -11,6 +11,17 @@ unset RM
 
 cd src
 
+# Apply patches.  See SPKG.txt for information about what each patch
+# does.
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
+
 # Unset CC and CFLAGS.  This will make mpc use the same configuration
 # as MPIR, which is probably a good thing.
 unset CC
