Put some extra checks in spkg-check

diff --git a/build/pkgs/mpc/spkg-check b/build/pkgs/mpc/spkg-check
--- a/build/pkgs/mpc/spkg-check
+++ b/build/pkgs/mpc/spkg-check
@@ -1,7 +1,18 @@
 #!/usr/bin/env bash
 
+if [ "$SAGE_LOCAL" = "" ]; then
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
+fi
+
 # Unset RM because it messes with libtool
 unset RM
 
 cd src
+
 $MAKE check
+if [ $? -ne 0 ]; then
+    echo >&2 "Error checking MPC."
+    exit 1
+fi
