#10719 (symmetrica-2.0.p7) Reviewer changes: More error checking, use LDFLAGS, clean up.
=== symmetrica-2.0.p7 (Leif Leonhardy, October 6th 2011) ===
 #10719 (Fix linker errors on OpenSUSE 11.2 and Ubuntu 11.10):
 Additional reviewer changes:
  * Add more error checks, normalize error messages.
  * Set up flags in spkg-check as well, as we build the test
    program there. Also use $MAKE there. Put CFLAG64 into
    LDFLAGS if appropriate (i.e. SAGE64=yes).
  * Clean up our Makefile, also use LDFLAGS when linking the test program.
  * Add GNU patch to the dependencies.

diff --git a/build/pkgs/symmetrica/spkg-check b/build/pkgs/symmetrica/spkg-check
--- a/build/pkgs/symmetrica/spkg-check
+++ b/build/pkgs/symmetrica/spkg-check
@@ -1,7 +1,31 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+if [ -z "$SAGE_LOCAL" ] ; then
+    echo >&2 "Error: SAGE_LOCAL undefined - exiting..."
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
+fi
+
+if [ -z "$CFLAG64" ] ; then
+    CFLAG64=-m64
+fi
+
+if [ "x$SAGE64" = xyes ] ; then
+    CFLAGS="$CFLAGS $CFLAG64"
+    LDFLAGS="$LDFLAGS $CFLAG64" # Could use an LDFLAG64 here.
+fi
+
+CFLAGS="-O2 -g $CFLAGS -fPIC -DFAST -DALLTRUE"
+export CFLAGS LDFLAGS # Currently redundant, but safe.
+
 
 cd src
-make test
+
+$MAKE test # Just *builds* an example / test program.
+if [ $? -ne 0 ]; then
+    echo >&2 "Error building Symmetrica's test program."
+    exit 1
+fi
 
 echo 123 | ./test > spkg-check.actual
 
@@ -12,7 +36,8 @@ cat <<EOF > spkg-check.expected
  960000.000000.000000.000000.000000
 EOF
 
-diff spkg-check.actual spkg-check.expected && exit 0
-
-echo "The symmetrica check failed, exitting".
-exit 1
+if ! diff spkg-check.actual spkg-check.expected; then
+    echo >&2 "Error: The Symmetrica check failed."
+    exit 1
+fi
+echo "The Symmetrica check passed."
