Temporary roll back changes between 6.9.beta2 and 6.9.beta8

diff --git a/build/make/install b/build/make/install
--- a/build/make/install
+++ b/build/make/install
@@ -153,10 +153,8 @@ else
     else
         # $CXX points to some version of GCC, find out which version.
         GCCVERSION=`$CXX -dumpversion`
-        # Add the .0 because Debian/Ubuntu gives version numbers like
-        # 4.6 instead of 4.6.4 (Trac #18885)
-        case "$GCCVERSION.0" in
-            [0-3].*|4.[0-3].*)
+        case $GCCVERSION in
+            [0-3].*|4.[0-3]|4.[0-3].*)
                 # Install our own GCC if the system-provided one is older than gcc-4.4.
                 # * gcc-4.2.4 compiles a slow IML:
                 # https://groups.google.com/forum/?fromgroups#!topic/sage-devel/Ux3t0dW2FSI
@@ -278,7 +276,9 @@ newest_version() {
         echo -n $PKG-
         cat "$SAGE_ROOT/build/pkgs/$PKG/package-version.txt"
     else
+        echo >&2 "Cannot determine latest version of $PKG."
         echo "$PKG"
+        return 1
     fi
 }
 
@@ -300,7 +300,6 @@ newest_version() {
 filtered_packages_list() {
     # for each package in pkgs/
     for DIR in $SAGE_ROOT/build/pkgs/*; do
-        test -d "$DIR" || continue
 
         PKG_TYPE_FILE="$DIR/type"
         if [ -f "$PKG_TYPE_FILE" ]; then
@@ -312,12 +311,8 @@ filtered_packages_list() {
         fi
 
         # Check consistency of 'DIR/type' file
-        if [ "$PKG_TYPE" != "base" ] && \
-           [ "$PKG_TYPE" != "standard" ] && \
-           [ "$PKG_TYPE" != "optional" ] && \
-           [ "$PKG_TYPE" != "experimental" ] && \
-           [ "$PKG_TYPE" != "pip" ]; then
-            echo >&2 "The content of \"$PKG_TYPE_FILE\" must be 'base', 'standard', 'optional', 'experimental' or 'pip'"
+        if [ "$PKG_TYPE" != "base" ] && [ "$PKG_TYPE" != "standard" ] && [ "$PKG_TYPE" != "optional" ] && [ "$PKG_TYPE" != "experimental" ]; then
+            echo >&2 "The content of \"$PKG_TYPE_FILE\" must be 'base', 'standard', 'optional' or 'experimental'"
             return 1
         fi
 
@@ -337,10 +332,8 @@ filtered_packages_list none || exit $?
 echo >&5 "# All Sage packages"
 
 filtered_packages_list all | while read PKG_NAME PKG_VERSION PKG_VAR; do
-    if [ "$PKG_NAME" != "$PKG_VERSION" ]; then
-        echo >&5 "$PKG_VAR = $PKG_VERSION"
-        echo "$PKG_VAR=$PKG_VERSION"
-    fi
+    echo >&5 "$PKG_VAR = $PKG_VERSION"
+    echo "$PKG_VAR=$PKG_VERSION"
 done
 
 cat >&5 <<EOF
@@ -442,42 +435,23 @@ EOF
 # Add a Makefile target corresponding to a given package
 filtered_packages_list all | while read PKG_NAME PKG_VERSION PKG_VAR; do
     DEP_FILE="$SAGE_ROOT/build/pkgs/$PKG_NAME/dependencies"
-    TYPE=`cat "$SAGE_ROOT/build/pkgs/$PKG_NAME/type"`
+    TYPE_FILE="$SAGE_ROOT/build/pkgs/$PKG_NAME/type"
     if [ -f "$DEP_FILE" ]; then
         DEPS=" $(head -n 1 $DEP_FILE)"
-    elif [ "$TYPE" = optional ]; then
+    elif [ x`cat "$TYPE_FILE"` = xoptional ]; then
         DEPS=' | $(STANDARD_PACKAGES)' # default for optional packages
-    elif [ "$TYPE" = pip ]; then
-        DEPS=' | $(INST)/$(PIP)'
     else
         DEPS=""
     fi
+    echo >&5 "\$(INST)/$PKG_VERSION:$DEPS"
+    echo >&5 "	+sage-logger '\$(SAGE_SPKG) \$($PKG_VAR)' '\$(SAGE_LOGS)/\$($PKG_VAR).log'"
+    echo >&5
 
-    if [ "$TYPE" = pip ]; then
-        # Special rules using PIP
-        echo >&5 "$PKG_NAME:$DEPS"
-        echo >&5 "	sage-logger 'sage --pip install $PKG_NAME' \$(SAGE_LOGS)/$PKG_NAME.log"
-        echo >&5
-
-        # Add a target to remove the "installed" file for "sage -f"
-        echo >&5 "$PKG_NAME-clean:"
-        echo >&5 "	-sage --pip uninstall -y $PKG_NAME"
-        echo >&5
-    else
-        # Normal Sage packages
-        echo >&5 "\$(INST)/$PKG_VERSION:$DEPS"
-        echo >&5 "	+sage-logger '\$(SAGE_SPKG) \$($PKG_VAR)' '\$(SAGE_LOGS)/\$($PKG_VAR).log'"
-        echo >&5
-
-        # Add a target with just the bare package name for "sage -i"
-        echo >&5 "$PKG_NAME: \$(INST)/\$($PKG_VAR)"
-        echo >&5
-
-        # Add a target to remove the "installed" file for "sage -f"
-        echo >&5 "$PKG_NAME-clean:"
-        echo >&5 "	rm -f \$(INST)/\$($PKG_VAR)"
-        echo >&5
-    fi
+    # Add a target with just the bare package name such that
+    # "make ccache" for example builds the ccache package with
+    # dependency checking.
+    echo >&5 "$PKG_NAME: \$(INST)/\$($PKG_VAR)"
+    echo >&5
 done
 
 # Close the Makefile
