Fix patch loop

diff --git a/build/pkgs/rubiks/spkg-install b/build/pkgs/rubiks/spkg-install
--- a/build/pkgs/rubiks/spkg-install
+++ b/build/pkgs/rubiks/spkg-install
@@ -120,17 +120,6 @@ export LDFLAGS
 export ABI
 export CPPFLAGS
 
-for patch in ../patches/*.patch; do
-    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
-    echo "Applying $patch"
-    patch -p1 <"$patch"
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error applying '$patch'"
-        exit 1
-    fi
-done
-
-
 # End of pretty general spkg-install file.
 # Now do the specific things needed for this package (rubiks)
 
@@ -141,12 +130,21 @@ else
 fi
 
 
-
 # remove the old dik binary since the has a name collision
 # with polynmake - see #2595
 rm -f $SAGE_LOCAL/bin/cube
 
 cd src
+
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    echo "Applying $patch"
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
 echo "Building Rubiks cube solvers"
 $MAKE install PREFIX="$SAGE_LOCAL"
