Still v1.1: Relocation of the public cohomology data base to SAGE_DATA. Fixing some typos in the documentation. More efficient test for the database_gap being installed. Build process is cleaned up - we are no longer building libmtx.a twice in different optimizations, since -O1 is fastest anyway.

diff --git a/build/pkgs/p_group_cohomology/spkg-install b/build/pkgs/p_group_cohomology/spkg-install
--- a/build/pkgs/p_group_cohomology/spkg-install
+++ b/build/pkgs/p_group_cohomology/spkg-install
@@ -4,7 +4,7 @@
 #
 #    Install script
 #
-#    Copyright (C) 2009 Simon A. King <simon.king@nuigalway.ie>
+#    Copyright (C) 2009 Simon A. King <simon.king@uni-jena.de>
 #
 #  Distributed under the terms of the GNU General Public License (GPL),
 #  version 2 or later (at your choice)
@@ -27,8 +27,11 @@ fi
 
 SMALL_GROUPS=`cd $SAGE_ROOT/spkg/optional/; $SAGE_ROOT/spkg/standard/newest_version database_gap`
 if [ "$SMALL_GROUPS" = "" ]; then
-    echo "Failed to find SmallGroups library.  Please install the database_gap spkg"
-    exit 1
+    SMALL_GROUPS=`cd $SAGE_ROOT/spkg/installed/; $SAGE_ROOT/spkg/standard/newest_version database_gap`
+    if [ "$SMALL_GROUPS" = "" ]; then
+        echo "Failed to find SmallGroups library.  Please install the database_gap spkg"
+        exit 1
+    fi
 fi
 
 cd src
