build git without i18n if gettext is not available

diff --git a/build/pkgs/git/spkg-install b/build/pkgs/git/spkg-install
--- a/build/pkgs/git/spkg-install
+++ b/build/pkgs/git/spkg-install
@@ -48,17 +48,34 @@ $MAKE GIT-VERSION-FILE
 # Configure without Tcl/Tk (otherwise git *requires* Tcl/Tk).
 # We keep SANE_TOOL_PATH empty, otherwise git messes with the PATH on
 # some systems, leading for example to a different "make" being used.
+echo "Configuring git..."
 ./configure --prefix="$SAGE_LOCAL" \
             --with-python="$SAGE_LOCAL"/bin/python \
             --without-tcltk \
-            --with-sane-tool-path= \
-            || die 'Error configuring git.'
-
-if [ "$SAGE_CHECK" = yes ]; then
-    $MAKE test || die "Error running git's combined build/test suite."
-else
-    $MAKE || die 'Error building git.'
+            --with-sane-tool-path=
+if [ $? -ne 0 ]; then
+    echo >&2 "Error configuring git."
+    exit 1
 fi
 
-# Force path to "install" program
-$MAKE INSTALL="$INSTALL" install || die 'Error installing git.'
+
+echo "Building git..."
+$MAKE
+if [ $? -ne 0 ]; then
+    echo "Retrying build without gettext (i18n will not be available)."
+    $MAKE NO_GETTEXT=1
+    if [ $? -ne 0 ]; then
+	echo >&2 "Error building git."
+	exit 1
+    fi
+fi
+
+
+echo "Installing git..."
+$MAKE INSTALL="$INSTALL" install
+if [ $? -ne 0 ]; then
+    echo >&2 'Error installing git.'
+    exit 1
+fi
+
+
