Clean up spkg-install

diff --git a/build/pkgs/git/spkg-install b/build/pkgs/git/spkg-install
--- a/build/pkgs/git/spkg-install
+++ b/build/pkgs/git/spkg-install
@@ -1,15 +1,13 @@
+#!/usr/bin/env sh
+
+die () {
+    echo $@ 1>&2
+    exit 1
+}
+
+[ -n "$SAGE_LOCAL" ] || die 'Error: $SAGE_LOCAL not set. Source sage-env or run this script from `sage -sh`.'
+
 cd src
-
-./configure --prefix="$SAGE_LOCAL"
-
-if [ $? -ne 0 ]; then
-    echo "Error configuring."
-    exit 1
-fi
-
-$MAKE install
-
-if [ $? -ne 0 ]; then
-    echo "Error building and installing."
-    exit 1
-fi
+./configure --prefix="$SAGE_LOCAL" || die 'Error configuring git.'
+$MAKE || die 'Error building git.'
+$MAKE install || die 'Error installing git.'
