#9603 Clean up spkg-install and spkg-check in the light of reviewer comments.

diff --git a/build/pkgs/iconv/spkg-check b/build/pkgs/iconv/spkg-check
--- a/build/pkgs/iconv/spkg-check
+++ b/build/pkgs/iconv/spkg-check
@@ -5,30 +5,35 @@ if [ -z "$SAGE_LOCAL" ]; then
     exit 1
 fi
 
-# Only test iconv on Solaris, HP-UX and Cygwin
-if [ "x$UNAME" != xSunOS ] && [ "x$UNAME" != xCYGWIN ] && [ "x$UNAME" != xHP-UX ]; then
-  echo "'make check' for iconv will not be run, since iconv is"
-  echo "only installed on HP-UX, Solaris and Cygwin - see:"
-  echo "http://trac.sagemath.org/sage_trac/ticket/8567"
-  exit 0
+# Only test iconv on Solaris, HP-UX and Cygwin, at that is
+# the only platforms on which iconv is installed. On
+# other platforms Sage uses the system iconv.
+
+if [ "x$UNAME" = xSunOS ] || [ "x$UNAME" = xCYGWIN ] || [ "x$UNAME" = xHP-UX ]; then
+   # We must test iconv, but on Solaris some tests will always fail.
+   if [ "x`uname`" = xSunOS ] ; then
+      echo "If you see 3 core dumps, do not be too alarmed. See"
+      echo "http://trac.sagemath.org/sage_trac/ticket/8270"
+      echo "This is a Solaris bug and can be safely ignored"
+      echo "http://bugs.opensolaris.org/bugdatabase/view_bug.do?bug_id=6550204"
+      echo "It will probably be fixed in later releases of Solaris 10"
+      echo "It was fixed in build 66 of OpenSolaris."
+   fi
+
+   cd src
+
+   make check
+
+   if [ $? -ne 0 ]; then
+       echo "Error encountered while running the iconv testsuite ... exiting"
+       exit 1
+   fi
+   echo "All the tests for iconv passed"
+   exit 0
+else
+   echo "iconv was not be tested, as the system iconv will be used"
+   echo "and not the iconv supplied with Sage. The iconv"
+   echo "supplied with Sage is only used on Cygwin, HP-UX and Solaris"
+   exit 0
 fi
 
-if [ "x`uname`" = xSunOS ] ; then
-   echo "If you see 3 core dumps, do not be too alarmed. See"
-   echo "http://trac.sagemath.org/sage_trac/ticket/8270"
-   echo "This is a Solaris bug and can be safely ignored"
-   echo "http://bugs.opensolaris.org/bugdatabase/view_bug.do?bug_id=6550204"
-   echo "It will probably be fixed in later releases of Solaris 10"
-fi
-
-cd src
-
-make check
-
-if [ $? -ne 0 ]; then
-    echo "Error encountered while running the iconv testsuite ... exiting"
-    exit 1
-fi
-
-echo "All the tests for iconv passed"
-exit 0
diff --git a/build/pkgs/iconv/spkg-install b/build/pkgs/iconv/spkg-install
--- a/build/pkgs/iconv/spkg-install
+++ b/build/pkgs/iconv/spkg-install
@@ -6,59 +6,68 @@ if [ -z "$SAGE_LOCAL" ] ; then
    exit 1
 fi
 
-
 # Only build iconv on Solaris, HP-UX and Cygwin
-if [ "x$UNAME" != xSunOS ] && [ "x$UNAME" != xHP-UX ] && [ "x$UNAME" != xCYGWIN ] ; then
-  echo "iconv will not be installed, as we only need to build it on"
-  echo "Solaris, HP-UX and Cygwin - see:"
-  echo "http://trac.sagemath.org/sage_trac/ticket/8567"
-  exit 0
-fi
+# See
+# http://trac.sagemath.org/sage_trac/ticket/8567
+# and http://trac.sagemath.org/sage_trac/ticket/9603
 
-echo "Installing iconv as the operating system is Cygwin, HP-UX or Solaris"
+if [ "x$UNAME" = xSunOS ] || [ "x$UNAME" = xHP-UX ] || [ "x$UNAME" = xCYGWIN ] ; then
+   echo "iconv will be installed as the operating system is Cygwin, HP-UX or Solaris"
+   echo "These system either lack iconv, or do not have a sufficiently capable"
+   echo "iconv. See:"
+   echo "http://trac.sagemath.org/sage_trac/ticket/8567"
+   echo "http://trac.sagemath.org/sage_trac/ticket/9603"
+
+   echo "First removing old iconv files if they exist"
+   # If iconv is updated, please double-check these are still necessary
+   # and that there are no extra files added.
+
+   rm -f $SAGE_LOCAL/bin/iconv  $SAGE_LOCAL/lib/charset.alias
+   rm -f $SAGE_LOCAL/lib/*libiconv*  $SAGE_LOCAL/lib/libcharset*
+   rm -f $SAGE_LOCAL/include/iconv.h  $SAGE_LOCAL/include/libcharset.h
+   rm -f $SAGE_LOCAL/include/localcharset.h
+   rm -rf  $SAGE_LOCAL/share/doc/libiconv
+   rm -f $SAGE_LOCAL/share/man/man1/iconv* $SAGE_LOCAL/share/man/man3/iconv*
 
 
-echo "Removing old iconv files if they exist"
-# If iconv is updated, please double-check these are still necessary
-# and that there are no extra files added.
+   # Let an environment variable CFLAG64 specify the option to generate 64-bit
+   # code. If this is not set, default to -m64.
+   if [ -z "$CFLAG64" ] ; then
+      CFLAG64=-m64
+   fi
 
-rm -f $SAGE_LOCAL/bin/iconv  $SAGE_LOCAL/lib/charset.alias
-rm -f $SAGE_LOCAL/lib/*libiconv*  $SAGE_LOCAL/lib/libcharset*
-rm -f $SAGE_LOCAL/include/iconv.h  $SAGE_LOCAL/include/libcharset.h
-rm -f $SAGE_LOCAL/include/localcharset.h
-rm -rf  $SAGE_LOCAL/share/doc/libiconv
-rm -f $SAGE_LOCAL/share/man/man1/iconv* $SAGE_LOCAL/share/man/man3/iconv*
+   # Add option for a 64-bit build if needed.
+   if [ "x$SAGE64" = xyes ] ; then
+      CFLAGS="$CFLAG64"
+      export CFLAGS
+   fi
 
+   cd src
+   ./configure --prefix=$SAGE_LOCAL
+   if [ $? -ne 0 ]; then
+      echo "Error configuring iconv"
+      exit 1
+   fi
 
-# Let an environment variable CFLAG64 specify the option to generate 64-bit
-# code. If this is not set, default to -m64.
-if [ -z "$CFLAG64" ] ; then
-   CFLAG64=-m64
-fi
+   make
+   if [ $? -ne 0 ]; then
+      echo "Error building iconv"
+      exit 1
+   fi
 
-# Add option for a 64-bit build if needed.
-if [ "x$SAGE64" = xyes ] ; then
-  CFLAGS="$CFLAG64"
-  export CFLAGS
-fi
-
-cd src
-./configure --prefix=$SAGE_LOCAL
-if [ $? -ne 0 ]; then
-    echo "Error configuring iconv"
-    exit 1
-fi
-
-make
-if [ $? -ne 0 ]; then
-    echo "Error making iconv"
-    exit 1
-fi
-
-make install
-
-if [ $? -ne 0 ]; then
-    echo "Error installing iconv"
-    exit 1
+   make install
+   if [ $? -ne 0 ]; then
+      echo "Error installing iconv"
+      exit 1
+   fi
+   exit 0
+else
+   echo "iconv will not be installed, as we only need to build it on"
+   echo "Solaris, HP-UX and Cygwin, as the system iconv will be"
+   echo "used on other platforms, rather than the one shipped with Sage"
+   echo "See:"
+   echo "http://trac.sagemath.org/sage_trac/ticket/8567"
+   echo "http://trac.sagemath.org/sage_trac/ticket/9603"
+   exit 0
 fi
 
