#13912: let iconv build on Cygwin without additional prereqs

diff --git a/build/pkgs/iconv/spkg-install b/build/pkgs/iconv/spkg-install
--- a/build/pkgs/iconv/spkg-install
+++ b/build/pkgs/iconv/spkg-install
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 if [ -z "$SAGE_LOCAL" ]; then
-    echo "SAGE_LOCAL undefined ... exiting"
-    echo "Maybe run 'sage -sh'?"
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage -sh'?"
     exit 1
 fi
 
@@ -36,23 +36,29 @@ CYGWIN|HP-UX|SunOS)
         export CC
     fi
 
+    # Disable NLS on Cygwin to be able to build libiconv without the Cygwin
+    # libiconv package.
+    if [ "$UNAME" = "CYGWIN" ]; then
+        ICONV_CONFIGURE="--disable-nls $ICONV_CONFIGURE"
+    fi
+
     cd src
 
-    ./configure --prefix="$SAGE_LOCAL"
+    ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" $ICONV_CONFIGURE
     if [ $? -ne 0 ]; then
-        echo "Error configuring iconv"
+        echo >&2 "Error configuring iconv"
         exit 1
     fi
 
     $MAKE
     if [ $? -ne 0 ]; then
-        echo "Error building iconv"
+        echo >&2 "Error building iconv"
         exit 1
     fi
 
     $MAKE install
     if [ $? -ne 0 ]; then
-        echo "Error installing iconv"
+        echo >&2 "Error installing iconv"
         exit 1
     fi
     exit 0
@@ -68,4 +74,3 @@ CYGWIN|HP-UX|SunOS)
 esac
 
 # NOT REACHED
-
