#9603: Consistently use "$UNAME"; more comments, corrections & cosmetic changes.

diff --git a/build/pkgs/iconv/spkg-check b/build/pkgs/iconv/spkg-check
--- a/build/pkgs/iconv/spkg-check
+++ b/build/pkgs/iconv/spkg-check
@@ -6,34 +6,36 @@ if [ -z "$SAGE_LOCAL" ]; then
 fi
 
 # Only test iconv on Solaris, HP-UX and Cygwin, as those are the only
-# platforms on which iconv is installed. On other platforms Sage uses
-# the system iconv.
+# platforms on which the iconv shipped with Sage will be installed. On
+# other platforms Sage uses the system's iconv.
 
 if [ "x$UNAME" = xSunOS ] || [ "x$UNAME" = xCYGWIN ] || [ "x$UNAME" = xHP-UX ]; then
-   # We must test iconv, but on Solaris some tests will always fail.
-   if [ "x`uname`" = xSunOS ] ; then
-      echo "If you see 3 core dumps, do not be too alarmed. See"
-      echo "http://trac.sagemath.org/sage_trac/ticket/8270"
-      echo "This is a Solaris bug and can be safely ignored"
-      echo "http://bugs.opensolaris.org/bugdatabase/view_bug.do?bug_id=6550204"
-      echo "It will probably be fixed in later releases of Solaris 10"
-      echo "It was fixed in build 66 of OpenSolaris."
-   fi
+    # We must test iconv, but on Solaris some tests will always fail.
+    if [ "x$UNAME" = xSunOS ]; then
+        echo "If you see 3 core dumps, do not be too alarmed."
+        echo "This is a known Solaris bug and can safely be ignored."
+        echo "See http://trac.sagemath.org/sage_trac/ticket/8270"
+        echo "It will probably be fixed in later releases of Solaris 10,"
+        echo "and was fixed in build 66 of OpenSolaris:"
+        echo "http://bugs.opensolaris.org/bugdatabase/view_bug.do?bug_id=6550204"
+    fi
 
-   cd src
+    cd src
 
-   $MAKE check
+    $MAKE check
 
-   if [ $? -ne 0 ]; then
-       echo "Error encountered while running the iconv test-suite ... exiting"
-       exit 1
-   fi
-   echo "All the tests for iconv passed"
-   exit 0
+    if [ $? -ne 0 ]; then
+        echo "Error encountered while running the iconv test suite ... exiting"
+        exit 1
+    fi
+    echo "All the tests for iconv passed."
+    exit 0
 else
-   echo "iconv was not be tested, as the system iconv will be used"
-   echo "and not the iconv supplied with Sage. The iconv"
-   echo "supplied with Sage is only used on Cygwin, HP-UX and Solaris"
-   exit 0
+    echo "iconv was not to be tested, since Sage will use the system's iconv"
+    echo "and not the one shipped with Sage."
+    echo "The iconv supplied by Sage is only used on Cygwin, HP-UX and Solaris."
+    exit 0
 fi
+
+# NOT REACHED
 
diff --git a/build/pkgs/iconv/spkg-install b/build/pkgs/iconv/spkg-install
--- a/build/pkgs/iconv/spkg-install
+++ b/build/pkgs/iconv/spkg-install
@@ -1,62 +1,70 @@
 #!/usr/bin/env bash
 
 if [ -z "$SAGE_LOCAL" ]; then
-   echo "SAGE_LOCAL undefined ... exiting"
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+    echo "SAGE_LOCAL undefined ... exiting"
+    echo "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
-# Only build iconv on Solaris, HP-UX and Cygwin
-# See
-# http://trac.sagemath.org/sage_trac/ticket/8567
-# and http://trac.sagemath.org/sage_trac/ticket/9603
+# Only build iconv on Solaris, HP-UX and Cygwin. See
+#     http://trac.sagemath.org/sage_trac/ticket/8567 and
+#     http://trac.sagemath.org/sage_trac/ticket/9603
+# for details.
 
-if [ "x$UNAME" = xSunOS ] || [ "x$UNAME" = xHP-UX ] || [ "x$UNAME" = xCYGWIN ]; then
-   echo "iconv will be installed as the operating system is Cygwin, HP-UX or Solaris"
-   echo "These system either lack iconv, or do not have a sufficiently capable"
-   echo "iconv. See:"
-   echo "http://trac.sagemath.org/sage_trac/ticket/8567"
-   echo "http://trac.sagemath.org/sage_trac/ticket/9603"
+if [ "x$UNAME" = xSunOS ] || [ "x$UNAME" = xHP-UX ] || [ "x$UNAME" = xCYGWIN ];
+then
+    echo "iconv will be installed as the operating system is Cygwin, HP-UX or Solaris."
+    echo "These systems either lack iconv, or do not have a sufficiently capable"
+    echo "version of iconv. See:"
+    echo "    http://trac.sagemath.org/sage_trac/ticket/8567"
+    echo "    http://trac.sagemath.org/sage_trac/ticket/9603"
 
-   # Let an environment variable CFLAG64 specify the option to generate 64-bit
-   # code. If this is not set, default to -m64.
-   if [ -z "$CFLAG64" ]; then
-      CFLAG64=-m64
-   fi
+    # Let an environment variable CFLAG64 specify the option to generate 64-bit
+    # code. If this is not set, default to -m64:
+    if [ -z "$CFLAG64" ]; then
+        CFLAG64=-m64
+    fi
 
-   # If the environment variable SAGE64="yes", then build a 64-bit version.
-   if [ "x$SAGE64" = xyes ]; then
-      CC="$CC $CFLAG64"
-      export CC
-      echo "Building a 64-bit version of iconv"
-   fi
+    # If the environment variable SAGE64=yes, force building a 64-bit version:
+    if [ "x$SAGE64" = xyes ]; then
+        echo "Building a 64-bit version of iconv"
+        # Put the flag(s) for building a 64-bit version into the C compiler
+        # command rather than into CFLAGS, since (the included version of)
+        # libtool would strip it off s.t. the build would otherwise fail.
+        # See http://trac.sagemath.org/sage_trac/ticket/9718 for details.
+        CC="$CC $CFLAG64"
+        export CC
+    fi
 
-   cd src
-   ./configure --prefix="$SAGE_LOCAL"
-   if [ $? -ne 0 ]; then
-      echo "Error configuring iconv"
-      exit 1
-   fi
+    cd src
 
-   $MAKE
-   if [ $? -ne 0 ]; then
-      echo "Error building iconv"
-      exit 1
-   fi
+    ./configure --prefix="$SAGE_LOCAL"
+    if [ $? -ne 0 ]; then
+        echo "Error configuring iconv"
+        exit 1
+    fi
 
-   $MAKE install
-   if [ $? -ne 0 ]; then
-      echo "Error installing iconv"
-      exit 1
-   fi
-   exit 0
+    $MAKE
+    if [ $? -ne 0 ]; then
+        echo "Error building iconv"
+        exit 1
+    fi
+
+    $MAKE install
+    if [ $? -ne 0 ]; then
+        echo "Error installing iconv"
+        exit 1
+    fi
+    exit 0
 else
-   echo "iconv will not be installed, as we only need to build it on"
-   echo "Solaris, HP-UX and Cygwin, as the system iconv will be"
-   echo "used on other platforms, rather than the one shipped with Sage"
-   echo "See:"
-   echo "http://trac.sagemath.org/sage_trac/ticket/8567"
-   echo "http://trac.sagemath.org/sage_trac/ticket/9603"
-   exit 0
+    echo "iconv will not be installed, as we only need to build it on"
+    echo "Solaris, HP-UX and Cygwin, as the system's iconv will be used"
+    echo "on other platforms, rather than the one shipped with Sage."
+    echo "See:"
+    echo "    http://trac.sagemath.org/sage_trac/ticket/8567"
+    echo "    http://trac.sagemath.org/sage_trac/ticket/9603"
+    exit 0
 fi
+
+# NOT REACHED
 
