updated the spkg-src to delete gap3 packages that need compilation

diff --git a/build/pkgs/gap3/spkg-install b/build/pkgs/gap3/spkg-install
--- a/build/pkgs/gap3/spkg-install
+++ b/build/pkgs/gap3/spkg-install
@@ -46,7 +46,7 @@ echo "Installing (copying) files..."
 mkdir -p "$INSTALL_DIR" &&
 cp -rf * "$INSTALL_DIR"
 if [[ $? -ne 0 ]]; then
-    echo >&2 "Error installing (copying) $PACKAGE_SHORTNAME files."
+    echo >&2 "Error copying $PACKAGE_SHORTNAME files."
     exit 1
 fi
 
