trac 9567: Now allows for the use of pyparsing using matplotlib.pyparsing

diff --git a/build/pkgs/networkx/spkg-install b/build/pkgs/networkx/spkg-install
--- a/build/pkgs/networkx/spkg-install
+++ b/build/pkgs/networkx/spkg-install
@@ -14,14 +14,19 @@ rm -rf "$SAGE_LOCAL"/lib/python/site-packages/networkx*
 rm -rf "$SAGE_LOCAL"/spkg/network*
 
 echo "Patching"
-#cp patches/nx_pylab.py src/networkx/drawing/
-#This patch will be fixed in networkx 1.2
-#cp patches/random_graphs.py src/networkx/generators/
-#if [ $? -ne 0]; then
-#    echo "Error copying patched random_graphs.py"
-#    exit 1
-#fi
-
+# This patch allows the user to use the matplotlib.pyparsing
+# as pyparsing is not included in the base install of sage
+# but is included in matplotlib.
+cp patchs/gml.py src/networkx/readwrite
+if [ $? -ne 0] then
+    echo "Error copying patched gml.py"
+    exit 1
+fi
+cp patchs/test_gml.py src/networx/readwrite/tests
+if [ $? -ne 0] then
+    echo "Error copying patched test_gml.py"
+    exit 1
+fi
 
 cd src
 
