added osx and sparc patch, deleted spkg-check

diff --git a/build/pkgs/ncurses/spkg-install b/build/pkgs/ncurses/spkg-install
--- a/build/pkgs/ncurses/spkg-install
+++ b/build/pkgs/ncurses/spkg-install
@@ -38,10 +38,18 @@ export CFLAGS
 export CPPFLAGS
 export LDFLAGS
 
-# End of pretty generic spkg-install file.
+cd src
+
+echo "Applying patches to upstream source..."
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [[ $? -ne 0 ]]; then
+        echo >&2 "Error applying '$patch'."
+        exit 1
+    fi
+done
 
 echo "Configuring ncurses..."
-cd src
 ./configure \
     --prefix="$SAGE_LOCAL" \
     --libdir="$SAGE_LOCAL/lib" \
