Fix last change

diff --git a/build/pkgs/lrslib/spkg-install b/build/pkgs/lrslib/spkg-install
--- a/build/pkgs/lrslib/spkg-install
+++ b/build/pkgs/lrslib/spkg-install
@@ -1,7 +1,5 @@
 #!/usr/bin/env bash
 
-cp -f patches/makefile src/makefile
-
 cd src/
 
 if [ "$SAGE_LOCAL" = "" ]; then
@@ -9,6 +7,15 @@ if [ "$SAGE_LOCAL" = "" ]; then
    echo "Maybe run 'sage -sh'?"
    exit 1
 fi
+
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
 $MAKE all-static
 if [ $? -ne 0 ]; then
