macaulay2-1.1-r7210: Made spkg-check better

diff --git a/build/pkgs/macaulay2/spkg-check b/build/pkgs/macaulay2/spkg-check
--- a/build/pkgs/macaulay2/spkg-check
+++ b/build/pkgs/macaulay2/spkg-check
@@ -1,2 +1,14 @@
+#!/usr/bin/env bash
+
+if [ "$SAGE_LOCAL" = "" ]; then
+   echo "SAGE_LOCAL undefined ... exiting";
+   echo "Maybe run 'sage -sh'?"
+   exit 1
+fi
+
 cd src/BUILD/normal
 make check
+if [ $? -ne 0 ]; then
+    echo "Failed to check Macaulay2."
+    exit 1
+fi
