gsl-1.10.p0: fix spkg-check, OSX 64 bit support, work around isinf bug on OSX

diff --git a/build/pkgs/gsl/spkg-check b/build/pkgs/gsl/spkg-check
--- a/build/pkgs/gsl/spkg-check
+++ b/build/pkgs/gsl/spkg-check
@@ -1,16 +1,10 @@
-#!/usr/bin/env python
+#!/usr/bin/env bash
 
-import os, sys
+cd src
 
-os.system("echo 'cd src; make check > test.err'")
+make check
 
-r = open('test.err').read()
+if [ $? -ne 0 ]; then
+    echo "Error: make check for GSL failed"
+fi
 
-if 'FAIL' in r:
-    open('test.out').read()
-    print r
-    sys.exit(1)
-else:
-    os.unlink('test.err')
-    os.unlink('test.out')
-    sys.exit(0)
