Trac #12221: pexpect-2.0.p5 (Jeroen Demeyer, 13 January 2012)  * Trac #12221: add env.patch to add env parameter to spawn.__init__()  * Restore upstream sources, use patch for patching

diff --git a/build/pkgs/pexpect/spkg-install b/build/pkgs/pexpect/spkg-install
--- a/build/pkgs/pexpect/spkg-install
+++ b/build/pkgs/pexpect/spkg-install
@@ -1,6 +1,16 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-cd src/
+cd src
+
+# Apply patches
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
 
 # On some systems pexpect doesn't upgrade correctly without
 # first removing the old version.
