#14706: Move previous install of R on OS X.

diff --git a/build/pkgs/r/spkg-install b/build/pkgs/r/spkg-install
--- a/build/pkgs/r/spkg-install
+++ b/build/pkgs/r/spkg-install
@@ -9,6 +9,10 @@ fi
 
 # Make sure CPPFLAGS and LDFLAGS are set to something (even the empty
 # string) to prevent R from overriding them.
+#
+# We need to explicitly add $SAGE_LOCAL/lib to LDFLAGS for R to find readline.
+# The --with-readline configure option only understands yes/no
+# and cannot be used to pass this path.
 CPPFLAGS="$CPPFLAGS"
 LDFLAGS="-L$SAGE_LOCAL/lib/ $LDFLAGS"
 
@@ -97,6 +101,7 @@ cd src
 # Apply patches.  See SPKG.txt for information about what each patch
 # does.
 for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue
     patch -p1 <"$patch"
     if [ $? -ne 0 ]; then
         echo >&2 "Error applying '$patch'"
@@ -129,26 +134,54 @@ if [ $? -ne 0 ]; then
 fi
 
 if [ $? -ne 0 ]; then
-    echo "Error configuring R."
+    echo >&2 "Error configuring R."
     exit 1
 fi
 
+if [ "$UNAME" = "Darwin" ]; then
+    # We have to move old installs of R when upgrading R in Sage on OS X.
+    # Indeed Sage modifies DYLD_LIBRARY_PATH whereas R build process
+    # modifies DYLD_LIBRARY_PATH, so that it is Sage's R and not the freshly
+    # built one which will get loaded during the build process and if they are
+    # different versions then the build process might fail.
+    # On systems using LD_LIBRARY_PATH, both Sage and R modify it and R wins,
+    # so no problem should occur.
+    if [ -d "$SAGE_LOCAL"/lib/R ]; then
+        RINSTALL_MOVED = yes
+        mv "$SAGE_LOCAL"/lib/R "$SAGE_LOCAL"/lib/R.old
+    fi
+fi
+
+# Build R
 $MAKE R
 if [ $? -ne 0 ]; then
-    echo "Error building R."
+    echo >&2 "Error building R."
+    if [ "$RINSTALL_MOVED" = yes ]; then
+        mv "$SAGE_LOCAL"/lib/R.old "$SAGE_LOCAL"/lib/R
+    fi
+    exit 1
+fi
+
+# needed for help system
+$MAKE vignettes
+if [ $? -ne 0 ]; then
+    echo >&2 "Error building vignettes."
+    if [ "$RINSTALL_MOVED" = yes ]; then
+        mv "$SAGE_LOCAL"/lib/R.old "$SAGE_LOCAL"/lib/R
+    fi
     exit 1
 fi
 
 # Remove old install
 rm -rf "$SAGE_LOCAL"/lib/r
 rm -rf "$SAGE_LOCAL"/lib/R
+rm -rf "$SAGE_LOCAL"/lib/R.old
 rm -rf "$SAGE_LOCAL"/lib/libRblas.* "$SAGE_LOCAL"/lib/libRlapack.* "$SAGE_LOCAL"/lib/libR.*
 
-
-$MAKE vignettes   # needed for help system
+# Install new version
 $MAKE install
 if [ $? -ne 0 ]; then
-    echo "Error installing R."
+    echo >&2 "Error installing R."
     exit 1
 fi
 
