fixed gap_packages, also package compiling/installing
packages that need compilation are installed old-style,
i.e. in-place, just what GAP itself does, and how it always
was in gap_packages. Package happrime is gone from GAP,
otherwise everything what 4.8.6 was providing is here

diff --git a/build/pkgs/gap_packages/spkg-install b/build/pkgs/gap_packages/spkg-install
--- a/build/pkgs/gap_packages/spkg-install
+++ b/build/pkgs/gap_packages/spkg-install
@@ -11,20 +11,29 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-
 cd src/pkg/
 
 #    happrime - no longer distributed, partly merged in Hap,
 #    cf. https://www.gap-system.org/Packages/packages.html#deppkg
 #    (GAP 4.8.6 still had it, but this is gone in 4.10)
 
-sdh_install aclib-* cohomolo-* corelg crime-* cryst crystcat design gbnp \
-    grape-* guava-* Hap1* HAPcryst hecke-* liealgdb-* liepring-* liering \
-    loops MapClass-* nq-* polymaking qpa-version-* quagroup repsn sla \
+sdh_install aclib-* corelg crime-* cryst crystcat design gbnp \
+    Hap1* HAPcryst hecke-* liealgdb-* liepring-* liering \
+    loops MapClass-* polymaking qpa-version-* quagroup repsn sla \
     sonata-* Toric-* polycyclic-* "$PKG_DIR"
 
+for p in cohomolo-1.6.7 grape-4.8.1 guava-3.14 nq-2.5.3
+do
+    echo "Copying package $p"
+    cp -r $p "$PKG_DIR"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error copying package $p."
+        exit 1
+    fi
+done
+
 # Build GRAPE package
-cd "$PKG_DIR/grape*"
+cd "$PKG_DIR"/grape*
 rm -rf bin   # added since rebuilding breaks otherwise
 ./configure "$GAP_DIR"
 if [ $? -ne 0 ]; then
@@ -66,7 +75,7 @@ if [ $? -ne 0 ]; then
 fi
 
 # Build nq package
-cd "$PKG_DIR/nq-*"
+cd "$PKG_DIR"/nq-*
 ./configure --with-gaproot="$GAP_DIR"
 if [ $? -ne 0 ]; then
     echo >&2 "Error configuring nq package."
