[FIXUP] make sage-sdist compatible with git layout

diff --git a/src/bin/sage-sdist b/src/bin/sage-sdist
--- a/src/bin/sage-sdist
+++ b/src/bin/sage-sdist
@@ -5,141 +5,118 @@
 # This script should be called by the spkg/bin/sage script
 ########################################################
 
-if [ $# -ne 2 ]; then
-    echo "Usage: $0 <SAGE_VERSION> <SAGE_ROOT>"
+set -e
+
+CMD="${0##*/}"
+
+die () {
+    echo >&2 -e "$@"
     exit 1
+}
+
+usage () {
+    echo "usage: $CMD <SAGE_VERSION> [TMP_DIR]"
+}
+
+[ $# -ge 1 -a $# -le 2 ] || die `usage`
+
+[ -n "$SAGE_ROOT" ] || die "must be run from within a Sage enviroment, or with SAGE_ROOT provided"
+
+if [ "$#" -gt 1 ]; then
+    TMP_DIR="$2"
+else
+    TMP_DIR="$SAGE_ROOT/tmp"
 fi
 
 # If $1 starts with "sage-", remove this prefix
 export SAGE_VERSION=`echo "$1" | sed 's/^sage-//'`
-export SAGE_ROOT=$2
-
-# are we trying to sdist a bdist copy? If so, tell the user about it and
-# fail.
-if [ -f "$SAGE_ROOT/spkg/standard/.from_bdist" ]
-then
-    cat <<EOF
-You are running 'sage --sdist' on a copy of Sage that was created with
-'sage --bdist'; this copy includes placeholders for the spkg files and
-does not have the SAGE_ROOT/spkg/base directory, so a source
-distribution cannot be made from this copy of Sage.
-
-You can fix this by:
-
-  * putting the "real" spkg files into spkg/standard; get a source
-    tarball for this version of Sage and copy the directory.
-  * copying the spkg/base directory from the source tarball into this
-    copy of Sage.
-  * removing the file spkg/standard/.from_bdist.
-
-Cannot create source distribution. Exiting.
-EOF
-    exit 1
-fi
 
 TARGET="sage-$SAGE_VERSION"
 
 SAGE_RELEASE_DATE=`date -u +'%Y-%m-%d'`
 
+rm -rf "$TMP_DIR/$TARGET"
+mkdir -p "$TMP_DIR/$TARGET"
+
+git clone "$SAGE_ROOT" "$TMP_DIR/$TARGET"
+cd "$TMP_DIR/$TARGET"
+git remote set-url origin git://github.com/sagemath/sage.git
+
 # Update Sage version file in SAGE_ROOT.
-echo "Sage version $SAGE_VERSION, released $SAGE_RELEASE_DATE" > "$SAGE_ROOT"/VERSION.txt
+echo "Sage version $SAGE_VERSION, released $SAGE_RELEASE_DATE" > VERSION.txt
 
-# Update Sage version file in devel/sage/sage: this is done here so
+# Update Sage version file in SAGE_SRC/sage: this is done here so
 # the banner produced below this if block is correct.
-if [ -d "$SAGE_ROOT"/devel/sage/sage ]; then
-    cd "$SAGE_ROOT"/devel/sage/sage
-    echo '"""nodoctests"""' > version.py
-    echo "version='"$SAGE_VERSION"'; date='"$SAGE_RELEASE_DATE"'" >> version.py
-    cd "$SAGE_ROOT"/devel/sage
-    python setup.py install
-fi
+(
+    cd src
+    echo '"""nodoctests"""' > sage/version.py
+    echo "version='"$SAGE_VERSION"'; date='"$SAGE_RELEASE_DATE"'" >> sage/version.py
+    echo "import sage.misc.banner; sage.misc.banner.banner()" | python > bin/sage-banner
+)
 
-cd "$SAGE_ROOT"/local/bin/
-echo "import sage.misc.banner; sage.misc.banner.banner()" | ./python > sage-banner
+git commit -am "$SAGE_VERSION" &&
+    git tag "$SAGE_VERSION" ||
+        die "Error committing to the repository."
 
-# Copy sage root directory.  Cloning needs to be done in an empty
-# directory, so we do this now.  Creating the sage_root spkg is done
-# in sage-make_devel_packages below.
-cd "$SAGE_ROOT"
+# Copy all the upstream packages
+mkdir -p upstream
+export SAGE_CURRENT_UPSTREAM="$SAGE_ROOT/upstream"
+export SAGE_INSTALL_FETCH_ONLY=yes
 
-hg diff
-hg status
-hg tag "$SAGE_VERSION"
-hg commit -m "$SAGE_VERSION"
-if [ $? -gt 1 ]; then  # Status 1 is returned when there are no changes
-    echo >&2 "Error committing SAGE_ROOT repository."
-    exit 1
-fi
+# create fake sage-spkg that only downloads files if necessary
+echo '
+set -e
+. "${0%spkg}env"
+mkdir -p "$SAGE_SPKG_INST"
+PKG_NAME="$1"
+PKG_BASE=`echo "$PKG_NAME" | sed 's/-.*//'`
+PKG_VER="${PKG_NAME#${PKG_BASE}}"
+PKG_VER="${PKG_VER#-}"
+PKG_NAME_UPSTREAM="${PKG_BASE}-`echo $PKG_VER | sed 's/\.p[0-9][0-9]*$//'`"
+for tarball in `ls -1t ${SAGE_CURRENT_UPSTREAM}/${PKG_NAME_UPSTREAM}.tar* 2>/dev/null`; do
+    if [ -f "$tarball" ]; then
+        cp "$tarball" $SAGE_ROOT/upstream
+        exit 0
+        break
+    fi
+done
+PKG_URL="$SAGE_UPSTREAM$PKG_NAME_UPSTREAM"
+PKG_TMP="${PKG_URL##*/}.tmp"
+for EXT in .tar.bz2 .tar.gz .tar; do
+    REAL_PKG_URL="$PKG_URL$EXT"
+    echo ">>> Trying to download $REAL_PKG_URL"
+    sage-download-file "$REAL_PKG_URL" >"$PKG_TMP" &&
+        { DOWNLOAD_SUCCESS=yes; break; }
+done
+[ -n "$DOWNLOAD_SUCCESS" ] || exit 1
+mv "$PKG_TMP" "$SAGE_ROOT/upstream/${PKG_URL##*/}$EXT"
+touch "$SAGE_SPKG_INST/$PKG_NAME"
+' > src/bin/sage-spkg
+chmod +x src/bin/sage-spkg
 
-# Create new sage_root, sage_scripts,... packages
-./local/bin/sage-make_devel_packages "$SAGE_VERSION" "$SAGE_ROOT"
+# use install to get all needed packages
+(
+    cd build
+    SAGE_BUILD_GCC=yes ./install all
+)
+cp "$SAGE_ROOT/upstream/prereq"*.tar.gz upstream
 
-if [ $? -ne 0 ]; then
-    echo >&2 "Error building the Sage packages."
-    exit 1
-fi
+# remove any artifacts from running install
+make distclean
 
+# revert changes to sage-spkg
+git checkout HEAD src/bin/sage-spkg
 
-# Top directory for temporary files
-TOP=`mktemp -d "${TMPDIR:-/tmp}/sage-sdist-XXXXXX"`
-if [ $? -ne 0 ]; then
-    echo >&2 "Error creating temporary directory."
-    exit 1
-fi
+cd "$TMP_DIR"
 
+echo "Creating $TARGET.tar.gz ..."
+tar zcf "$TARGET".tar.gz "$TARGET"
 
-# Copy all files and create the tarball
-copy_sdist()
-{
-    # Exit on errors
-    set -e
+mkdir -p "$SAGE_ROOT"/dist
 
-    # Temporary "SAGE_ROOT" for the sdist.
-    TMPROOT="$TOP/$TARGET"
+rm -rf "$SAGE_ROOT/dist/$TARGET"
 
-    ROOT_REPO="sage_root-$SAGE_VERSION"
+echo "Moving final distribution file to $SAGE_ROOT/dist"
 
-    # Extract the SAGE_ROOT repository to $TOP/$ROOT_REPO, then rename to
-    # $TMPROOT.  This will become the root directory of the source tarball.
-    cd "$TOP"
-    tar xjf "$SAGE_ROOT/spkg/standard/${ROOT_REPO}.spkg"
-    mv "$ROOT_REPO" "$TMPROOT"
-    cd "$TMPROOT"
-
-    # Remove spkg-install which is only needed in the spkg
-    rm spkg-install
-
-    # Copy all base and standard packages
-    cp -p "$SAGE_ROOT"/spkg/base/*.tar* spkg/base
-    cp -p "$SAGE_ROOT"/spkg/standard/*.spkg spkg/standard
-
-    # Put VERSION.txt in the new tarball root and also in spkg/standard,
-    # a directory available for download during the update process.
-    # (See sage-update)
-    cp -p "$SAGE_ROOT/VERSION.txt" .
-    cp -p "$SAGE_ROOT/VERSION.txt" spkg/standard
-
-
-    # Package the sdist repository
-    cd "$TOP"
-    tar cf "$TARGET".tar "$TARGET"
-
-    mkdir -p "$SAGE_ROOT"/dist
-
-    rm -rf "$SAGE_ROOT/dist/$TARGET"
-
-    mv "$TARGET" "$SAGE_ROOT"/dist/
-    mv "$TARGET.tar" "$SAGE_ROOT"/dist/
-}
-
-# Get exit status of copy_sdist function.
-# We want to remove $TOP no matter what happens.
-( copy_sdist ); status=$?
-
-rm -rf "$TOP"
-
-if [ $status -ne 0 ]; then
-    echo >&2 "Copying and packing source distribution failed"
-fi
-
-exit $status
+mv "$TARGET" "$SAGE_ROOT"/dist/
+mv "$TARGET".* "$SAGE_ROOT"/dist/
