Trac #11926: Run sage-starts after upgrading Do not run "sage-location" in sage-starts since "sage -c" does that anyway

diff --git a/src/bin/sage-sage b/src/bin/sage-sage
--- a/src/bin/sage-sage
+++ b/src/bin/sage-sage
@@ -258,7 +258,7 @@ sage_setup() {
     fi
 
     # Check to see if the whole Sage install tree has moved.
-    # If so, regenerate .pyc files.
+    # If so, change various hardcoded paths.
     "$SAGE_ROOT/local/bin/"sage-location
     if [ $? -ne 0 ]; then
         exit 1
@@ -920,22 +920,25 @@ fi
 #fi
 
 if [ "$1" = '-upgrade' -o "$1" = "--upgrade" ]; then
+    shift
+
     # People often move the Sage install right before doing the upgrade, so it's
     # important to fix any path hardcoding issues first, or certain library
     # links will fail.
-    "$SAGE_ROOT/local/bin/"sage-location
+    sage-location
 
-    # Do it twice since when installing sage-scripts and a running
-    # script changes, it gets confused and exits with an error.
+    # Run sage-upgrade twice since when installing sage-scripts and a
+    # running script changes, it gets confused and exits with an error.
     # Running again (with the script replaced) then fixes the problem.
-    # Run from a temporary copy of sage-sage
-    shift
     sage-upgrade "$@"
-    if [ $? = 2 ]; then   # this exit codes means the user elected not to do the upgrade at all.
-        exit $?
+    if [ $? -eq 2 ]; then   # this exit code means the user elected not to do the upgrade at all.
+        exit 2
     fi
     echo "Double checking that all packages have been installed."
-    sage-upgrade "$@"
+    sage-upgrade "$@" || exit $?
+
+    # Check that Sage still works
+    sage-starts
     exit $?
 fi
 
diff --git a/src/bin/sage-starts b/src/bin/sage-starts
--- a/src/bin/sage-starts
+++ b/src/bin/sage-starts
@@ -1,16 +1,22 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
-sage-location
-
-if [ $? -ne 0 ]; then
-   echo "Problem with sage location or flags."
-   exit 1
+# Run this test from SAGE_ROOT.
+# If SAGE_ROOT is not defined (this will be the case when called from
+# the top-level Makefile), assume the current directory is SAGE_ROOT.
+if [ -n "$SAGE_ROOT" ]; then
+    cd "$SAGE_ROOT"
 fi
 
+echo
 echo "Testing that Sage starts..."
-sage -c "print 'Yes, Sage starts.'"
+spkg/pipestatus "./sage -c \"print 'Yes, Sage starts.'\" 2>&1" "tee -a start.log"
 
 if [ $? -ne 0 ]; then
-    echo "Sage failed to startup."
+    echo >&2 "Sage failed to start up."
+    echo >&2 "Please email sage-devel (http://groups.google.com/group/sage-devel)"
+    echo >&2 "explaining the problem and send the log file"
+    echo >&2 "  `pwd`/start.log"
+    echo >&2 "Describe your computer, operating system, etc."
+    rm local/lib/sage-started.txt 2>/dev/null
     exit 1
 fi
