Verify checksums of upstream sources.

diff --git a/src/bin/sage-spkg b/src/bin/sage-spkg
--- a/src/bin/sage-spkg
+++ b/src/bin/sage-spkg
@@ -74,6 +74,46 @@ When you are done debugging, you can type "exit" to leave the subshell.
 MESSAGE
 }
 
+lookup_param()
+{
+    local param=$1
+    local file=$2
+    RESULT=`grep "^$param *="  $file| sed "s/^$param *= *//"`
+    echo $RESULT
+}
+
+verify_checksum()
+{
+    local file=$1
+    local checksums=$2
+    
+    if [ ! -f $checksums ]; then
+        echo "No checksum file: $checksums"
+        exit 1
+    fi
+
+    if command -v shasum > /dev/null; then
+        expected=`lookup_param sha1 $checksums`
+        actual=`shasum -a 1 $file | sed 's/ .*//'`
+    elif command -v md5sum > /dev/null; then
+        expected=`lookup_param md5 $checksums`
+        actual=`md5sum $file | sed 's/ .*//'`
+    elif command -v md5 > /dev/null; then
+        expected=`lookup_param md5 $checksums`
+        actual=`md5 $file | sed 's/.*= *//'`
+    else
+        # POSIX
+        expected=`lookup_param cksum $checksums`
+        actual=`cksum $file | sed 's/ .*//'`
+    fi
+
+    echo "Checksum: $expected vs $actual"
+    if [ "$expected" != "$actual" ]; then
+        echo "Invalid checksum for $file"
+        exit 1
+    fi
+}
+
 # Handle -n, -t, -q options for recursive make
 # See Trac #12016.
 if echo "$MAKE $MAKEFLAGS -$MAKEFLAGS" |grep '[ ]-[A-Za-z]*[qnt]' >/dev/null; then
@@ -420,6 +460,10 @@ fi
 # up the system if we do something wrong.
 cd "$SAGE_ROOT" || exit
 
+if [ "$USE_LOCAL_SCRIPTS" == yes ]; then
+    verify_checksum "$PKG_SRC" "$PKG_SCRIPTS/checksums.ini"
+fi
+
 if [ $DOWNLOAD_ONLY -ne 0 ]; then
     exit 0
 fi
@@ -484,6 +528,7 @@ if [ "$USE_LOCAL_SCRIPTS" == yes ]; then
     echo "Setting up build directory for $PKG_NAME"
     cp -Rp "$PKG_SCRIPTS" "$PKG_NAME"
     cd "$PKG_NAME"
+    verify_checksum "$PKG_SRC" "$PKG_SCRIPTS/checksums.ini"
 else
     echo "Extracting package $PKG_SRC"
     ls -l "$PKG_SRC"
