Allow sage to run if sage-env is not present

diff --git a/src/bin/sage b/src/bin/sage
--- a/src/bin/sage
+++ b/src/bin/sage
@@ -430,13 +430,18 @@ fi
 # append -env to that). We redirect stdout to stderr, which is safer
 # for scripts.
 #####################################################################
-. "$0-env" >&2
-if [ $? -ne 0 ]; then
-    echo >&2 "Error setting environment variables by sourcing '$0-env';"
-    echo >&2 "possibly contact sage-devel (see http://groups.google.com/group/sage-devel)."
-    exit 1
+if [ -f "$0-env" ]; then
+    . "$0-env" >&2
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error setting environment variables by sourcing '$0-env';"
+        echo >&2 "possibly contact sage-devel (see http://groups.google.com/group/sage-devel)."
+        exit 1
+    fi
 fi
 
+if [ -z "$DOT_SAGE" ]; then
+    DOT_SAGE="$HOME/.sage"
+fi
 
 # Prepare for running Sage, either interactively or non-interactively.
 sage_setup() {
