#9433: put more files under revision control.  scripts patch.

diff --git a/src/bin/sage-bdist b/src/bin/sage-bdist
--- a/src/bin/sage-bdist
+++ b/src/bin/sage-bdist
@@ -17,7 +17,7 @@ PKGDIR=spkg
 
 CUR=`pwd`
 
-OPT="pPR"
+CP_OPT="-pPR"
 
 if [ $# -ne 2 ]; then
    echo "Usage: $0 <SAGE_VERSION> <SAGE_ROOT>"
@@ -32,27 +32,36 @@ TARGET=sage-"$SAGE_VERSION"-`uname -m`-`uname`
 TARGET=`echo $TARGET | sed -e 's/ //'`     #no blank spaces
 TMP="$CUR/tmp/$TARGET"
 
-if [ ! -d "$CUR/tmp" ]; then
-   mkdir "$CUR/tmp"
-fi
+mkdir -p "$CUR/tmp"
 
-if [ -d "$TMP" ]; then
-   rm -rf "$TMP"
-fi
-
+rm -rf "$TMP"
 mkdir "$TMP"
+
+# copy sage root repo over:
+cd "$SAGE_ROOT"
+
+echo "Copying root repository..."
+"$SAGE_ROOT"/sage --hg clone --pull . "$TMP"
+
+if [ $? -ne 0 ]; then
+    echo "Error copying Sage root repository."
+    exit 1
+fi
+
+rm "$TMP"/.hg/hgrc
+echo "Done copying root repository."
 
 cd "$SAGE_ROOT"
 
 echo "Copying files over to tmp directory"
-cp -$OPT examples local Makefile *.txt *.sage sage ipython data "$TMP"/
+cp $CP_OPT examples local data "$TMP"/
 
 if [ -d devel/sage-main ]; then
    echo "Copying Sage library over"
    mkdir "$TMP"/devel/
-   cp -L$OPT devel/sage-main "$TMP"/devel/sage-main
-   cp -L$OPT devel/sagenb-main "$TMP"/devel/sagenb-main
-   cd $TMP/devel
+   cp -L $CP_OPT devel/sagenb-main "$TMP"/devel/sagenb-main
+   cp -L $CP_OPT devel/sage-main "$TMP"/devel/sage-main
+   cd "$TMP"/devel
    ln -s sage-main sage
    ln -s sagenb-main sagenb
    cd sage
@@ -65,18 +74,16 @@ fi
 
 cd "$SAGE_ROOT"
 
-if [ -d $PKGDIR ]; then
+if [ -d "$PKGDIR" ]; then
    echo "Making empty spkg's"
-   cd $PKGDIR
-   mkdir $TMP/$PKGDIR
-   mkdir $TMP/$PKGDIR/build
-   mkdir $TMP/$PKGDIR/optional
-   cp -$OPT installed $TMP/$PKGDIR/
-   cp -$OPT standard $TMP/$PKGDIR/
-   cp  install README.txt gen_html pipestatus $TMP/$PKGDIR/
-   cd $TMP/$PKGDIR/standard/
-   for F in `/bin/ls *.spkg`; do
-       echo "Placeholder spkg file so this binary version of Sage knows this package version used when installing Sage." > $F
+   cd "$PKGDIR"
+   mkdir "$TMP/$PKGDIR"/build
+   mkdir "$TMP/$PKGDIR"/optional
+   cp $CP_OPT installed "$TMP/$PKGDIR/"
+   cp $CP_OPT standard "$TMP/$PKGDIR/"
+   cd "$TMP/$PKGDIR"/standard/
+   for spkg in *.spkg; do
+       echo "Placeholder spkg file so this binary version of Sage knows this package version used when installing Sage." >"$spkg"
    done
    # sage -sdist uses the following file to detect if it's working with
    # a "bdisted" copy
@@ -88,7 +95,7 @@ if [ "$UNAME" = "Darwin" ]; then
     cd "$TARGET"
     mkdir x
     echo "There will be an error about x below that you can safely ignore."
-    mv * x
+    mv * .hg* x
     mv x sage
     cp sage/local/bin/sage-README-osx.txt README.txt
 
@@ -120,7 +127,7 @@ if [ "$UNAME" = "Darwin" ]; then
         fi
 
         echo 'Copying Sage.app'
-        cp -L$OPT "$SAGE_ROOT/data/extcode/sage/ext/mac-app/build/$CONFIGURATION/Sage.app" ./Sage.app
+        cp -L $CP_OPT "$SAGE_ROOT/data/extcode/sage/ext/mac-app/build/$CONFIGURATION/Sage.app" ./Sage.app
         # Info.plist is a binary plist, so convert it for processing with sed.
         # I would just change it to be an xml plist, but xcode changes it back.
         plutil -convert xml1 ./Sage.app/Contents/Info.plist
@@ -142,7 +149,7 @@ if [ "$UNAME" = "Darwin" ]; then
     if [ "$SAGE_APP_DMG" != "no" ]; then
         echo "Creating dmg"
         echo "(If you don't wish to create a disk image please set SAGE_APP_DMG=no)"
-        DYLD_LIBRARY_PATH=$SAGE_ORIG_DYLD_LIBRARY_PATH; export DYLD_LIBRARY_PATH
+        DYLD_LIBRARY_PATH="$SAGE_ORIG_DYLD_LIBRARY_PATH"; export DYLD_LIBRARY_PATH
         hdiutil create -srcfolder "$TARGET" -format UDBZ "$TARGET".dmg
     else
         echo 'If you wish to create a disk image please set'
@@ -157,15 +164,11 @@ else
     tar zcvf "$TARGET".tar.gz "$TARGET"
 fi
 
-if [ ! -d $SAGE_ROOT/dist ]; then
-    mkdir $SAGE_ROOT/dist
-fi
+mkdir -p "$SAGE_ROOT"/dist
 
-if [ -d $SAGE_ROOT/dist/$TARGET ]; then
-    rm -rf "$SAGE_ROOT/dist/$TARGET"
-fi
+rm -rf "$SAGE_ROOT/dist/$TARGET"
 
 echo "Moving final distribution file to $SAGE_ROOT/dist"
 
-mv $TARGET $SAGE_ROOT/dist/
-mv $TARGET.* $SAGE_ROOT/dist/
+mv "$TARGET" "$SAGE_ROOT"/dist/
+mv "$TARGET".* "$SAGE_ROOT"/dist/
diff --git a/src/bin/sage-make_devel_packages b/src/bin/sage-make_devel_packages
--- a/src/bin/sage-make_devel_packages
+++ b/src/bin/sage-make_devel_packages
@@ -14,9 +14,9 @@ fi
 
 SAGE_VERSION=$1
 SAGE_ROOT=$2
-SPKG_INST=$SAGE_ROOT/spkg/installed/
+SPKG_INST="$SAGE_ROOT"/spkg/installed/
 export SAGE_ROOT SAGE_VERSION
-TARGET="sage-"$1
+TARGET=sage-$1
 
 # REMOVE OLD PACKAGES
 cd "$SAGE_ROOT"/spkg/standard/
@@ -25,6 +25,7 @@ rm examples-*.spkg
 rm extcode-*.spkg
 rm sage-*.spkg
 rm sage_scripts-*.spkg
+rm sage_root-*.spkg
 
 if [ $# -eq 2 ]; then
    DESTINATION="$SAGE_ROOT"/spkg/standard/
@@ -32,40 +33,40 @@ else
    DESTINATION=$3
 fi
 
-if [ ! -d $DESTINATION ]; then
-   mkdir $DESTINATION
+if [ ! -d "$DESTINATION" ]; then
+   mkdir "$DESTINATION"
 fi
 
 cd "$DESTINATION"
 DESTINATION=`pwd`
-PKG=$DESTINATION
+PKG="$DESTINATION"
 
 # NEW SAGE SOURCE PACKAGE
-if [ -d $SAGE_ROOT/devel/sage-main ]; then
-   cd $SAGE_ROOT/devel/sage-main
+if [ -d "$SAGE_ROOT"/devel/sage-main ]; then
+   cd "$SAGE_ROOT"/devel/sage-main
    hg diff
    hg status
    hg tag "$SAGE_VERSION"
    hg commit -m "$SAGE_VERSION"
    #./sage-push
    chmod +x spkg-dist
-   ./spkg-dist $SAGE_VERSION $SAGE_ROOT
+   ./spkg-dist "$SAGE_VERSION" "$SAGE_ROOT"
    if [ $? -ne 0 ]; then
-       echo "Error building the sage source code package"
+       echo "Error building the Sage source code package"
        exit 1
    fi
-   mv dist/sage-$SAGE_VERSION.spkg $DESTINATION/
-   touch $SPKG_INST/sage-$SAGE_VERSION
+   mv dist/sage-"$SAGE_VERSION".spkg "$DESTINATION"/
+   touch "$SPKG_INST"/sage-"$SAGE_VERSION"
 fi
 
-if [ ! -f $PKG/sage-$SAGE_VERSION.spkg ]; then
+if [ ! -f "$PKG"/sage-"$SAGE_VERSION".spkg ]; then
     echo "The package sage-$SAGE_VERSION.spkg wasn't created."
     exit 1
 fi
 
 # NEW SAGE EXTERNAL CODE PACKAGE
-if [ -d $SAGE_ROOT/data/extcode ]; then
-   cd $SAGE_ROOT/data/extcode
+if [ -d "$SAGE_ROOT"/data/extcode ]; then
+   cd "$SAGE_ROOT"/data/extcode
    hg diff
    hg status
    hg tag "$SAGE_VERSION"
@@ -73,43 +74,43 @@ if [ -d $SAGE_ROOT/data/extcode ]; then
 
    #./sage-push
    chmod +x spkg-dist
-   ./spkg-dist $SAGE_VERSION $SAGE_ROOT
+   ./spkg-dist "$SAGE_VERSION" "$SAGE_ROOT"
    if [ $? -ne 0 ]; then
        echo "Error building the extcode package"
        exit 1
    fi
-   mv extcode-$SAGE_VERSION.spkg $DESTINATION/
-   touch $SPKG_INST/extcode-$SAGE_VERSION
+   mv extcode-"$SAGE_VERSION".spkg "$DESTINATION"/
+   touch "$SPKG_INST"/extcode-"$SAGE_VERSION"
 fi
 
 
-if [ ! -f $PKG/extcode-$SAGE_VERSION.spkg ]; then
+if [ ! -f "$PKG"/extcode-"$SAGE_VERSION".spkg ]; then
     echo "The package extcode-$SAGE_VERSION.spkg wasn't created."
     exit 1
 fi
 
 # NEW SAGE EXAMPLE CODE PACKAGE
-if [ -d $SAGE_ROOT/examples ]; then
-   cd $SAGE_ROOT/examples
+if [ -d "$SAGE_ROOT"/examples ]; then
+   cd "$SAGE_ROOT"/examples
    hg diff
    hg status
    hg tag "$SAGE_VERSION"
    hg commit -m "$SAGE_VERSION"
    #./sage-push
    cd ..
-   rm -rf examples-$SAGE_VERSION
-   cp -r examples examples-$SAGE_VERSION
-   "$SAGE_ROOT"/sage -pkg examples-$SAGE_VERSION
+   rm -rf examples-"$SAGE_VERSION"
+   cp -r examples examples-"$SAGE_VERSION"
+   "$SAGE_ROOT"/sage -pkg examples-"$SAGE_VERSION"
    if [ $? -ne 0 ]; then
        echo "Error building examples package"
        exit 1
    fi
-   mv examples-$SAGE_VERSION.spkg $DESTINATION/
-   rm -rf examples-$SAGE_VERSION
-   touch $SPKG_INST/examples-$SAGE_VERSION
+   mv examples-"$SAGE_VERSION".spkg "$DESTINATION"/
+   rm -rf examples-"$SAGE_VERSION"
+   touch "$SPKG_INST"/examples-"$SAGE_VERSION"
 fi
 
-if [ ! -f $PKG/examples-$SAGE_VERSION.spkg ]; then
+if [ ! -f "$PKG"/examples-"$SAGE_VERSION".spkg ]; then
     echo "The package examples-$SAGE_VERSION.spkg wasn't created."
     exit 1
 fi
@@ -119,8 +120,8 @@ fi
 
 
 # NEW SAGE SCRIPTS PACKAGE
-SCRIPTS=sage_scripts-$SAGE_VERSION
-cd $SAGE_ROOT/local/bin/
+SCRIPTS=sage_scripts-"$SAGE_VERSION"
+cd "$SAGE_ROOT"/local/bin/
 
 #./sage-push
 hg diff
@@ -133,31 +134,64 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-rm -rf $SCRIPTS
-mkdir $SCRIPTS
+rm -rf "$SCRIPTS"
+mkdir "$SCRIPTS"
 chmod +x sage-*
 chmod -x sage-README-osx.txt sage-banner sage-gdb-commands
 chmod -x sage-maxima.lisp sage-verify-pyc
 rm sage-*~
 
-cp -pr sage-* .hg* ipy_profile_sage.py $SCRIPTS/
-cp -p $SAGE_ROOT/sage-python $SCRIPTS/
-cp -p $SAGE_ROOT/COPYING.txt $SCRIPTS/
-cp -p $SAGE_ROOT/README.txt $SCRIPTS/
-cp -pr $SAGE_ROOT/ipython $SCRIPTS/
-cp -p $SAGE_ROOT/spkg/install $SCRIPTS/
-cp -p $SAGE_ROOT/local/bin/sage-spkg-install $SCRIPTS/spkg-install
-cp -p $SAGE_ROOT/local/bin/SbuildHack.pm $SCRIPTS/
-cp -p $SAGE_ROOT/local/bin/ncadoctest.py $SCRIPTS/
-cp -p $SAGE_ROOT/local/bin/sagedoctest.py $SCRIPTS/
+cp -pr sage-* .hg* ipy_profile_sage.py "$SCRIPTS"/
+cp -p "$SAGE_ROOT"/local/bin/sage-spkg-install "$SCRIPTS"/spkg-install
+cp -p "$SAGE_ROOT"/local/bin/SbuildHack.pm "$SCRIPTS"/
+cp -p "$SAGE_ROOT"/local/bin/ncadoctest.py "$SCRIPTS"/
+cp -p "$SAGE_ROOT"/local/bin/sagedoctest.py "$SCRIPTS"/
 
-chmod +x $SCRIPTS/spkg-install
-tar -jcf $SCRIPTS.spkg $SCRIPTS
-mv $SCRIPTS.spkg $DESTINATION/
-rm -rf $SCRIPTS
-touch $SPKG_INST/sage_scripts-$SAGE_VERSION
+chmod +x "$SCRIPTS"/spkg-install
+tar -jcf "$SCRIPTS".spkg "$SCRIPTS"
+mv "$SCRIPTS".spkg "$DESTINATION"/
+rm -rf "$SCRIPTS"
+touch "$SPKG_INST"/sage_scripts-"$SAGE_VERSION"
 
-if [ ! -f $PKG/sage_scripts-$SAGE_VERSION.spkg ]; then
+if [ ! -f "$PKG/sage_scripts-$SAGE_VERSION.spkg" ]; then
     echo "The package sage_scripts-$SAGE_VERSION.spkg wasn't created."
+    exit 1
+fi
+
+#################################
+
+# SAGE ROOT PACKAGE: sage-sdist already tags and commits the repo, so
+# we just need to build the spkg file.
+
+ROOT_REPO=sage_root-"$SAGE_VERSION"
+cd "$SAGE_ROOT"
+
+rm -rf "$ROOT_REPO"
+mkdir "$ROOT_REPO"
+cd "$ROOT_REPO"
+
+echo "Copying root repository..."
+"$SAGE_ROOT"/sage --hg clone --pull "$SAGE_ROOT" .
+
+if [ $? -ne 0 ]; then
+    echo "Error copying Sage root repository."
+    exit 1
+fi
+
+rm .hg/hgrc
+cd "$SAGE_ROOT"
+
+cp -p "$SAGE_ROOT"/spkg/root-spkg-install "$ROOT_REPO"/spkg-install
+chmod +x "$ROOT_REPO"/spkg-install
+
+echo "Done copying root repository."
+
+tar -jcf "$ROOT_REPO".spkg "$ROOT_REPO"
+mv "$ROOT_REPO".spkg "$DESTINATION"/
+rm -rf "$ROOT_REPO"
+touch "$SPKG_INST/$ROOT_REPO"
+
+if [ ! -f "$PKG/$ROOT_REPO".spkg ]; then
+    echo "The package $ROOT_REPO.spkg wasn't created."
     exit 1
 fi
diff --git a/src/bin/sage-sdist b/src/bin/sage-sdist
--- a/src/bin/sage-sdist
+++ b/src/bin/sage-sdist
@@ -40,7 +40,7 @@ fi
 
 LD_LIBRARY_PATH="$SAGE_ROOT/local/lib:$LD_LIBRARY_PATH" && export LD_LIBRARY_PATH
 export SAGE_ROOT SAGE_VERSION
-TARGET="sage-"$1
+TARGET="sage-$1"
 
 CUR=`pwd`
 
@@ -51,76 +51,77 @@ echo "Sage version $SAGE_VERSION, released $SAGE_RELEASE_DATE" > "$SAGE_ROOT"/VE
 
 # Update Sage version file in devel/sage/sage: this is done here so
 # the banner produced below this if block is correct.
-if [ -d $SAGE_ROOT/devel/sage/sage ]; then
-   cd $SAGE_ROOT/devel/sage/sage
+if [ -d "$SAGE_ROOT"/devel/sage/sage ]; then
+   cd "$SAGE_ROOT"/devel/sage/sage
    echo '"""nodoctests"""' > version.py
    echo "version='"$SAGE_VERSION"'; date='"$SAGE_RELEASE_DATE"'" >> version.py
-   cd $SAGE_ROOT/devel/sage
+   cd "$SAGE_ROOT"/devel/sage
    python setup.py install
 fi
 
-cd $SAGE_ROOT/local/bin/
+cd "$SAGE_ROOT"/local/bin/
 echo "import sage.misc.banner; sage.misc.banner.banner()" | ./python > sage-banner
 
 cd "$CUR"
 
-cp $SAGE_ROOT/local/bin/sage-spkg $PKGDIR/base/
-cp $SAGE_ROOT/local/bin/sage-env  $PKGDIR/base/
-cp $SAGE_ROOT/local/bin/sage-make_relative $PKGDIR/base/
+cp "$SAGE_ROOT"/local/bin/sage-spkg "$PKGDIR"/base/
+cp "$SAGE_ROOT"/local/bin/sage-env "$PKGDIR"/base/
+cp "$SAGE_ROOT"/local/bin/sage-make_relative "$PKGDIR"/base/
 
 TMP="/tmp/$TARGET"
 
-if [ -d $TMP ]; then
-   rm -rf "$TMP"
+rm -rf "$TMP"
+mkdir "$TMP"
+
+# copy sage root repo over.  Cloning needs to be done in an empty
+# directory, so we do this now.  The other sage repositories are dealt
+# with later.
+cd "$SAGE_ROOT"
+
+hg diff
+hg status
+hg tag "$SAGE_VERSION"
+hg commit -m "$SAGE_VERSION"
+
+echo "Copying root repository..."
+"$SAGE_ROOT"/sage --hg clone --pull . "$TMP"
+
+if [ $? -ne 0 ]; then
+    echo "Error copying Sage root repository."
+    exit 1
 fi
 
-mkdir $TMP
+rm "$TMP"/.hg/hgrc
+echo "Done copying root repository."
 
-cd $SAGE_ROOT
-cp -LRp Makefile *.txt *.sage sage ipythonrc $TMP/
 STD=standard
-mkdir $TMP/$PKGDIR
-mkdir $TMP/$PKGDIR/$STD
 # Put VERSION.txt in a directory available for download during the
 # update process.  (See sage-update.)
 cp -p VERSION.txt $TMP/$PKGDIR/$STD/
-cp -p $PKGDIR/$STD/deps $TMP/$PKGDIR/$STD/
-cp -p $PKGDIR/$STD/libdist_filelist $TMP/$PKGDIR/$STD/
-cp -p $PKGDIR/$STD/newest_version $TMP/$PKGDIR/$STD/
-cp -pr $PKGDIR/base $TMP/$PKGDIR/
-cp -p $PKGDIR/install $TMP/$PKGDIR/
-cp -p $PKGDIR/pipestatus $TMP/$PKGDIR/
-cp -p $PKGDIR/update $TMP/$PKGDIR/
-cp -p $PKGDIR/gen_html $TMP/$PKGDIR/
-cp -p $PKGDIR/README.txt $TMP/$PKGDIR/
+cp -pr "$PKGDIR"/base "$TMP/$PKGDIR/"
 
-$SAGE_ROOT/local/bin/sage-make_devel_packages $SAGE_VERSION $SAGE_ROOT $TMP/devel
+"$SAGE_ROOT"/local/bin/sage-make_devel_packages "$SAGE_VERSION" "$SAGE_ROOT" "$TMP"/devel
 
 if [ $? -ne 0 ]; then
     echo "Error building the Sage packages."
     exit 1
 fi
 
-cp $TMP/devel/*.spkg $SAGE_ROOT/$PKGDIR/$STD/
+cp "$TMP"/devel/*.spkg "$SAGE_ROOT/$PKGDIR/$STD/"
 
-cp -p $PKGDIR/$STD/*.spkg $TMP/$PKGDIR/$STD/
-cp -p $PKGDIR/$STD/*.txt $TMP/$PKGDIR/$STD/
+cp -p "$PKGDIR/$STD"/*.spkg "$TMP/$PKGDIR/$STD/"
 
-cd $TMP/$PKGDIR/$STD
+cd "$TMP/$PKGDIR/$STD"
 rm -rf doc-* sage-* extcode-* sage_scripts-* examples-*
-mv $TMP/devel/*.spkg .
-rmdir $TMP/devel
+mv "$TMP"/devel/*.spkg .
+rmdir "$TMP"/devel
 
 cd /tmp
-tar cf $TARGET.tar $TARGET
+tar cf "$TARGET".tar "$TARGET"
 
-if [ ! -d $SAGE_ROOT/dist ]; then
-    mkdir $SAGE_ROOT/dist
-fi
+mkdir -p "$SAGE_ROOT"/dist
 
-if [ -d $SAGE_ROOT/dist/$TARGET ]; then
-    rm -rf "$SAGE_ROOT/dist/$TARGET"
-fi
+rm -rf "$SAGE_ROOT/dist/$TARGET"
 
-mv $TARGET $SAGE_ROOT/dist/
-mv $TARGET.tar $SAGE_ROOT/dist/
+mv "$TARGET" "$SAGE_ROOT"/dist/
+mv "$TARGET".tar "$SAGE_ROOT"/dist/
