[FIXUP] make sage-bdist compatible with git layout

diff --git a/src/bin/sage-bdist b/src/bin/sage-bdist
--- a/src/bin/sage-bdist
+++ b/src/bin/sage-bdist
@@ -7,86 +7,54 @@
 # Released under the GNU GPL-v2+ -- (c) William Stein
 ########################################################
 
-PKGDIR=spkg
+set -e
 
-CUR=`pwd`
+CMD="${0##*/}"
 
-if [ $# -ne 2 ]; then
-   echo "Usage: $0 <SAGE_VERSION> <SAGE_ROOT>"
-   exit 1
+die () {
+    echo >&2 -e "$@"
+    exit 1
+}
+
+usage () {
+    echo "usage: $CMD <SAGE_VERSION> [TMP_DIR]"
+}
+
+[ $# -ge 1 -a $# -le 2 ] || die `usage`
+
+[ -n "$SAGE_ROOT" ] || die "must be run from within a Sage enviroment, or with SAGE_ROOT provided"
+
+if [ "$#" -gt 1 ]; then
+    TMP_DIR="$2"
+else
+    TMP_DIR="$SAGE_ROOT/tmp"
 fi
 
 # If $1 starts with "sage-", remove this prefix
 export SAGE_VERSION=`echo "$1" | sed 's/^sage-//'`
-export SAGE_ROOT=$2
-export SAGE_SPKG_INST="$SAGE_ROOT/$PKGDIR/installed"
 
 TARGET=sage-"$SAGE_VERSION"-`uname -m`-`uname`
 TARGET=`echo $TARGET | sed 's/ //g'`   # Remove spaces
 
-# Copy all files in the bdist to $TMP
-TMP="$CUR/tmp/$TARGET"
+rm -rf "$TMP_DIR/$TARGET"
+mkdir -p "$TMP_DIR/$TARGET"
 
-rm -rf "$TMP"
-mkdir -p "$TMP"
-
-
-# Copy sage_root repository
-cd "$SAGE_ROOT"
-echo "Copying root repository..."
-hg clone --pull . "$TMP"
-if [ $? -ne 0 ]; then
-    echo "Error copying Sage root repository."
-    exit 1
-fi
-
-rm "$TMP"/.hg/hgrc
+# Clone Sage repository
+echo "Cloning Sage repository..."
+git clone "$SAGE_ROOT" "$TMP_DIR/$TARGET"
 
 # Copy VERSION.txt (which is untracked)
-cp -p VERSION.txt "$TMP/"
+cp -p VERSION.txt "$TMP_DIR/$TARGET"
 
-# Make data symlink for backwards compatibility
-ln -s local/share "$TMP/data"
-
-echo "Done copying root repository."
+echo "Done cloning Sage repository."
 
 echo "Copying files over to tmp directory"
 # We use "tar" to copy files for portability,
 # see http://trac.sagemath.org/sage_trac/ticket/14236
-tar cf - local | ( cd "$TMP" && tar xf - )
+tar cf - local | ( cd "$TMP_DIR/$TARGET" && tar xf - )
+tar cf - src/doc/output | ( cd "$TMP_DIR/$TARGET" && tar xf - )
 
-# Copy devel/ subdirectories.  We only copy the currently active
-# branches, which become the default branches in the bdisted tarball.
-if [ -d devel/sage ]; then
-    echo "Copying Sage library"
-    mkdir -p "$TMP/devel/sage-main"
-    ln -s sage-main "$TMP/devel/sage"
-    ( cd devel/sage && tar cf - . ) | ( cd "$TMP/devel/sage-main" && tar xf - )
-fi
-
-if [ -d devel/sagenb ]; then
-    echo "Copying Sage Notebook"
-    mkdir -p "$TMP/devel/sagenb-main"
-    ln -s sagenb-main "$TMP/devel/sagenb"
-    ( cd devel/sagenb && tar cf - . ) | ( cd "$TMP/devel/sagenb-main" && tar xf - )
-fi
-
-if [ -d devel/ext ]; then
-    echo "Copying Extcode"
-    mkdir -p "$TMP/devel/ext-main"
-    ln -s ext-main "$TMP/devel/ext"
-    ( cd devel/ext && tar cf - . ) | ( cd "$TMP/devel/ext-main" && tar xf - )
-fi
-
-
-if [ -d "$PKGDIR" ]; then
-    cp -pR "$SAGE_SPKG_INST" "$TMP/$PKGDIR/"
-    # sage --sdist uses the following file to detect if it's working
-    # with a "bdisted" copy.
-    touch $TMP/$PKGDIR/standard/.from_bdist
-fi
-
-cd "$CUR"/tmp/
+cd "$TMP_DIR"
 if [ "$UNAME" = "Darwin" ]; then
     cd "$TARGET"
     # Move everything into a subdirectory sage, but first name it
@@ -94,7 +62,7 @@ if [ "$UNAME" = "Darwin" ]; then
     mkdir .sage_tmp
     mv * .hg* .sage_tmp
     mv .sage_tmp sage
-    cp -p sage/local/bin/sage-README-osx.txt README.txt
+    cp -p "$SAGE_LOCAL"/bin/sage-README-osx.txt README.txt
 
     if [ "$SAGE_APP_BUNDLE" = "yes" ]; then
 
@@ -111,20 +79,15 @@ if [ "$UNAME" = "Darwin" ]; then
         # Note that we don't have to build this part with the same
         # compiler as everything else, and in fact it causes problems
         # to do so.
-        (cd "$SAGE_EXTCODE/sage/ext/mac-app/" && \
+        (cd "$SAGE_SRC/mac-app/" && \
             unset CC LD && \
             xcodebuild -target 'Sage' -configuration "$CONFIGURATION" \
             ARCHES="$(uname -m)" \
-            $SET_SDKROOT)
-
-        if [ $? -ne 0 ]; then
-            echo "Failed to build Sage.app."
-            echo "If you don't wish to build Sage.app set SAGE_APP_BUNDLE=no"
-            exit 1
-        fi
+            $SET_SDKROOT) || 
+                die "Failed to build Sage.app.\nIf you don't wish to build Sage.app set SAGE_APP_BUNDLE=no"
 
         echo 'Copying Sage.app'
-        cp -pRL "$SAGE_EXTCODE/sage/ext/mac-app/build/$CONFIGURATION/Sage.app" ./Sage.app
+        cp -pRL "$SAGE_SRC/mac-app/build/$CONFIGURATION/Sage.app" ./Sage.app
         # Info.plist is a binary plist, so convert it for processing with sed.
         # I would just change it to be an xml plist, but xcode changes it back.
         plutil -convert xml1 ./Sage.app/Contents/Info.plist
@@ -141,7 +104,7 @@ if [ "$UNAME" = "Darwin" ]; then
     fi
 
     # Go back to the right directory for later copying
-    cd "$CUR"/tmp/
+    cd "$TMP_DIR"
     if [ "$SAGE_APP_DMG" != "no" ]; then
         echo "Creating $TARGET.dmg"
         echo "(If you don't wish to create a disk image please set SAGE_APP_DMG=no)"
