[project @ improvements (example "sage -pyrex")]

diff --git a/src/bin/sage-upgrade b/src/bin/sage-upgrade
--- a/src/bin/sage-upgrade
+++ b/src/bin/sage-upgrade
@@ -1,5 +1,33 @@
 #!/bin/sh
 
 sage-update
+
+if [ $? -ne 0 ]; then
+    echo "Error getting new packages!"
+    exit 1
+fi
+
+cd $SAGE_ROOT
+make clean
+
 cd $SAGE_ROOT/spkg/
+
+
+
 ./install
+
+if [ $? -ne 0 ]; then
+    echo "Error installing SAGE!"
+    exit 1
+fi
+
+echo ""
+echo " ***************************************************"
+echo "The upgrade appears to have succeeded!"
+echo "Now running 'make clean' to delete temporary build files "
+echo "that were created during the ugprade."
+echo " ***************************************************"
+echo ""
+
+cd $SAGE_ROOT
+make clean
