Use SAGE_SCRIPTS_DIR to source sage-env-config

diff --git a/src/bin/sage-env b/src/bin/sage-env
--- a/src/bin/sage-env
+++ b/src/bin/sage-env
@@ -186,40 +186,20 @@ export SAGE_ENV_SOURCED=$SAGE_ENV_VERSION
 
 export SAGE_ROOT="$NEW_SAGE_ROOT"
 
-# SAGE_LOCAL is the installation prefix and can be customized by using ./configure --prefix
-#
 
-## Find the directory of this script (sage-env).
-## Note that it is *sourced* by various other scripts,
-## which is why `dirname $0` would not work ($0 is /bin/bash).
-## Instead we use a solution from
-## http://stackoverflow.com/questions/59895/can-a-bash-script-tell-which-directory-it-is-stored-in
-## It uses a bash feature: BASH_SOURCE[0] gives the source of
-## the "currently running function". See
-## https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html
-## (entries for FUNCNAME and BASH_SOURCE).
-SAGE_ENV_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-if [ $? -ne 0 ]; then
-    echo >&2 "sage-env: Error: Could not find the directory of sage-env."
-    return 1
-fi
-. "$SAGE_ENV_DIR"/sage-env-config
-if [ $? -ne 0 ]; then
-    echo >&2 "sage-env: Error: $SAGE_ENV_DIR/sage-env-config could not be read."
-    return 1
-fi
-
-# sage-env must know where the Sage's script files are
+# sage-env must know where the Sage's script files are.
+# Note that SAGE_SCRIPTS_DIR is only used here, so it does not need to
+# be exported.
 if [ -z "$SAGE_SCRIPTS_DIR" ]; then
-    if [ -f "$SAGE_LOCAL/bin/sage-env" ]; then
+    if [ -n "$SAGE_LOCAL" ] && [ -f "$SAGE_LOCAL/bin/sage-env-config" ]; then
         SAGE_SCRIPTS_DIR="$SAGE_LOCAL/bin"
-    elif [ -f "$SAGE_ROOT/src/bin/sage-env" ]; then
+    elif [ -f "$SAGE_ROOT/src/bin/sage-env-config" ]; then
         SAGE_SCRIPTS_DIR="$SAGE_ROOT/src/bin"
     else
-        echo >&2 "Error: You must set the SAGE_SCRIPTS_DIR environment variable to run this"
+        echo >&2 "Error: You must set either the SAGE_LOCAL or SAGE_SCRIPTS_DIR environment variable to run this"
         return 1
     fi
-elif [ ! -f "$SAGE_SCRIPTS_DIR/sage-env" ]; then
+elif [ ! -f "$SAGE_SCRIPTS_DIR/sage-env-config" ]; then
     echo >&2 "Error: SAGE_SCRIPTS_DIR is set to a bad value:"
     echo >&2 "SAGE_SCRIPTS_DIR=$SAGE_SCRIPTS_DIR"
     echo >&2 "You must correct it or erase it and rerun this script"
@@ -228,6 +208,14 @@ fi
 
 # Make SAGE_SCRIPTS_DIR absolute
 export SAGE_SCRIPTS_DIR="`cd "$SAGE_SCRIPTS_DIR" && pwd -P`"
+
+# Set environment variables (like SAGE_LOCAL) depending on ./configure
+. "$SAGE_SCRIPTS_DIR/sage-env-config"
+if [ $? -ne 0 ]; then
+    echo >&2 "Error: failed to source $SAGE_SCRIPTS_DIR/sage-env-config"
+    return 1
+fi
+
 
 # Call with: contains_spaces X${VAR}X
 # i.e., WITHOUT quotes but some character(s) around the environment variable to test.
