new version.

diff --git a/src/bin/sage-make_devel_packages b/src/bin/sage-make_devel_packages
--- a/src/bin/sage-make_devel_packages
+++ b/src/bin/sage-make_devel_packages
@@ -103,6 +103,33 @@ if [ ! -f $PKG/extcode-$SAGE_VERSION.spkg ]; then
     exit 1
 fi
 
+# NEW SAGE C LIBRARY CODE PACKAGE
+if [ -d "$SAGE_ROOT"/devel/c_lib ]; then
+   cd "$SAGE_ROOT"/devel/c_lib
+   chmod +x configure
+   hg diff
+   hg status
+   hg commit
+   if [ $? -ne 0 ]; then
+       echo "Error building the extcode package"
+       exit 1
+   fi
+   NAME=sage_c_lib-$SAGE_VERSION
+   D="$DESTINATION"/"$NAME"
+   if [ -d "$D" ]; then
+       rm -rf "$D"
+   fi
+   cp -r "$SAGE_ROOT"/devel/c_lib "$D"
+   cd "$DESTINATION"
+   sage -pkg $NAME
+   rm -rf "$D"
+fi
+
+
+if [ ! -f $PKG/extcode-$SAGE_VERSION.spkg ]; then
+    echo "The package extcode-$SAGE_VERSION.spkg wasn't created."
+    exit 1
+fi
 
 # NEW SAGE EXAMPLE CODE PACKAGE
 if [ -d $SAGE_ROOT/examples ]; then
