build/bin/sage-spkg, src/bin/sage: Remove support for installing old-style SPKGs

diff --git a/src/bin/sage b/src/bin/sage
--- a/src/bin/sage
+++ b/src/bin/sage
@@ -167,9 +167,7 @@ usage_advanced() {
     echo "                           -n -- reply no to prompts about experimental"
     echo "                                 and old-style packages"
     echo "  -p [opts] [packages]-- install the given Sage packages, without dependency"
-    echo "                         checking and with support for old-style spkgs."
-    echo "                         Options are -c, -d and -s with the same meaning as"
-    echo "                         for the -i command"
+    echo "                         checking. Options are the same as for the -i command."
     echo "  -info [packages]    -- print the SPKG.txt or SPKG.rst of the given packages,"
     echo "                         and some additional information."
     echo "  --location          -- if needed, fix paths to make Sage relocatable"
@@ -385,7 +383,7 @@ if [ "$1" = '-i' ]; then
         # See https://trac.sagemath.org/ticket/25078
         if ! echo "$ALL_TARGETS" | grep "^${PKG}$" >/dev/null; then
             echo >&2 "Error: package '$PKG' not found"
-            echo >&2 "Note: if it is an old-style package, use -p instead of -i to install it"
+            echo >&2 "Note: if it is an old-style package, installing these is no longer supported"
             exit 1
         fi
         $MAKE SAGE_SPKG="sage-spkg $INSTALL_OPTIONS" "$PKG"
@@ -1110,7 +1108,8 @@ fi
 if [ $# -ge 1 ]; then
     T=`echo "$1" | sed -e "s/.*\.//"`
     if [ "$T" = "spkg" ]; then
-        install "$@"
+        echo "Error: Installing old-style SPKGs is no longer supported."
+        exit 1
     fi
     sage_setup
     unset TERM  # See Trac #12263
