new version

diff --git a/src/bin/sage-sdist b/src/bin/sage-sdist
--- a/src/bin/sage-sdist
+++ b/src/bin/sage-sdist
@@ -62,6 +62,11 @@ cp -p $PKGDIR/gen_html $TMP/$PKGDIR/
 
 $SAGE_ROOT/local/bin/sage-make_devel_packages $SAGE_VERSION $SAGE_ROOT $TMP/devel
 
+if [ $? -ne 0 ]; then
+    echo "Error building the SAGE packages."
+    exit 1
+fi
+
 cp $TMP/devel/*.spkg $SAGE_ROOT/$PKGDIR/$STD/
 
 cp -p $PKGDIR/$STD/*.spkg $TMP/$PKGDIR/$STD/
