Make creation of development packages more robust.

diff --git a/src/bin/sage-make_devel_packages b/src/bin/sage-make_devel_packages
--- a/src/bin/sage-make_devel_packages
+++ b/src/bin/sage-make_devel_packages
@@ -31,48 +31,105 @@ fi
 
 cd $DESTINATION
 DESTINATION=`pwd`
+PKG=$DESTINATION
 
 # NEW DOCUMENTATION PACKAGE
-if [ -d $SAGE_ROOT/devel/doc ]; then
-   cd $SAGE_ROOT/devel/doc
+if [ -d $SAGE_ROOT/devel/doc-main ]; then
+   cd $SAGE_ROOT/devel/doc-main
+   ./sage-push
    chmod +x scripts/spkg-dist
    scripts/spkg-dist $SAGE_VERSION
+   if [ $? -ne 0 ]; then
+       echo "Error building the documentation package"
+       exit 1
+   fi
    mv doc-$SAGE_VERSION.spkg $DESTINATION/
    touch $SPKG_INST/doc-$SAGE_VERSION
 fi
 
+
+if [ ! -f $PKG/doc-$SAGE_VERSION.spkg ]; then
+    echo "The package doc-$SAGE_VERSION.spkg wasn't created."
+    exit 1
+fi
+
 # NEW SAGE SOURCE PACKAGE
-if [ -d $SAGE_ROOT/devel/sage ]; then
-   cd $SAGE_ROOT/devel/sage
+if [ -d $SAGE_ROOT/devel/sage-main ]; then
+   cd $SAGE_ROOT/devel/sage-main
+   ./sage-push
    chmod +x spkg-dist
    ./spkg-dist $SAGE_VERSION $SAGE_ROOT
+   if [ $? -ne 0 ]; then
+       echo "Error building the sage source code package"
+       exit 1
+   fi
    mv dist/sage-$SAGE_VERSION.spkg $DESTINATION/
    touch $SPKG_INST/sage-$SAGE_VERSION
+fi
+
+if [ ! -f $PKG/sage-$SAGE_VERSION.spkg ]; then
+    echo "The package sage-$SAGE_VERSION.spkg wasn't created."
+    exit 1
 fi
 
 # NEW SAGE EXTERNAL CODE PACKAGE
 if [ -d $SAGE_ROOT/data/extcode ]; then
    cd $SAGE_ROOT/data/extcode
+   ./sage-push
    chmod +x spkg-dist
    ./spkg-dist $SAGE_VERSION $SAGE_ROOT
+   if [ $? -ne 0 ]; then
+       echo "Error building the extcode package"
+       exit 1
+   fi
    mv extcode-$SAGE_VERSION.spkg $DESTINATION/
    touch $SPKG_INST/extcode-$SAGE_VERSION
 fi
 
+
+if [ ! -f $PKG/extcode-$SAGE_VERSION.spkg ]; then
+    echo "The package extcode-$SAGE_VERSION.spkg wasn't created."
+    exit 1
+fi
+
+
 # NEW SAGE EXAMPLE CODE PACKAGE
 if [ -d $SAGE_ROOT/examples ]; then
-   cd $SAGE_ROOT
+   cd $SAGE_ROOT/examples
+   ./sage-push
+   cd ..
    rm -rf examples-$SAGE_VERSION
    cp -pr examples examples-$SAGE_VERSION
    sage -pkg examples-$SAGE_VERSION
+   if [ $? -ne 0 ]; then
+       echo "Error building examples package"
+       exit 1
+   fi
    mv examples-$SAGE_VERSION.spkg $DESTINATION/
    rm -rf examples-$SAGE_VERSION
    touch $SPKG_INST/examples-$SAGE_VERSION
 fi
 
+if [ ! -f $PKG/examples-$SAGE_VERSION.spkg ]; then
+    echo "The package examples-$SAGE_VERSION.spkg wasn't created."
+    exit 1
+fi
+
+
+#################################
+
+
 # NEW SAGE SCRIPTS PACKAGE
 SCRIPTS=sage_scripts-$SAGE_VERSION
 cd $SAGE_ROOT/local/bin/
+
+./sage-push
+
+if [ $? -ne 0 ]; then
+    echo "Error pushing scripts repository."
+    exit 1
+fi
+
 rm -rf $SCRIPTS
 mkdir $SCRIPTS
 cp -pr sage-* $SCRIPTS/
@@ -104,3 +161,7 @@ mv $SCRIPTS.spkg $DESTINATION/
 rm -rf $SCRIPTS
 touch $SPKG_INST/sage_scripts-$SAGE_VERSION
 
+if [ ! -f $PKG/sage_scripts-$SAGE_VERSION.spkg ]; then
+    echo "The package sage_scripts-$SAGE_VERSION.spkg wasn't created."
+    exit 1
+fi
