Don't source sage-env before sage-upgrade

diff --git a/src/bin/sage b/src/bin/sage
--- a/src/bin/sage
+++ b/src/bin/sage
@@ -249,10 +249,21 @@ if [ "$1" = '--nodotsage' ]; then
     exit $status
 fi
 
-# Make sure this doesn't produce output (in case we use this in scripts).
+# Check for '--upgrade' before sourcing sage-env: the top-level "make"
+# should be run outside of the Sage shell, see #15517.
+if [ "$1" = '-upgrade' -o "$1" = "--upgrade" ]; then
+    shift
+    cd "$SAGE_ROOT"
+    exec local/bin/sage-upgrade "$@"
+fi
+
+
+# Source sage-env ($0 is the name of this "sage" script, so we can just
+# append -env to that). We redirect stdout to stderr, which is safer
+# for scripts.
 . "$0-env" >&2
 if [ $? -ne 0 ]; then
-    echo >&2 "Error setting environment variables by sourcing '$SAGE_ROOT/spkg/bin/sage-env';"
+    echo >&2 "Error setting environment variables by sourcing '$0-env';"
     echo >&2 "possibly contact sage-devel (see http://groups.google.com/group/sage-devel)."
     exit 1
 fi
@@ -861,23 +872,6 @@ if [ "$1" = '-bdist' -o "$1" = "--bdist" ]; then
     maybe_sage_location
     shift
     exec sage-bdist "$@"
-fi
-
-#if [ "$1" = '-update' ]; then
-#    sage-update
-#    exit $?
-#fi
-
-#if [ "$1" = '-update-build' -o "$1" = "--update-build" ]; then
-#    sage-update-build
-#    sage-update-build
-#    exit $?
-#fi
-
-if [ "$1" = '-upgrade' -o "$1" = "--upgrade" ]; then
-    shift
-    sage-upgrade "$@"
-    exit $?
 fi
 
 if [ "$1" = "-docbuild" -o "$1" = "--docbuild" ]; then
