[FIXUP] make sage-env and basic startup not depend on the spkg directory

diff --git a/build/install b/build/install
--- a/build/install
+++ b/build/install
@@ -4,15 +4,17 @@
 # Set various environment variables
 ########################################################################
 
-# Assume current directory is SAGE_ROOT/spkg
+# Assume current directory is SAGE_ROOT/build
 SAGE_ROOT=`cd .. && pwd -P`
+SAGE_SRC="$SAGE_ROOT/src"
 SAGE_LOCAL="$SAGE_ROOT/local"
 SAGE_SHARE="$SAGE_LOCAL/share"
+SAGE_EXTCODE="$SAGE_SHARE/sage/ext"
 SAGE_LOGS="$SAGE_ROOT/logs/pkgs"
-SAGE_SPKG_INST="$SAGE_ROOT/spkg/installed"
-PATH="$SAGE_ROOT/spkg/bin:$SAGE_LOCAL/bin:$PATH"
+SAGE_SPKG_INST="$SAGE_LOCAL/var/lib/sage/installed"
+PATH="$SAGE_ROOT/src/bin:$SAGE_LOCAL/bin:$PATH"
 PYTHONPATH="$SAGE_LOCAL"
-export SAGE_ROOT SAGE_LOCAL SAGE_LOGS SAGE_SPKG_INST PATH PYTHONPATH
+export SAGE_ROOT SAGE_SRC SAGE_LOCAL SAGE_LOGS SAGE_SPKG_INST PATH PYTHONPATH
 
 # Storing the start time of the build process. The time is stored in
 # seconds since 1970-01-01 in a hidden file called
@@ -39,15 +41,8 @@ EOF
     exit 2
 fi
 
-# If spkg/bin/sage-env doesn't exist, we are surely upgrading (sage-env
-# was moved to spkg/bin in sage-5.0).  Manually set SAGE_UPGRADING=yes,
-# as old versions of sage-upgrade didn't do this.
-if [ ! -f "$SAGE_ROOT/spkg/bin/sage-env" ]; then
-    SAGE_UPGRADING=yes
-fi
-
 if [ "$SAGE_UPGRADING" = yes ]; then
-    # We're doing an upgrade. Let spkg/Makefile call sage-spkg with
+    # We're doing an upgrade. Let build/Makefile call sage-spkg with
     # "-f" to force rebuilding dependent packages, too:
     export SAGE_SPKG_OPTS="-f"
 
@@ -135,7 +130,7 @@ sleep 5
 fi
 
 # Determine various compilers.  These variables should not be exported,
-# they are only used in this spkg/install script to determine whether to
+# they are only used in this build/install script to determine whether to
 # install GCC.  The "real" $CC, $CXX,... variables for building Sage are
 # set in sage-env.
 
@@ -278,7 +273,7 @@ cat >"$SAGE_LOCAL/bin/sage_fortran" <<EOF
 #!/bin/sh
 
 if [ "x\$FC" = x ]; then
-    # Default value determined in spkg/install
+    # Default value determined in build/install
     myFC='${FC:-gfortran}'
 else
     myFC="\$FC"
@@ -301,7 +296,7 @@ if [ -f "$SAGE_FORTRAN_LIB" ]; then
 fi
 
 ###############################################################################
-# Create $SAGE_ROOT/spkg/Makefile starting from spkg/standard/deps
+# Create $SAGE_ROOT/build/Makefile starting from build/deps
 ###############################################################################
 
 exec 3>Makefile
@@ -309,7 +304,7 @@ exec 3>Makefile
 cat >&3 <<EOF
 #==============================================================================
 # This file has been automatically generated by
-#   $SAGE_ROOT/spkg/install
+#   $SAGE_ROOT/build/install
 # You should not edit it by hand
 #==============================================================================
 
@@ -345,25 +340,17 @@ newest_version_base() {
 }
 
 # Usage: newest_version $pkg
-# Print version number of latest (according to modification time)
-# standard or optional package $pkg
+# Print version number of latest standard package $pkg
 newest_version() {
     PKG=$1
-    # First find the most recent spkg.  We also look for *optional*
-    # packages since downloaded packages arrive in spkg/optional.
-    # As a fallback, we also look at the latest installed package.
-    for FILE in `{ ls -1t standard/$PKG-*.spkg optional/$PKG-*.spkg; ls -1t "$SAGE_SPKG_INST"/$PKG-*; } 2>/dev/null`
-    do
-        ANS=`echo "$FILE" | sed 's|.*/||; s|\.spkg||'`
-        if [ -n "$ANS" ]; then
-            echo "$ANS"
-            return 0
-        fi
-    done
-
-    echo >&2 "Cannot determine latest version of $PKG."
-    echo "$PKG"
-    return 1
+    if [ -f "$SAGE_ROOT/build/pkgs/$PKG/package-version.txt" ]; then
+        echo -n $PKG-
+        cat "$SAGE_ROOT/build/pkgs/$PKG/package-version.txt"
+    else
+        echo >&2 "Cannot determine latest version of $PKG."
+        echo "$PKG"
+        return 1
+    fi
 }
 
 cat >&3 <<EOF
@@ -386,7 +373,6 @@ ECL=`newest_version ecl`
 ECLIB=`newest_version eclib`
 ECM=`newest_version ecm`
 ELLIPTIC_CURVES=`newest_version elliptic_curves`
-EXTCODE=`newest_version extcode`
 FFLASFFPACK=`newest_version fflas_ffpack`
 FLINT=`newest_version flint`
 FLINTQS=`newest_version flintqs`
@@ -442,11 +428,8 @@ RPY=`newest_version rpy2`
 RATPOINTS=`newest_version ratpoints`
 READLINE=`newest_version readline`
 RUBIKS=`newest_version rubiks`
-SAGE=`newest_version sage`
 SAGENB=`newest_version sagenb`
 SAGETEX=`newest_version sagetex`
-SAGE_ROOT_REPO=`newest_version sage_root`
-SAGE_SCRIPTS=`newest_version sage_scripts`
 SCIPY=`newest_version scipy`
 SCONS=`newest_version scons`
 SETUPTOOLS=`newest_version setuptools`
@@ -480,17 +463,49 @@ if [ "$need_to_install_gcc" == yes ]; then
 fi
 echo >&3
 
-# Copy spkg/standard/deps
+echo >&3 'SCRIPT_SOURCES = \'
+for file in "$SAGE_SRC/bin/"*; do
+    echo >&3 "                 $file \\"
+done
+echo >&3
+echo >&3 'SCRIPT_TARGETS = \'
+for file in "$SAGE_SRC/bin/"*; do
+    echo >&3 "                 ${SAGE_LOCAL}${file#$SAGE_SRC} \\"
+done
+echo >&3
+echo >&3 'EXTCODE_SOURCES = \'
+for file in `find "$SAGE_SRC"/ext -type f`; do
+    echo >&3 "                  $file \\"
+done
+echo >&3
+echo >&3 'EXTCODE_TARGETS = \'
+for file in `find "$SAGE_SRC"/ext -type f`; do
+    echo >&3 "                  ${SAGE_EXTCODE}${file#$SAGE_SRC/ext} \\"
+done
+echo >&3
+
+cat >&3 <<EOF
+# don't just use \`install\` since we don't want to change permissions
+$SAGE_LOCAL/bin/%: $SAGE_SRC/bin/%
+	cp \$< \$@
+
+# don't just use \`install -D\` since we don't want to change permissions
+$SAGE_EXTCODE/%: $SAGE_SRC/ext/%
+	@mkdir -p "\$(@D)"
+	cp \$< \$@
+EOF
+
+# Copy build/deps
 cat >&3 <<EOF
 
 #==============================================================================
 # What follows now is a copy of
-#   $SAGE_ROOT/spkg/standard/deps
+#   $SAGE_ROOT/build/deps
 #==============================================================================
 
 EOF
 
-cat standard/deps >&3
+cat "$SAGE_ROOT/build/deps" >&3
 
 # Close the Makefile
 exec 3>&-
@@ -507,16 +522,9 @@ fi
 # * If "make" doesn't understand the -q option (although we require
 #   GNU make, which supports it), it should exit with a non-zero status
 #   which is not a problem.
-# * Only do this check if spkg/bin/sage-spkg exists, as that means we
-#   are running sage-5.x and sage-spkg understands MAKEFLAGS.
-#   If we are upgrading, we might have a pre-4.8 version of sage-spkg
-#   which doesn't check MAKEFLAGS.
-#   See Trac #12248 and also #12016.
-if [ -f "$SAGE_ROOT/spkg/bin/sage-spkg" ]; then
-    if $MAKE -q "$@" >/dev/null 2>/dev/null; then
-        echo "Nothing to (re)build / all up-to-date."
-        exit 0
-    fi
+if $MAKE -q "$@" >/dev/null 2>/dev/null; then
+    echo "Nothing to (re)build / all up-to-date."
+    exit 0
 fi
 
 # Dump environment for debugging purposes:
