Trac #10492: Change newest_version to be a function inside spkg/install

diff --git a/build/install b/build/install
--- a/build/install
+++ b/build/install
@@ -60,350 +60,201 @@ if [ "$SAGE_UPGRADING" = yes ]; then
 fi
 
 ###############################################################################
-# Setup environment variables pointing to the newest versions
-# of the base packages:
+# Create $SAGE_ROOT/spkg/Makefile starting from spkg/standard/deps
 ###############################################################################
-newest="$PKGDIR/newest_version -base "
 
-SAGE_BZIP2=`$newest bzip2`
-export SAGE_BZIP2
+exec 3>Makefile
 
-DIR=`$newest dir`
-export DIR
+cat >&3 <<EOF
+#==============================================================================
+# This file has been automatically generated by
+#   $SAGE_ROOT/spkg/install
+# You should not edit it by hand
+#==============================================================================
 
-PREREQ=`$newest prereq`
-export PREREQ
-
-###############################################################################
-# Setup environment variables pointing to the newest versions
-# of the standard packages:
-###############################################################################
-newest="$PKGDIR/newest_version"
-
-ATLAS=`$newest atlas`
-export ATLAS
-
-BLAS=`$newest blas`
-export BLAS
-
-BOEHM_GC=`$newest boehm_gc`
-export BOEHM_GC
-
-BOOST_CROPPED=`$newest boost-cropped`
-export BOOST_CROPPED
-
-CEPHES=`$newest cephes`
-export CEPHES
-
-CLIQUER=`$newest cliquer`
-export CLIQUER
-
-CDDLIB=`$newest cddlib`
-export CDDLIB
-
-PPL=`$newest ppl`
-export PPL
-
-ECL=`$newest ecl`
-export ECL
-
-CONWAY=`$newest conway_polynomials`
-if [ $? -ne 0 ]; then
-    echo "Error determining package name using spkg/standard/newest_version script."
-    exit 1
-fi
-export CONWAY
-
-ECLIB=`$newest eclib`
-export ECLIB
-
-ELLIPTIC_CURVES=`$newest elliptic_curves`
-export ELLIPTIC_CURVES
-
-CVXOPT=`$newest cvxopt`
-export CVXOPT
-
-DOCUTILS=`$newest docutils`
-export DOCUTILS
-
-ECM=`$newest ecm`
-export ECM
-
-EXTCODE=`$newest extcode`
-export EXTCODE
-
-F2C=`$newest f2c`
-export F2C
-
-GLPK=`$newest glpk`
-export GLPK
-
-ICONV=`$newest iconv`
-export ICONV
-
-#############
-# This is all for GNUtls crypto
-LIBGCRYPT=`$newest libgcrypt`
-export LIBGCRYPT
-
-OPENCDK=`$newest opencdk`
-export OPENCDK
-
-GNUTLS=`$newest gnutls`
-export GNUTLS
-
-LIBGPG_ERROR=`$newest libgpg_error`
-export LIBGPG_ERROR
-
-PYGMENTS=`$newest pygments`
-export PYGMENTS
-
-PYTHON_GNUTLS=`$newest python_gnutls`
-export PYTHON_GNUTLS
-############# end gnutls crypto
-
-PIL=`$newest pil`
-export PIL
-
-PATCH=`$newest patch`
-export PATCH
-
-LIBM4RI=`$newest libm4ri`
-export LIBM4RI
-
-LIBM4RIE=`$newest libm4rie`
-export LIBM4RIE
-
-FORTRAN=`$newest fortran`
-export FORTRAN
-
-FPLLL=`$newest libfplll`
-export FPLLL
-
-FREETYPE=`$newest freetype`
-export FREETYPE
-
-GAP=`$newest gap`
-export GAP
-
-G2RED=`$newest genus2reduction`
-export G2RED
-
-GD=`$newest gd`
-export GD
-
-GDMODULE=`$newest gdmodule`
-export GDMODULE
-
-GFAN=`$newest gfan`
-export GFAN
-
-GIVARO=`$newest givaro`
-export GIVARO
-
-MPIR=`$newest mpir`
-export MPIR
-
-GRAPHS=`$newest graphs`
-export GRAPHS
-
-GSL=`$newest gsl`
-export GSL
-
-IPYTHON=`$newest ipython`
-export IPYTHON
-
-LAPACK=`$newest lapack`
-export LAPACK
-
-LCALC=`$newest lcalc`
-export LCALC
-
-LIBPNG=`$newest libpng`
-export LIBPNG
-
-LINBOX=`$newest linbox`
-export LINBOX
-
-IML=`$newest iml`
-export IML
-
-JINJA2=`$newest jinja2`
-export JINJA2
-
-MATPLOTLIB=`$newest matplotlib`
-export MATPLOTLIB
-
-MAXIMA=`$newest maxima`
-export MAXIMA
-
-MERCURIAL=`$newest mercurial`
-export MERCURIAL
-
-MPFI=`$newest mpfi`
-export MPFI
-
-MOIN=`$newest moin`
-export MOIN
-
-MPFR=`$newest mpfr`
-export MPFR
-
-MPMATH=`$newest mpmath`
-export MPMATH
-
-NETWORKX=`$newest networkx`
-export NETWORKX
-
-NUMPY=`$newest numpy`
-export NUMPY
-
-NTL=`$newest ntl`
-export NTL
-
-#OPENSSL=`$newest openssl`
-#export OPENSSL
-
-#PYOPENSSL=`$newest pyopenssl`
-#export PYOPENSSL
-
-PALP=`$newest palp`
-export PALP
-
-PARI=`$newest pari`
-export PARI
-
-PEXPECT=`$newest pexpect`
-export PEXPECT
-
-POLYBORI=`$newest polybori`
-export POLYBORI
-
-PYNAC=`$newest pynac`
-export PYNAC
-
-CYTHON=`$newest cython`
-export CYTHON
-
-RATPOINTS=`$newest ratpoints`
-export RATPOINTS
-
-SAGENB=`$newest sagenb`
-export SAGENB
-
-SAGETEX=`$newest sagetex`
-export SAGETEX
-
-SPHINX=`$newest sphinx`
-export SPHINX
-
-SQLALCHEMY=`$newest sqlalchemy`
-export SQLALCHEMY
-
-SQLITE=`$newest sqlite`
-export SQLITE
-
-FLINTQS=`$newest flintqs`
-export FLINTQS
-
-FLINT=`$newest flint`
-export FLINT
-
-POLYTOPES_DB=`$newest polytopes_db`
-export POLYTOPES_DB
-
-PYCRYPTO=`$newest pycrypto`
-export PYCRYPTO
-
-PYTHON=`$newest python`
-export PYTHON
-
-R=`$newest r`
-export R
-
-# Needed when #9906 gets merged:
-# RPY=`$newest rpy2`
-# export RPY
-
-READLINE=`$newest readline`
-export READLINE
-
-RUBIKS=`$newest rubiks`
-export RUBIKS
-
-SAGE=`$newest sage`
-export SAGE
-
-SAGE_ROOT_REPO=`$newest sage_root`
-export SAGE_ROOT_REPO
-
-SAGE_SCRIPTS=`$newest sage_scripts`
-export SAGE_SCRIPTS
-
-SCIPY=`$newest scipy`
-export SCIPY
-
-TACHYON=`$newest tachyon`
-export TACHYON
-
-TWISTED=`$newest twisted`
-export TWISTED
-
-SCONS=`$newest scons`
-export SCONS
-
-SETUPTOOLS=`$newest setuptools`
-export SETUPTOOLS
-
-SINGULAR=`$newest singular`
-export SINGULAR
-
-SYMPOW=`$newest sympow`
-export SYMPOW
-
-SYMPY=`$newest sympy`
-export SYMPY
-
-SYMMETRICA=`$newest symmetrica`
-export SYMMETRICA
-
-TERMCAP=`$newest termcap`
-export TERMCAP
-
-ZLIB=`$newest zlib`
-export ZLIB
-
-ZODB=`$newest zodb3`
-export ZODB
-
-ZNPOLY=`$newest zn_poly`
-export ZNPOLY
+EOF
 
 # If the user (or the Makefile) has set SAGE_PARALLEL_SPKG_BUILD=no,
-# then turn off parallel building by writing .NOTPARALLEL to
-# spkg/standard/parallel_make.cfg.  Otherwise clear that file.
-if [[ ${SAGE_PARALLEL_SPKG_BUILD:-yes} = no ]]; then
-    # Disable just building multiple packages at the same time; individual
-    # spkgs still get built in parallel if they support it and '--jobs'
-    # in $MAKE is greater than one (and at all specified):
-    echo ".NOTPARALLEL:" > "$SAGE_ROOT"/spkg/parallel_make.cfg
-else
-    # Create an (almost) empty file, s.t. including it from spkg/standard/deps
-    # doesn't raise an error, thereby also invalidating any previous setting:
-    echo > "$SAGE_ROOT"/spkg/parallel_make.cfg
+# then turn off parallel building: disable just building multiple
+# packages at the same time.   Individual packages can still be built
+# in parallel by specifying '-j' in $MAKE.
+if [ "${SAGE_PARALLEL_SPKG_BUILD:-yes}" = no ]; then
+    echo ".NOTPARALLEL:" >&3
+    echo "" >&3
 fi
+
+# Usage: newest_version_base $pkg
+# Print version number of latest (according to modification time)
+# base package $pkg
+newest_version_base() {
+    PKG=$1
+    # As a fallback, we also look at the latest installed package.
+    for FILE in `{ ls -1t base/$PKG-*-install; ls -1t installed/$PKG-*; } 2>/dev/null`
+    do
+        ANS=`echo "$FILE" | sed 's|.*/||; s|-install||'`
+        if [ -n "$ANS" ]; then
+            echo "$ANS"
+            return 0
+        fi
+    done
+
+    echo >&2 "Cannot determine latest version of $PKG."
+    echo "$PKG"
+    return 1
+}
+
+# Usage: newest_version $pkg
+# Print version number of latest (according to modification time)
+# standard or optional package $pkg
+newest_version() {
+    PKG=$1
+    # First find the most recent spkg.  We also look for *optional*
+    # packages since downloaded packages arrive in spkg/optional.
+    # As a fallback, we also look at the latest installed package.
+    for FILE in `{ ls -1t standard/$PKG-*.spkg optional/$PKG-*.spkg; ls -1t installed/$PKG-*; } 2>/dev/null`
+    do
+        ANS=`echo "$FILE" | sed 's|.*/||; s|\.spkg||'`
+        if [ -n "$ANS" ]; then
+            echo "$ANS"
+            return 0
+        fi
+    done
+
+    echo >&2 "Cannot determine latest version of $PKG."
+    echo "$PKG"
+    return 1
+}
+
+cat >&3 <<EOF
+# Base packages
+DIR=`newest_version_base dir`
+PREREQ=`newest_version_base prereq`
+BZIP2=`newest_version_base bzip2`
+
+# Standard packages
+ATLAS=`newest_version atlas`
+BLAS=`newest_version blas`
+BOEHM_GC=`newest_version boehm_gc`
+BOOST_CROPPED=`newest_version boost-cropped`
+CDDLIB=`newest_version cddlib`
+CEPHES=`newest_version cephes`
+CLIQUER=`newest_version cliquer`
+CONWAY=`newest_version conway_polynomials`
+CVXOPT=`newest_version cvxopt`
+CYTHON=`newest_version cython`
+DOCUTILS=`newest_version docutils`
+ECL=`newest_version ecl`
+ECLIB=`newest_version eclib`
+ECM=`newest_version ecm`
+ELLIPTIC_CURVES=`newest_version elliptic_curves`
+EXTCODE=`newest_version extcode`
+F2C=`newest_version f2c`
+FLINT=`newest_version flint`
+FLINTQS=`newest_version flintqs`
+FORTRAN=`newest_version fortran`
+FPLLL=`newest_version libfplll`
+FREETYPE=`newest_version freetype`
+GAP=`newest_version gap`
+GD=`newest_version gd`
+GDMODULE=`newest_version gdmodule`
+GENUS2REDUCTION=`newest_version genus2reduction`
+GFAN=`newest_version gfan`
+GIVARO=`newest_version givaro`
+GLPK=`newest_version glpk`
+GNUTLS=`newest_version gnutls`
+GRAPHS=`newest_version graphs`
+GSL=`newest_version gsl`
+ICONV=`newest_version iconv`
+IML=`newest_version iml`
+IPYTHON=`newest_version ipython`
+JINJA2=`newest_version jinja2`
+LAPACK=`newest_version lapack`
+LCALC=`newest_version lcalc`
+LIBGCRYPT=`newest_version libgcrypt`
+LIBGPG_ERROR=`newest_version libgpg_error`
+LIBPNG=`newest_version libpng`
+LINBOX=`newest_version linbox`
+M4RI=`newest_version libm4ri`
+M4RIE=`newest_version libm4rie`
+MATPLOTLIB=`newest_version matplotlib`
+MAXIMA=`newest_version maxima`
+MERCURIAL=`newest_version mercurial`
+MOIN=`newest_version moin`
+MPFI=`newest_version mpfi`
+MPFR=`newest_version mpfr`
+MPIR=`newest_version mpir`
+MPMATH=`newest_version mpmath`
+NETWORKX=`newest_version networkx`
+NTL=`newest_version ntl`
+NUMPY=`newest_version numpy`
+OPENCDK=`newest_version opencdk`
+PALP=`newest_version palp`
+PARI=`newest_version pari`
+PATCH=`newest_version patch`
+PEXPECT=`newest_version pexpect`
+PIL=`newest_version pil`
+POLYBORI=`newest_version polybori`
+POLYTOPES_DB=`newest_version polytopes_db`
+PPL=`newest_version ppl`
+PYCRYPTO=`newest_version pycrypto`
+PYGMENTS=`newest_version pygments`
+PYNAC=`newest_version pynac`
+PYTHON=`newest_version python`
+PYTHON_GNUTLS=`newest_version python_gnutls`
+R=`newest_version r`
+RATPOINTS=`newest_version ratpoints`
+READLINE=`newest_version readline`
+RUBIKS=`newest_version rubiks`
+SAGE=`newest_version sage`
+SAGENB=`newest_version sagenb`
+SAGETEX=`newest_version sagetex`
+SAGE_ROOT_REPO=`newest_version sage_root`
+SAGE_SCRIPTS=`newest_version sage_scripts`
+SCIPY=`newest_version scipy`
+SCONS=`newest_version scons`
+SETUPTOOLS=`newest_version setuptools`
+SINGULAR=`newest_version singular`
+SPHINX=`newest_version sphinx`
+SQLALCHEMY=`newest_version sqlalchemy`
+SQLITE=`newest_version sqlite`
+SYMMETRICA=`newest_version symmetrica`
+SYMPOW=`newest_version sympow`
+SYMPY=`newest_version sympy`
+TACHYON=`newest_version tachyon`
+TERMCAP=`newest_version termcap`
+TWISTED=`newest_version twisted`
+ZLIB=`newest_version zlib`
+ZNPOLY=`newest_version zn_poly`
+ZODB=`newest_version zodb3`
+
+EOF
+
+# Copy spkg/standard/deps
+cat >&3 <<EOF
+
+#==============================================================================
+# What follows now is a copy of
+#   $SAGE_ROOT/spkg/standard/deps
+#==============================================================================
+
+EOF
+
+cat standard/deps >&3
+
+# Close the Makefile
+exec 3>&-
 
 # Skip the rest if nothing to do (i.e., to [re]build).
 # * If "make" doesn't understand the -q option (although we require
 #   GNU make, which supports it), it should exit with a non-zero status
 #   which is not a problem.
-# * Only do this check if $SAGE_LOCAL/bin/sage-spkg understands MAKEFLAGS.
-#   If $SAGE_LOCAL/bin/sage-spkg does not exist, we assume that a
-#   sage-5.x scripts and root repository has been installed, which also
-#   understands MAKEFLAGS.  See Trac #12248 and also #12016.
-if [ ! -f "$SAGE_LOCAL/bin/sage-spkg" ] || \
-grep >/dev/null MAKEFLAGS "$SAGE_LOCAL/bin/sage-spkg"; then
-    if ${MAKE:-make} -q -f standard/deps $1; then
+# * Only do this check if spkg/bin/sage-spkg exists, as that means we
+#   are running sage-5.x and sage-spkg understands MAKEFLAGS.
+#   If we are upgrading, we might have a pre-4.8 version of sage-spkg
+#   which doesn't check MAKEFLAGS.
+#   See Trac #12248 and also #12016.
+if [ -f "$SAGE_ROOT/spkg/bin/sage-spkg" ]; then
+    if ${MAKE:-make} -q $1; then
         echo "Nothing to (re)build / all up-to-date."
         exit 0
     fi
@@ -417,23 +268,10 @@ echo "***********************************************"
 ###############################################################################
 # NOW do the actual build:
 ###############################################################################
-time ${MAKE:-make} -f standard/deps $1
-
-# Added by Burcin Erocal, see trac #6295:
+time ${MAKE:-make} $1
 if [ $? -ne 0 ]; then
     echo >&2 "Error building Sage."
     exit 1
-fi
-
-cd "$SAGE_ROOT"
-
-# Rename makefile to Makefile (see #10156):
-if [ -f makefile ]; then
-    mv makefile Makefile
-    if [ $? -ne 0 ]; then
-        echo "Error renaming 'makefile' to 'Makefile'."
-        exit 1
-    fi
 fi
 
 # Build succeeded.
