Patch for building CMake on OSX 10.10

diff --git a/build/pkgs/cmake/spkg-install b/build/pkgs/cmake/spkg-install
--- a/build/pkgs/cmake/spkg-install
+++ b/build/pkgs/cmake/spkg-install
@@ -2,6 +2,15 @@
 
 cd src
 
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
 ./bootstrap --prefix=$SAGE_LOCAL \
     --system-bzip2 \
     --system-zlib \
