Trac #12519: Do not add -lcblas and -latlas on Darwin

diff --git a/build/pkgs/cvxopt/spkg-check b/build/pkgs/cvxopt/spkg-check
--- a/build/pkgs/cvxopt/spkg-check
+++ b/build/pkgs/cvxopt/spkg-check
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 if [ -z "$SAGE_LOCAL" ] ; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
 CUR=`pwd`
@@ -14,39 +14,37 @@ CUR=`pwd`
 # and HP's on HP-UX do NOT use -m64.
 
 if [ -z "$CFLAG64" ] ; then
-   CFLAG64=-m64
+    CFLAG64=-m64
 fi
 
 # There is no C++ code in cvxopt, so no need to do likewise
 # with CXXFLAG64.
 
 if [ "x$SAGE64" = xyes ]; then
-   echo "Testing a 64-bit version of the cvxopt"
-   CFLAGS="$CFLAGS $CFLAG64"
-   CPPFLAGS="$CPPFLAGS $CFLAG64" ; export CPPFLAGS
-   LDFLAGS="$LDFLAGS $CFLAG64" ; export LDFLAGS
-   CC="$CC $CFLAG64" ; export CC
+    echo "Testing a 64-bit version of the cvxopt"
+    CFLAGS="$CFLAGS $CFLAG64"
+    CPPFLAGS="$CPPFLAGS $CFLAG64" ; export CPPFLAGS
+    LDFLAGS="$LDFLAGS $CFLAG64" ; export LDFLAGS
+    CC="$CC $CFLAG64" ; export CC
 fi
 
 if [ "x$SAGE_DEBUG" = xyes ] ; then
-  CFLAGS="$CFLAGS -g -O0" # No optimisation, aids debugging.
+    CFLAGS="$CFLAGS -g -O0" # No optimisation, aids debugging.
 else
-  CFLAGS="$CFLAGS -g -O2" # Normal optimisation.
+    CFLAGS="$CFLAGS -g -O2" # Normal optimisation.
 fi
 
 export CFLAGS
 
-for di in `ls $CUR/src/examples/doc | grep chap` ; do
- echo "Testing in src/examples/doc/$di "
- cd $CUR/src/examples/doc/$di
- for i in `ls | grep -v bin` ; do
-   echo "Testing  $i ..."
-   python $i
-   if [ $? -ne 0 ]; then
-     echo "Error: $SAGE_LOCAL/bin/python $i failed"
-   fi
- done
+for di in "$CUR"/src/examples/doc/chap* ; do
+    echo "Testing in $di"
+    cd "$di"
+    for i in `ls | grep -v bin` ; do
+        echo "Testing $i ..."
+        python $i
+        if [ $? -ne 0 ]; then
+            echo >&2 "Error: test $di/$i failed"
+            exit 1
+        fi
+    done
 done
-cd $CUR
-
-
diff --git a/build/pkgs/cvxopt/spkg-install b/build/pkgs/cvxopt/spkg-install
--- a/build/pkgs/cvxopt/spkg-install
+++ b/build/pkgs/cvxopt/spkg-install
@@ -1,10 +1,22 @@
 #!/usr/bin/env bash
 
 if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+    echo "SAGE_LOCAL undefined ... exiting";
+    echo "Maybe run 'sage -sh'?"
+    exit 1
 fi
+
+cd src
+
+# Apply patches.
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
 # Normally for a 64-bit build the -m64 option is added to
 # gcc, but other compilers will not accept that, so
 # allow it to be configured as something different if need
@@ -32,7 +44,7 @@ cp -p patches/__init__.py src/src/python/
 # setting Sage-specific libraries locations, etc.
 cp -p patches/setup.py src/src/
 
-cd src/src
+cd src
 python setup.py install
 if [ $? -ne 0 ]; then
    echo "Error building/installing cvxopt"
