#5847 (ecm-6.3.p2): Put back '-fPIC', don't add '-march=native' on older GCC versions, add some tuning parameters from MPIR if available.
We in fact need the '-fPIC' flags unless we build a shared library (where
libtool adds this). Alternatively, not very much tested, we could use the
'--with-pic' option to configure. Either is optimal if we do it uncondi-
tionally.

'-march=native' now only gets added if the compliler really supports it
(not necessarily limited to 'gcc'), since some older GCC 4.0.x versions
don't support it. If '-march=native' isn't supported, we try to get the
processor-specific settings from GMP / MPIR, recorded in Sage's 'gmp.h'.

Some cosmetic changes. Deletion of previous installation is still per-
formed before we know the (re)build succeeded.

Selection of effective CFLAGS can be improved further, still respecting
user-specified settings though. If the user didn't specify any, we can
use the full set of CFLAGS from 'gmp.h' with some additions if required.
(There'll be an MPIR 2.1.3.p2 spkg that exactly does such, so we can
adopt more from there later, also in the MPFR spkg.)

diff --git a/build/pkgs/ecm/spkg-install b/build/pkgs/ecm/spkg-install
--- a/build/pkgs/ecm/spkg-install
+++ b/build/pkgs/ecm/spkg-install
@@ -5,10 +5,37 @@ if [ -z "$SAGE_LOCAL" ]; then
     exit 1
 fi
 
+###############################################################################
+# Apply patches (if any):
+###############################################################################
+
+# Patch configure (and configure.in):
+# - Disable asm-redc on 32-bit Darwin PPCs (upstream revision 1516 / bug #10646)
+# - Fix compilation error on x86 CPUs supporting SSE2. (Sage trac #10252,
+#   upstream revision 1546)
+echo "Copying patched files..."
+cp -p patches/configure patches/configure.in src/
+if [ $? -ne 0 ]; then
+    echo "Error copying patched configure and configure.in."
+    exit 1
+fi
+
+# XXX MOVE THIS DOWN (after *successful* build)!!!
+###############################################################################
+# Remove old executable/header/libraries/manpage:
+###############################################################################
+echo "Removing old binary, header file, manual page and libraries..."
+rm -f "$SAGE_LOCAL"/bin/ecm
+rm -f "$SAGE_LOCAL"/lib/libecm.*
+rm -f "$SAGE_LOCAL"/include/ecm.h
+rm -f "$SAGE_LOCAL"/share/man/man1/ecm.1
+
+###############################################################################
+# Set up environment variables, depending on SAGE_* settings:
 # Note that GMP-ECM is written in C (and assembler) - no C++ sources.
+###############################################################################
 
-
-# We could use / add these settings (or parts of them) later to "our" CFLAGS,
+# We eventually use / add these settings (or parts of them) to "our" CFLAGS,
 # e.g. "-march=..." or "-mcpu=..." and "-mtune=..." to let gcc generate better,
 # processor-specific code, since ECM doesn't use them if we set our own:
 # (But currently MPIR doesn't provide optimized settings either if we pass
@@ -30,20 +57,28 @@ if [ -n "$system_gmp_h" ]; then
     system_gmp_cflags=`sed -n -e "$gmp_cflags_pat" $system_gmp_h`
 fi
 
+cc_is_gcc=false
+if $CC -v 2>&1 | grep -i gcc &>/dev/null; then
+    cc_is_gcc=true;
+fi
+
 
 if [ "$SAGE64" = yes ]; then
     echo "Building a 64-bit version of GMP-ECM"
     if [ -z "$CFLAG64" ]; then
         CFLAG64=-m64
     fi
-    # CFLAGS="$CFLAGS $CFLAG64 -fPIC"
     CFLAGS="$CFLAGS $CFLAG64"
     LDFLAGS="$LDFLAGS $CFLAG64"; export LDFLAGS
 else
-    # libtool should add the proper flags:
-    # CFLAGS="$CFLAGS -fPIC"
     :;
 fi
+
+
+# libtool should add the proper flags, but doesn't use "-fPIC"
+# for the *static* library (which the Sage library links to unless
+# we also build the shared one):
+CFLAGS="$CFLAGS -fPIC" # alternatively add '--with-pic' to 'configure' options
 
 
 if [ "$SAGE_DEBUG" = yes ]; then
@@ -71,29 +106,52 @@ fi
 
 
 if [ "$SAGE_FAT_BINARY" = yes ]; then
+    # XXX Disable SSE2 on x86? (by passing '--enable-sse2=no' to 'configure')
+    # XXX Disable asm-redc? Or pass some "generic" '--host=...' to 'configure'?
     echo "Warning: SAGE_FAT_BINARY is currently not really supported by this package."
+    echo "         Add e.g. '--disable-asm-redc' and/or '--enable-sse2=no'"
+    echo "         to ECM_EXTRA_OPTS if you run into problems."
 else
-    # XXX We don't yet test if CC is really gcc here.
-    # gcc's "-march=native" only works on some platforms:
-    case "`uname -m`" in
-        i[3456]86|i86pc|x86_64|amd64)
-            # Only add it if CFLAGS do not already contain similar:
-            if ! (echo "$CFLAGS" | egrep -- '-march=|-mcpu=|-mtune=' >/dev/null);
-            then
-                CFLAGS="-march=native $CFLAGS"
-            fi;;
-    esac
+    # Tune the code generation to the machine we build on:
+    cpu_params=""; other_gmp_cflags=""
+
+    # Some gcc 4.0.x versions don't support '-march=native', and it's currently
+    # not supported on all platforms supported by Sage:
+    if false && touch foo.c && $CC -march=native -c foo.c &>/dev/null; then
+        cpu_params="-march=native"
+    else
+        # 'native' not supported, see if GMP / MPIR provides us some CPU type:
+        for opt in $gmp_cflags; do
+            case $opt in
+                -march=*|-mcpu=*|-mtune*)
+                    echo "Found CPU parameter in gmp.h: $opt"
+                    cpu_params="$cpu_params $opt"
+                    ;;
+                 # perhaps add other options, too (e.g. for different compilers)
+                 *) other_gmp_cflags="$other_gmp_cflags $opt"
+            esac
+        done
+    fi
+    rm -f foo.*
+    # Only add them if CFLAGS do not already contain similar:
+    if [ -n "$cpu_params" ] &&
+        ! (echo "$CFLAGS" | egrep -- '-march=|-mcpu=|-mtune=' >/dev/null);
+    then
+        echo "Using additional host-specific CFLAGS: $cpu_params"
+        CFLAGS="$cpu_params $CFLAGS"
+    fi
+    if [ -n "$other_gmp_cflags" ]; then
+        echo "Not using other CFLAGS provided by gmp.h: $other_gmp_cflags"
+    fi
 fi
 
 
-export CFLAGS # usually redundant, but safe(r)
-
 echo ""
-echo "Settings from SAGE_LOCAL/include/gmp.h (currently not used):"
+echo "Settings from SAGE_LOCAL/include/gmp.h:"
 echo "    CC=$gmp_cc"
 echo "    CFLAGS=$gmp_cflags"
 if [ -n "$system_gmp_h" ]; then
-    echo "Settings found in $system_gmp_h (also currently not used):"
+    echo "Settings found in $system_gmp_h (currently not used):"
     echo "    CC=$system_gmp_cc"
     echo "    CFLAGS=$system_gmp_cflags"
 fi
@@ -106,36 +164,18 @@ echo "Using ABI=$ABI"
 echo "(These settings may get overridden by 'configure' or Makefiles.)"
 echo ""
 
-
-# Remove old executable/header/libraries/manpage:
-echo "Removing old binary, header file, manual page and libraries..."
-rm -f "$SAGE_LOCAL"/bin/ecm
-rm -f "$SAGE_LOCAL"/lib/libecm.*
-rm -f "$SAGE_LOCAL"/include/ecm.h
-rm -f "$SAGE_LOCAL"/share/man/man1/ecm.1
-
+export CFLAGS # usually redundant, but safe(r)
 
 unset RM
 
-
 cd src
 
-
-# Patch configure (and configure.in):
-# - Disable asm-redc on 32-bit Darwin PPCs (upstream revision 1516 / bug #10646)
-# - Fix compilation error on x86 CPUs supporting SSE2. (Sage trac #10252,
-#   upstream revision 1546)
-echo "Copying patched files..."
-cp -p ../patches/configure ../patches/configure.in .
-if [ $? -ne 0 ]; then
-    echo "Error copying patched configure and configure.in."
-    exit 1
-fi
-
-
-# Note: Building (also) a *shared* library is disabled by default.
-#       Add "--enable-shared" below if you want it, though one can
-#       now pass extra 'configure' options through ECM_EXTRA_OPTS.
+###############################################################################
+# Now configure ECM:
+# (Note: Building (also) a *shared* library is disabled by default.
+#        Add "--enable-shared" below if you want it, though one can
+#        now pass extra 'configure' options through ECM_EXTRA_OPTS.)
+###############################################################################
 
 SAGE_CONF_OPTS=""
 
@@ -163,6 +203,10 @@ if [ $? -ne 0 ]; then
     echo "Error configuring GMP-ECM."
     exit 1
 fi
+
+###############################################################################
+# Now build and install ECM:
+###############################################################################
 
 $MAKE
 if [ $? -ne 0 ]; then
