ecm-6.3.p1: #5847: Apply a patch from upstream to configure.in to fix compilation on 32-bit PowerPC processors
This patch disables redc assembly code on 32-bit MacOS X (PPC), regardless of the processor.

diff --git a/build/pkgs/ecm/spkg-install b/build/pkgs/ecm/spkg-install
--- a/build/pkgs/ecm/spkg-install
+++ b/build/pkgs/ecm/spkg-install
@@ -41,6 +41,14 @@ rm -f "$SAGE_LOCAL"/share/man/man1/ecm.1
 
 cd src
 
+# Patch configure (and configure.in)
+cp -p ../patches/configure ../patches/configure.in .
+if [ $? != 0 ]; then
+	echo >&2 "Error patching configure and configure.in"
+	exit 1
+fi
+
+
 unset RM
 
 # Note: Building (also) a *shared* library is disabled by default.
