#12762 (linbox-1.1.6.p9): Fix C++11/GCC 4.7 issues, add spkg-check, rework spkg-install.
=== linbox-1.1.6.p9 (Leif Leonhardy, April 7th 2012) ===
 * #12762: Temporarily add `-fpermissive` to `CXXFLAGS` if we're compiling
   with `g++` 4.7.x, since the LinBox sources currently don't conform to
   C++11, so GCC 4.7.x would otherwise reject them.
 * Exit if the build failed.
 * Use `CFLAG64` if it is set (and `SAGE64=yes`).
 * Clean up `spkg-install`, add some messages.
 * Add an `spkg-check` file, which currently runs `make check`. (There's also
   a `fullcheck` target.)
 * Change patch to disable the commentator, as default parameters were missing
   with `-DDISABLE_COMMENTATOR`, such that the test suite wouldn't build.
   Also, one must not unconditionally use `extern` for the global (dummy)
   commentator since this is C++, and doing so also breaks the test suite.
 * Fix (i.e. patch) the sources such that the test suite (`make check`) builds,
   also with GCC 4.7.0.
 * Add the "Special Update/Build Instructions" section.

diff --git a/build/pkgs/linbox/spkg-install b/build/pkgs/linbox/spkg-install
--- a/build/pkgs/linbox/spkg-install
+++ b/build/pkgs/linbox/spkg-install
@@ -1,128 +1,140 @@
 #!/usr/bin/env bash
 
-if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "Error: SAGE_LOCAL undefined - exiting..."
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
 cd src/
 
-# Apply patches.
+###############################################################################
+# Apply patches (if any):
+###############################################################################
+
+echo "Applying patches (if any) to upstream source..."
 for patch in ../patches/*.patch; do
+    basename "$patch"
     patch -p1 <"$patch"
     if [ $? -ne 0 ]; then
-        echo >&2 "Error applying '$patch'"
+        echo >&2 "Error applying '$patch'."
         exit 1
     fi
 done
 
-export CFLAGS="$CFLAGS -g -fPIC"
-export CXXFLAGS="$CXXFLAGS -g -fPIC"
+###############################################################################
+# Set up environment variables:
+###############################################################################
 
-# Some systems have problems when parts of Linbox are compiled with
+CFLAGS="-g $CFLAGS -fPIC"
+CXXFLAGS="-g $CXXFLAGS -fPIC"
+
+case "`$CXX -dumpversion 2>/dev/null`" in
+    4.7.*)
+        echo "Adding '-fpermissive' to CXXFLAGS to make LinBox build with GCC 4.7.x."
+        echo "This is a temporary fix; LinBox currently doesn't conform to the C++11 standard."
+        CXXFLAGS="-fpermissive $CXXFLAGS" # The user might still override that.
+esac
+
+# Some systems have problems when parts of LinBox are compiled with
 # the commentator enabled and other parts with the commentator
-# disabled.  Therefore, disable it always.
-export CPPFLAGS="$CPPFLAGS -DDISABLE_COMMENTATOR"
+# disabled.  Therefore, disable it always:
+CPPFLAGS="$CPPFLAGS -DDISABLE_COMMENTATOR"
 
-if [ "$SAGE64" = "yes" ]; then
-   echo "64 bit build"
-   CFLAGS="-m64 $CFLAGS "; export CFLAGS
-   CXXFLAGS="-m64 $CXXFLAGS "; export CXXFLAGS
-   CPPFLAGS="-m64 $CPPFLAGS "; export CPPFLAGS
-   LDFLAGS="-m64"; export LDFLAGS
+if [ "$SAGE64" = yes ]; then
+    echo "Building a 64-bit version of LinBox."
+    if [ -z "$CFLAG64" ]; then
+        CFLAG64=-m64
+    fi
+    CFLAGS="$CFLAGS $CFLAG64"
+    CXXFLAGS="$CXXFLAGS $CFLAG64"
+    CPPFLAGS="$CPPFLAGS $CFLAG64"
+    LDFLAGS="$LDFLAGS $CFLAG64"
 fi
 
+export CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
 
-if [ "$LINBOX_BLAS" != "" ]; then
 
-    echo "Using environment variable LINBOX_BLAS "$LINBOX_BLAS""
-
-elif [ $UNAME = "Darwin" -a -f "/usr/lib/libcblas.dylib" ]; then
-
-    LINBOX_BLAS=/usr/lib/libcblas.dylib
-
-elif [ $UNAME = "Linux" -a -f "${SAGE_LOCAL}/lib/libcblas.so" ]; then
-
-    echo "Linux cblas"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
-elif [ $UNAME = "CYGWIN" ]; then
-
-    echo "Using system-wide Cygwin LAPACK BLAS."
-    if [ ! -f "/usr/lib/libblas.a" ]; then
-        echo "*************************************************"
-        echo "*"
-        echo "* On Cygwin you must install the standard LAPACK Cygwin package"
-        echo "* via the Cygwin setup.exe program in the 'Math' category."
-        echo "*"
-        echo "*************************************************"
-        exit 1
-    fi
-    LINBOX_BLAS="-lblas "
-
-elif [ $UNAME = "SunOS" -a -f "${SAGE_LOCAL}/lib/libcblas.so" ]; then
-
-    echo "Solaris cblas"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
-elif [ $UNAME = "FreeBSD" -a -f "${SAGE_LOCAL}/lib/libcblas.a" ]; then
-
-    echo "FreeBSD cblas"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
-elif [ $UNAME = "FreeBSD" -a -f "${SAGE_LOCAL}/lib/libcblas.so" ]; then
-
-    echo "FreeBSD cblas"
-
-    LINBOX_BLAS="-lcblas -latlas"
-
+if [ -n "$LINBOX_BLAS" ]; then
+    echo "Using environment variable LINBOX_BLAS (=\"$LINBOX_BLAS\")."
 else
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "using frickin' slow GSL C-blas"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-    echo "WARNING WARNING"
-
-    if [ $UNAME = "Darwin" ]; then
-        LINBOX_BLAS="$SAGE_LOCAL"/lib/libgslcblas.dylib
-    else
-        LINBOX_BLAS="$SAGE_LOCAL"/lib/libgslcblas.so
+    case "$UNAME" in
+        Darwin)
+            so_ext=dylib
+            if [ -f /usr/lib/libcblas.dylib ]; then
+                echo "Using the system-wide CBLAS library."
+                LINBOX_BLAS=/usr/lib/libcblas.dylib
+            fi;;
+        Linux|SunOS|FreeBSD) # Other OSs could be added here as well.
+            so_ext=so
+            if [ -f "$SAGE_LOCAL"/lib/libcblas.a -o -f "$SAGE_LOCAL"/lib/libcblas.so ]; then
+                LINBOX_BLAS="-lcblas -latlas"
+            fi;;
+        CYGWIN)
+            echo "Using the system-wide Cygwin LAPACK BLAS library."
+            if [ ! -f /usr/lib/libblas.a ]; then
+                echo >&2 "Error: BLAS library not found."
+		echo >&2 "On Cygwin you must install the standard LAPACK Cygwin package"
+		echo >&2 "via the Cygwin setup.exe program in the 'Math' category."
+                exit 1
+            fi
+            LINBOX_BLAS="-lblas"
+            ;;
+        *) # We may issue a warning here, or just (try to) use Sage's ATLAS lib.
+            so_ext=so # Most common.
+            echo >&2 "Warning: Your operating system ($UNAME) is not explicitly supported"
+            echo >&2 "         by Sage / LinBox's 'spkg-install'."
+            echo >&2 "         Not trying to use Sage's ATLAS library."
+    esac
+    if [ -z "$LINBOX_BLAS" ]; then
+        echo >&2 "Warning: Using the frickin' slow GSL CBLAS library."
+        LINBOX_BLAS="$SAGE_LOCAL"/lib/libgslcblas.${so_ext}
     fi
-
 fi
 
-echo "*************************************************"
-echo " Using LINBOX_BLAS=$LINBOX_BLAS"
-echo "*************************************************"
+echo "Using \"$LINBOX_BLAS\" for the BLAS library."
 
-./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" --with-givaro="$SAGE_LOCAL" --with-gmp="$SAGE_LOCAL" --with-ntl="$SAGE_LOCAL"  --with-blas="$LINBOX_BLAS" --enable-sage --enable-optimization --disable-static
+###############################################################################
+# Configure, build and install LinBox:
+###############################################################################
 
+echo "Now configuring LinBox..."
+./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
+            --with-givaro="$SAGE_LOCAL" --with-gmp="$SAGE_LOCAL" \
+            --with-ntl="$SAGE_LOCAL" --with-blas="$LINBOX_BLAS" \
+            --enable-sage --enable-optimization --disable-static
 if [ $? -ne 0 ]; then
-    echo "Error configuring linbox"
+    echo >&2 "Error configuring LinBox."
     exit 1
 fi
 
+echo "Now building LinBox..."
 $MAKE
 if [ $? -ne 0 ]; then
-    echo "Error building linbox"
-fi
-
-$MAKE install
-if [ $? -ne 0 ]; then
-    echo "Error installing linbox"
+    echo >&2 "Error building LinBox."
     exit 1
 fi
 
-if [ -f "$SAGE_ROOT"/devel/sage/sage/libs/linbox/linbox.pyx ]; then
-    echo "Touching extensions linked against LinBox"
-    touch "$SAGE_ROOT"/devel/sage/sage/libs/linbox/linbox.pyx
+echo "Now installing LinBox..."
+$MAKE install
+if [ $? -ne 0 ]; then
+    echo >&2 "Error installing LinBox."
+    exit 1
 fi
+
+echo "Installation of LinBox completed."
+
+# Touch sources of Python extension modules using LinBox such that they get
+# rebuilt the next time the Sage library gets (re)built (e.g. by './sage -b'):
+# (In principle, such modules should depend on a header file with a fresh
+# timestamp each time LinBox gets reinstalled.  Then Cython would automatically
+# rebuild them.)
+echo "Touching extension modules linked against LinBox to force their rebuild..."
+prefix="$SAGE_ROOT/devel/sage"
+modules="sage/libs/linbox/linbox.pyx"
+for pyx in $modules; do
+    if [ -f "$prefix/$pyx" ]; then
+        echo "    $pyx"
+        touch "$prefix/$pyx"
+    fi
+done
