Integrate patch by Clement Pernet fixing #3671

diff --git a/build/pkgs/linbox/spkg-install b/build/pkgs/linbox/spkg-install
--- a/build/pkgs/linbox/spkg-install
+++ b/build/pkgs/linbox/spkg-install
@@ -1,4 +1,10 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+if [ "$SAGE_LOCAL" = "" ]; then
+   echo "SAGE_LOCAL undefined ... exiting";
+   echo "Maybe run 'sage -sh'?"
+   exit 1
+fi
 
 CUR=`pwd`
 
@@ -7,6 +13,13 @@ cp patches/commentator.C linbox/linbox/util/
 
 if [ $? -ne 0 ]; then
     echo "Error copying commentator OSX 10.4 fix"
+    exit 1
+fi
+
+echo "Copying ffpack.h patch for charpoly mpd p issue (#3671)"
+cp patches/ffpack.h linbox/linbox/ffpack/
+if [ $? -ne 0 ]; then
+    echo "Error copying ffpack.h patch for charpoly mpd p issue"
     exit 1
 fi
 
