mercurial-0.9.5.p1: fix OSX 64 bit build, clean up SPKG.txt

diff --git a/build/pkgs/mercurial/spkg-install b/build/pkgs/mercurial/spkg-install
--- a/build/pkgs/mercurial/spkg-install
+++ b/build/pkgs/mercurial/spkg-install
@@ -1,5 +1,16 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
+if [ "$SAGE_LOCAL" = "" ]; then
+   echo "SAGE_LOCAL undefined ... exiting";
+   echo "Maybe run 'sage -sh'?"
+   exit 1
+fi
+
+if [ `uname` = "Darwin" -a "$SAGE64" = "yes" ]; then
+   echo "64 bit MacIntel"
+   CFLAGS="-O2 -g -m64 "; export CFLAGS
+   CXXFLAGS="-O2 -g -m64 "; export CXXFLAGS
+fi
 
 CUR=`pwd`
 
@@ -22,6 +33,11 @@ perl -p -i -e 's/>manifest</>browse all files</g' src/templates/*.tmpl
 cd src
 
 python setup.py install --home="$SAGE_LOCAL" --force
+
+if [ $? -ne 0 ]; then
+    echo "Error building mercurial"
+    exit 1
+fi
 
 echo "Deleting dead links"
 cd $SAGE_LOCAL/lib
