Trac #13126: update and clean up openssl  * Update source to 1.0.1c  * Created hg repository  * Cleaned up spkg-install  * Created spkg-check  * Patch to build on OS X Lion  * Patch to build on Solaris

diff --git a/build/pkgs/openssl/spkg-install b/build/pkgs/openssl/spkg-install
--- a/build/pkgs/openssl/spkg-install
+++ b/build/pkgs/openssl/spkg-install
@@ -1,31 +1,60 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-cd src/
-
-# this avoids a bug later in the build scripts.
-touch apps/openssl
-touch apps/openssl.exe   # in case user is on Windows
-
-./config --libdir=lib --prefix="$SAGE_LOCAL" --openssldir="$SAGE_LOCAL"/openssl shared
-
-if [ $? -ne 0 ]; then
-    echo "Error configuring openssl."
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage --sh'?"
     exit 1
 fi
 
-# do not use MAKE environment variable -- if given -j option install breaks
-make
+cd src
 
-if [ $? -ne 0 ]; then
-    echo "Error building openssl."
-    exit 1
+# Apply patches
+echo "Patching openssl..."
+for p in ../patches/*.patch; do
+    patch -p1 <"$p"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+echo
+
+# Building on OS X Lion 64-bit seems to fail unless we build a 64-bit library.
+echo "Configuring openssl..."
+if [ "$UNAME" = "Darwin" ]; then
+    # This check for 64-bit is taken from src/config.
+    ISA64=`(sysctl -n hw.optional.x86_64) 2>/dev/null`
+    if [ "$ISA64" = "1" ]; then
+	# 64-bit
+	./Configure darwin64-x86_64-cc --libdir=lib --prefix="$SAGE_LOCAL" --openssldir="$SAGE_LOCAL"/openssl shared
+    else
+	./config --libdir=lib --prefix="$SAGE_LOCAL" --openssldir="$SAGE_LOCAL"/openssl shared
+    fi
+else
+    ./config --libdir=lib --prefix="$SAGE_LOCAL" --openssldir="$SAGE_LOCAL"/openssl shared
 fi
 
-make install
-
 if [ $? -ne 0 ]; then
-    echo "Error installing openssl."
+    echo >&2 "Error configuring openssl."
     exit 1
 fi
+echo
 
+# Do not build in parallel.
+MAKE="$MAKE -j1"
+echo "Building openssl..."
+$MAKE
 
+if [ $? -ne 0 ]; then
+    echo >&2 "Error building openssl."
+    exit 1
+fi
+echo
+
+echo "Installing openssl..."
+$MAKE install
+
+if [ $? -ne 0 ]; then
+    echo >&2 "Error installing openssl."
+    exit 1
+fi
