touch src/src/config.h.in; remove testcc.sh script

diff --git a/build/pkgs/libm4rie/spkg-install b/build/pkgs/libm4rie/spkg-install
--- a/build/pkgs/libm4rie/spkg-install
+++ b/build/pkgs/libm4rie/spkg-install
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting"
-   echo "Maybe run 'sage -sh'?"
+   echo >&2 "SAGE_LOCAL undefined ... exiting"
+   echo >&2 "Maybe run 'sage -sh'?"
    exit 1
 fi
 
@@ -16,14 +16,14 @@ LIBDIRS="-L$SAGE_LOCAL/lib"
 CFLAGS="$CFLAGS $INCLUDES -g"
 LDFLAGS="$LIBDIRS"
 
-COMPILER=`./testcc.sh`
+COMPILER=`testcc.sh "$CC"`
 
-if [ "x$COMPILER"  = "xGNU" ] ; then
-   CFLAGS="$CFLAGS -fPIC -Wall -pedantic"
-elif [ "x$COMPILER" = "xSun_on_Solaris" ] ; then
-   CFLAGS="$CFLAGS -Kpic"
-elif [ "x$COMPILER" = "xHP_on_HPUX" ] ; then
-   CFLAGS="$CFLAGS + z"
+if [ "$COMPILER"  = "GNU" ] ; then
+    CFLAGS="$CFLAGS -fPIC -Wall -pedantic"
+elif [ "$COMPILER" = "Sun_on_Solaris" ] ; then
+    CFLAGS="$CFLAGS -Kpic"
+elif [ "$COMPILER" = "HP_on_HPUX" ] ; then
+    CFLAGS="$CFLAGS + z"
 fi
 
 CPPFLAGS="$INCLUDES"
@@ -49,25 +49,25 @@ export LDFLAGS
 
 # build M4RIE
 
-cd $ROOT_DIR/m4rie/
-$ROOT_DIR/m4rie/configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" $ENABLE_DEBUG
+cd $ROOT_DIR/src/
+./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" $ENABLE_DEBUG
 
 if [ $? -ne 0 ]; then
-    echo "Error configuring libm4rie"
+    echo >&2 "Error configuring libm4rie"
     exit 1
 fi
 
 $MAKE
 
 if [ $? -ne 0 ]; then
-    echo "Error building libm4rie"
+    echo >&2 "Error building libm4rie"
     exit 1
 fi
 
 $MAKE install
 
 if [ $? -ne 0 ]; then
-    echo "Error installing libm4rie"
+    echo >&2 "Error installing libm4rie"
     exit 1
 fi
 
