#7766 Changed make to $MAKE, improved spkg-check, fixed changelog

diff --git a/build/pkgs/valgrind/spkg-check b/build/pkgs/valgrind/spkg-check
--- a/build/pkgs/valgrind/spkg-check
+++ b/build/pkgs/valgrind/spkg-check
@@ -1,5 +1,16 @@
 #!/usr/bin/env bash
 
+if [ "$SAGE_LOCAL" = "" ]; then
+   echo "SAGE_LOCAL undefined ... exiting";
+   echo "Maybe run 'sage -sh'?"
+   exit 1
+fi
+
 cd src/
 
-make regtest
+$MAKE regtest
+
+if [ $? -ne 0 ]; then
+    echo "Testing valgrind failed"
+    exit 1
+fi
