valgrind_3.3.0: update to 3.3.0 release, pretty up SPKG.txt, exit if uname != Linux

diff --git a/build/pkgs/valgrind/spkg-install b/build/pkgs/valgrind/spkg-install
--- a/build/pkgs/valgrind/spkg-install
+++ b/build/pkgs/valgrind/spkg-install
@@ -1,28 +1,32 @@
-#!/bin/sh
-###########################################
-## valrgind 3.3.0svn
-###########################################
+#!/bin/bash
+
+VALGRIND_VERSION="3.3.0"
+
+if [ `uname` != "Linux" ]; then
+    echo "Sorry, valgrind only works on Linux at the moment"
+    exit 1
+fi
 
 cd src/
 
 ./configure --prefix=$SAGE_LOCAL
 
 if [ $? -ne 0 ]; then
-    echo "error configuring valgrind 3.3.0svn"
+    echo "error configuring valgrind $VALGRIND_VERSION"
     exit 1
 fi
 
 make
 
 if [ $? -ne 0 ]; then
-    echo "error installing valgrind 3.3.0svn"
+    echo "error installing valgrind $VALGRIND_VERSION"
     exit 1
 fi
 
 make install
 
 if [ $? -ne 0 ]; then
-    echo "error installing valgrind 3.3.0svn"
+    echo "error installing valgrind $VALGRIND_VERSION"
     exit 1
 fi
 
