build/pkgs/pplpy/dependencies: Fix up SAGE_SPKG_INSTALL_DOCS logic

diff --git a/build/pkgs/pplpy/spkg-postinst.in b/build/pkgs/pplpy/spkg-postinst.in
--- a/build/pkgs/pplpy/spkg-postinst.in
+++ b/build/pkgs/pplpy/spkg-postinst.in
@@ -2,8 +2,14 @@ if [[ "$SAGE_SPKG_INSTALL_DOCS" != no ]] ; then
     # Compile pplpy's documentation
     cd src
     cd docs
-    $MAKE html
-
+    if ! command -v sphinx-build >/dev/null; then
+        echo "sphinx-build not found, not attempting documentation build"
+        exit 0
+    fi
+    if ! $MAKE html; then
+        echo "Documentation build failed (ignored)"
+        exit 0
+    fi
     # install pplpy's documentation
     PPLPY_DOCS=$SAGE_SHARE/doc/pplpy
     mkdir -p $PPLPY_DOCS
