A bunch of changes - see SPKG.txt

diff --git a/build/pkgs/lie/spkg-install b/build/pkgs/lie/spkg-install
--- a/build/pkgs/lie/spkg-install
+++ b/build/pkgs/lie/spkg-install
@@ -1,29 +1,29 @@
 #!/bin/sh
 
-CUR=`pwd`
-
-cp patches/lie "$SAGE_LOCAL"/bin/
-
-# PATCHING
-cp patches/lie.h src
-if [ $UNAME = "SunOS" ]; then
-cp pathces/Makefile.sun src/Makefile
-else
-cp patches/Makefile src
-fi
-cp patches/closure.c src/box/
-
-rm -rf "$SAGE_LOCAL"/lib/lie
-cp -r src "$SAGE_LOCAL"/lib/lie
-
-cd "$SAGE_LOCAL"/lib/lie
-
-make
-
-if [ $? -ne 0 ]; then
-    echo "Error building Lie."
+die () {
+    echo "$@"
     exit 1
+}
+
+# patching
+cd src/
+chmod -R a+rX .
+patch -p1 <../patches/00-string.h.patch &&
+patch -p1 <../patches/01-libs.patch &&
+patch -p1 <../patches/02-hashbang.patch ||
+    die "Error patching LiE."
+if [ $UNAME = "SunOS" ]; then
+    patch -p1 <../patches/03-solaris.patch ||
+        die "Error patching LiE."
 fi
 
+# building
+make CC="$CC" || die "Error building LiE."
 
-
+# relocating
+cd ..
+sed -i -e "s'$PWD/src'$SAGE_LOCAL/lib/LiE'" src/lie
+rm -rf "$SAGE_LOCAL"/lib/lie # clean up old versions
+rm -rf "$SAGE_LOCAL"/bin/lie "$SAGE_LOCAL"/lib/LiE
+mv src/lie -t "$SAGE_LOCAL"/bin/
+mv src/ -T "$SAGE_LOCAL"/lib/LiE
