Trac #14629: upgrade to version 3.7.17 Use standard template for SPKG.txt and spkg-install, use $MAKE instead of make Remove Fortran and C++ stuff from spkg-install

diff --git a/build/pkgs/sqlite/spkg-install b/build/pkgs/sqlite/spkg-install
--- a/build/pkgs/sqlite/spkg-install
+++ b/build/pkgs/sqlite/spkg-install
@@ -1,91 +1,61 @@
 #!/usr/bin/env bash
 
-
-if [ -z "$SAGE_LOCAL" ] ; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage --sh'?"
+    exit 1
 fi
-
-# Force an exit on all errors. However, note it will be desirable to unset
-# this sometimes, as you might want to test for a particular error and exit
-# with a message. You can't do that with 'set -e'. So use 'set +e' to unset it
-
-set -e
-
-
-# Compile for 64-bit if SAGE64 is set to 'yes'
-if [ "x$SAGE64" = "xyes" ] ; then
-   CFLAGS="$CFLAGS -m64 "
-   CXXFLAGS="$CXXFLAGS -m64 "
-   FFLAGS="$FFLAGS -m64 "
-fi
-
-# If SAGE_DEBUG is set either unset (the default), set to '1', 'yes', or 'TRUE'
-# then build with debugging information. Otherwise, don't add debugging
-# information.
-
-# Since both the Sun and GNU compilers accept -g to give debugging information,
-# there is no need to do anything specific to one compiler or the other.
-
-if [ "x$SAGE_DEBUG" = "x" ] || [ "x$SAGE_DEBUG" = "x1" ] ; then
-  echo "Code will be built with debugging information present. Set 'SAGE_DEBUG' to '0' if you don't want that."
-  CFLAGS="$CFLAGS -g "
-  CXXFLAGS="$CXXFLAGS -g "
-  FFLAGS="$FFLAGS -g "
-elif [ "x$SAGE_DEBUG" = "xyes" ] || [ "x$SAGE_DEBUG" = "xTRUE" ] ; then
-  echo "Code will be built with debugging information present. Set 'SAGE_DEBUG' to '0' if you don't want that."
-  CFLAGS="$CFLAGS -g "
-  CXXFLAGS="$CXXFLAGS -g "
-  FFLAGS="$FFLAGS -g "
-fi
-
-export CFLAGS="$CFLAGS -O2 "
-export CXXFLAGS="$CXXFLAGS -O2 "
-export CPPFLAGS="$CPPFLAGS -I $SAGE_LOCAL/include"
-export LDFLAGS="$LDFLAGS -I $SAGE_LOCAL/lib"
-
-# There is no Fortran code in sqlite, but if FC is not set, there
-# there are annoying messages showing the use of the GNU fortran compiler
-# even if SAGE_FORTRAN is set to another compiler. This just stops that.
-export FC=$SAGE_FORTRAN
-export F77=$SAGE_FORTRAN
 
 cd src
 
-echo "Building sqlite using CC=$CC"
-echo "                      CCX=$CXX"
-echo "                      SAGE_FORTRAN=$SAGE_FORTRAN"
-echo "                      F77=$F77"
-echo "                      FC=$FC"
-echo "                      CFLAGS=$CFLAGS"
-echo "                      CXXFLAGS=$CXXFLAGS"
-echo "                      FFLAGS=$FFLAGS"
-echo "                      CPPFLAGS=$CPPFLAGS"
-echo "                      LDFLAGS=$LDFLAGS"
+# Apply patches.  See SPKG.txt for information about what each patch
+# does.
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
-# Disable exit on error, since the necessary checks for errors
-# are below.
+# Compile for 64-bit if SAGE64 is set to 'yes'
+if [ "x$SAGE64" = "xyes" ] ; then
+    CFLAGS="$CFLAGS -m64 "
+fi
 
-set +e
+
+# Build with -O0 if debugging requested
+if [ "$SAGE_DEBUG" = "yes" ]; then
+    CFLAGS="-g -O0 $CFLAGS"
+else
+    CFLAGS="-g -O2 $CFLAGS"
+fi
+
+export CPPFLAGS="$CPPFLAGS -I$SAGE_LOCAL/include"
+export LDFLAGS="$LDFLAGS -L$SAGE_LOCAL/lib"
+export CFLAGS
+
+# Old OS X systems need -DSQLITE_WITHOUT_ZONEMALLOC
+if uname -sr |grep 'Darwin [0-8][.]' >/dev/null; then
+    export CPPFLAGS="$CPPFLAGS -DSQLITE_WITHOUT_ZONEMALLOC"
+fi
+
 
 ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib"
-
 if [ $? -ne 0 ]; then
-    echo "Error configuring sqlite"
+    echo >&2 "Error configuring sqlite."
     exit 1
 fi
 
-make
-
+$MAKE
 if [ $? -ne 0 ]; then
-    echo "Error making sqlite"
+    echo >&2 "Error making sqlite."
     exit 1
 fi
 
-make install
-
+$MAKE install
 if [ $? -ne 0 ]; then
-    echo "Error installing sqlite"
+    echo >&2 "Error installing sqlite."
     exit 1
 fi
