Add a patch removing "static" option which is not supported on Mac OS.

diff --git a/build/pkgs/normaliz/spkg-install b/build/pkgs/normaliz/spkg-install
--- a/build/pkgs/normaliz/spkg-install
+++ b/build/pkgs/normaliz/spkg-install
@@ -1,25 +1,18 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
-if [ -z "$SAGE_LOCAL" ]; then
-    echo >&2 "SAGE_LOCAL undefined ... exiting"
-    echo >&2 "Maybe run 'sage -sh'?"
+die () {
+    echo "$@" 1>&2
     exit 1
-fi
+}
+
+[ -n "$SAGE_LOCAL" ] || die 'Error: $SAGE_LOCAL not set. Source sage-env or run this script from `sage -sh`.'
+
+cd src
+patch -p1 < ../patches/00-remove-static-option.patch || die "Error: Couldn't apply patch."
 
 export CXXFLAGS="-I$SAGE_LOCAL/include $CXXFLAGS"
+cd source
+$MAKE || die "Error building Normaliz."
 
-cd src/source
-$MAKE
-
-if [ $? -ne 0 ]; then
-    echo >&2 "Error building Normaliz."
-    exit 1
-fi
-
-cp -pf normaliz "$SAGE_LOCAL/bin/"
-
-if [ $? -ne 0 ]; then
-    echo >&2 "Error installing Normaliz."
-    exit 1
-fi
+cp -pf normaliz "$SAGE_LOCAL/bin/" || die "Error installing Normaliz."
 
