#12761 (givaro-3.2.13.rc1.p4): Fix headers to conform to C++11 (GCC 4.7.x), major clean-up.
=== givaro-3.2.13.rc1.p4 (Leif Leonhardy, March 27th 2012) ===
 * #12761: Fix headers not conforming to C++11 to make Sage (especially the
   Sage library) build with GCC 4.7.0 (and without `-fpermissive`).
   Same for Givaro's test suite, which uses / instantiates much more!
   (These headers get installed into `$SAGE_LOCAL/include/givaro/`.)
   New patches:
   - patches/src.kernel.integer.givintnumtheo.inl.patch
   - patches/src.kernel.integer.givintrsa.inl.patch
   - patches/src.library.poly1.givpoly1factor.inl.patch
   - patches/src.library.poly1.givpoly1padic.h.patch
   - patches/src.library.poly1.givpoly1proot.inl.patch
 * Remove the obsolete Debian `dist/` directory.
 * Remove obsolete GCC 4.3 patch.
 * Rename diffs of prepatched files that are (still) copied over to `*.diff`
   (rather than `*.patch`) such that they don't get "automatically" applied
   by the `patch -p1` loop, which I added.
 * Fix permissions of `SPKG.txt` and `spkg-install`, and two upstream files.
 * Add "Special Update/Build Instructions" section.
 * Clean up `spkg-check` and `spkg-install`.
 * Also set up environment variables in `spkg-check`, as `make check` involves
   compilation.  (Although `configure` should have put them into the generated
   Makefiles.)
 * Use `$MAKE` in `spkg-check` as well.
 * Exit in case the build failed!
 * Only `touch` extension modules (`*.pyx`) if they (already) exist.

diff --git a/build/pkgs/givaro/spkg-install b/build/pkgs/givaro/spkg-install
--- a/build/pkgs/givaro/spkg-install
+++ b/build/pkgs/givaro/spkg-install
@@ -1,60 +1,111 @@
 #!/usr/bin/env bash
 
-if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+if [[ -z "$SAGE_LOCAL" ]]; then
+    echo >&2 "Error: SAGE_LOCAL undefined - exiting..."
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
-echo "Copying updated gmp++.h"
-cp patches/gmp++.h src/src/kernel/gmp++/
-echo "Copying updated gmp++_int.inl"
-cp patches/gmp++_int.inl src/src/kernel/gmp++/
+#################################
+# Set up environment variables: #
+#################################
 
-if [ $UNAME = "CYGWIN" ]; then
-    echo "Patching givtablelimits.h for Cygwin (because of missing logb)"
-    cp patches/givtablelimits.h src/src/kernel/zpz/givtablelimits.h
+if [[ -z $CFLAG64 ]]; then
+    CFLAG64=-m64
+fi
+if [[ -z $CXXFLAG64 ]]; then
+    CXXFLAG64="$CFLAG64"
+fi
+if [[ "$SAGE64" = yes ]]; then
+    echo "Building a 64-bit version of Givaro."
+    CFLAGS="$CFLAGS $CFLAG64"
+    CPPFLAGS="$CPPFLAGS $CFLAG64"
+    CXXFLAGS="$CXXFLAGS $CXXFLAG64"
+    LDFLAGS="$LDFLAGS $CFLAG64"
 fi
 
-cd src
-
-if [ "$SAGE64" = "yes" ]; then
-   echo "64 bit build"
-   CFLAGS="-O2 -g -m64 "; export CFLAGS
-   CPPFLAGS="-O2 -g -m64 "; export CPPFLAGS
-   LDFLAGS="-m64"; export LDFLAGS
-fi
-
+# It shouldn't be necessary to add Sage's include directory here,
+# since we configure with '--with-gmp=...'.
+# Also, '-I...' should normally be added to (just) CPPFLAGS.
 CFLAGS="$CFLAGS -fPIC -I\"$SAGE_LOCAL/include\""
 CXXFLAGS="$CXXFLAGS -fPIC -I\"$SAGE_LOCAL/include\""
-export CFLAGS
-export CXXFLAGS
 
-./configure --prefix=$SAGE_LOCAL --libdir="$SAGE_LOCAL/lib" --with-gmp="$SAGE_LOCAL/" --enable-shared
+export CFLAGS CPPFLAGS CXXFLAGS LDFLAGS
 
-if [ $? -ne 0 ]; then
-    echo "Error configuring givaro"
+
+cd src/
+
+##################################################
+# Apply patches (or copy over prepatched files): #
+##################################################
+
+echo "Copying updated gmp++ headers..."
+cp ../patches/{gmp++.h,gmp++_int.inl} src/kernel/gmp++/
+if [[ $? -ne 0 ]]; then
+    echo >&2 "Error copying updated gmp++ headers."
     exit 1
 fi
 
+if [[ "$UNAME" = CYGWIN ]]; then
+    echo "Patching givtablelimits.h for Cygwin (because of missing logb())..."
+    cp ../patches/givtablelimits.h src/kernel/zpz/givtablelimits.h
+    if [[ $? -ne 0 ]]; then
+        echo >&2 "Error copying patched header file for Cygwin."
+        exit 1
+    fi
+fi
+
+echo "Applying further patches (if any)..."
+for patch in ../patches/*.patch; do
+    patch -p1 <"$patch"
+    if [[ $? -ne 0 ]]; then
+        echo >&2 "Error: '$patch' failed to apply."
+        exit 1
+    fi
+done
+
+########################################
+# Configure, build and install Givaro: #
+########################################
+
+echo "Now configuring Givaro..."
+./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
+            --with-gmp="$SAGE_LOCAL" --enable-shared
+if [[ $? -ne 0 ]]; then
+    echo >&2 "Error configuring Givaro."
+    exit 1
+fi
+
+echo "Now building Givaro..."
 $MAKE
-if [ $? -ne 0 ]; then
-    echo "Error building givaro"
-fi
-
-$MAKE install
-if [ $? -ne 0 ]; then
-    echo "Error installing givaro"
+if [[ $? -ne 0 ]]; then
+    echo >&2 "Error building Givaro."
     exit 1
 fi
 
-if [ -f "$SAGE_ROOT"/devel/sage/sage/rings/polynomial/multi_polynomial_ideal_libsingular.pyx ]; then
-    echo "Touching extensions linked against Givaro"
-    touch "$SAGE_ROOT"/devel/sage/sage/rings/finite_field_givaro.pyx
-    touch "$SAGE_ROOT"/devel/sage/sage/libs/linbox/linbox.pyx
-    touch "$SAGE_ROOT"/devel/sage/sage/libs/singular/singular.pyx
-    touch "$SAGE_ROOT"/devel/sage/sage/matrix/matrix_mpolynomial_dense.pyx
-    touch "$SAGE_ROOT"/devel/sage/sage/rings/polynomial/multi_polynomial_libsingular.pyx
-    touch "$SAGE_ROOT"/devel/sage/sage/rings/polynomial/multi_polynomial_ideal_libsingular.pyx
+echo "Now installing Givaro..."
+$MAKE install
+if [[ $? -ne 0 ]]; then
+    echo >&2 "Error installing Givaro."
+    exit 1
 fi
+
+############################################################
+# Make sure dependent extension modules later get rebuilt: #
+############################################################
+
+echo "Touching Python extension modules linked against Givaro..."
+for pyx in rings/finite_field_givaro.pyx \
+           libs/linbox/linbox.pyx \
+           libs/singular/singular.pyx \
+           matrix/matrix_mpolynomial_dense.pyx \
+           rings/polynomial/multi_polynomial_libsingular.pyx \
+           rings/polynomial/multi_polynomial_ideal_libsingular.pyx ;
+do
+    f="$SAGE_ROOT/devel/sage/sage/$pyx"
+    if [[ -f "$f" ]]; then
+        echo "  $f"
+        touch "$f"
+    fi
+done
 
