#11706: Make Tachyon build on *64-bit* PPC Linux, too; further fixes, also for Cygwin (see below).
=== tachyon-0.98.9.p5 (William Stein and Leif Leonhardy, August 19th 2011) ===
 * #11706: Make package build on 64-bit PPC Linux, too (by using the `linux-ppc`
   `make` target, which works for ppc64 as well).
 * Check exit codes of `cp`, especially in the last case where the built
   Tachyon executable gets installed. Also use `cp -p` (and `-f`) there, to
   avoid permission issues in multi-user environments.
 * Quote all instances of `$UNAME`.
 * Copy / install `tachyon.exe` (instead of `tachyon`) on Cygwin.
 * Make `spkg-install` executable.
 * Fix all file permissions (see Special Update/Build Instructions).
 * Fix mark-up of headings of changelog entries.
 * Minor cosmetic clean-up.

Excerpt from (the additions to) Special Update/Build Instructions:

 * The upstream files had strange permissions, i.e. some source files
   were executable, while almost all files weren't world-readable.
 * There's seems to be some crap like `tachyon.html.tar.gz` and a few
   `.#*` files I haven't [yet] deleted, since they're not that large.
 * TODO: Check whether building multi-threaded versions on MacOS X
         meanwhile works. (This was said to fail with an old beta.)
 * TODO: Use `patch` instead of copying over pre-patched files.
 * TODO: [Optionally] also install some of the documentation.
 * TODO: I doubt the CFLAGS set for AIX and HP-UX won't get overridden
         by the created Makefile, but that's a minor issue. -leif

diff --git a/build/pkgs/tachyon/spkg-install b/build/pkgs/tachyon/spkg-install
--- a/build/pkgs/tachyon/spkg-install
+++ b/build/pkgs/tachyon/spkg-install
@@ -1,43 +1,61 @@
 #!/usr/bin/env bash
 
-if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+if [ -z "$SAGE_LOCAL" ]; then
+    echo "Error: SAGE_LOCAL undefined - exiting..."
+    echo "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
-cd src/
-
-cp ../patches/main.c demosrc
-
 CUR=`pwd`
-cd unix
 
-cp ../../patches/Make-arch .
-cp ../../patches/Make-config .
+# Copy over pre-patched files:
+cp patches/main.c src/demosrc &&
+cp patches/Make-arch src/unix &&
+cp patches/Make-config src/unix
+if [ $? -ne 0 ]; then
+    echo "Error copying over patched files."
+    exit 1
+fi
+
+cd src/unix
+
 
 finished()
 {
-   if [ $? -ne 0 ]; then
-      echo "Error building Tachyon Ray Tracer"
-      exit 1
-   fi
+    if [ $? -ne 0 ]; then
+        echo "Error building Tachyon Ray Tracer."
+        exit 1
+    fi
 
-   cd "$CUR"
-   cp compile/*/tachyon "$SAGE_LOCAL/bin"
-   exit 0
+    echo "Installing the Tachyon binary..."
+    cd "$CUR"
+    if [ "$UNAME" = CYGWIN ]; then
+        binary_name=tachyon.exe
+    else
+        binary_name=tachyon
+    fi
+    # The '*' is a place-holder for the arch just built (e.g. 'win32' for
+    # Cygwin, other directories won't exist):
+    cp -p -f src/compile/*/"${binary_name}" "$SAGE_LOCAL/bin"
+    if [ $? -ne 0 ]; then
+        echo "Error installing Tachyon Ray Tracer binary (\"${binary_name}\")."
+        exit 1
+    fi
+    exit 0 # Necessary, to not execute further parts of the script!
 }
 
-if [ $UNAME = "CYGWIN" ]; then
+
+if [ "$UNAME" = "CYGWIN" ]; then
     $MAKE win32
     finished
 fi
 
-if [ $UNAME = "Darwin" ]; then
-    #make macosx-thr
+if [ "$UNAME" = "Darwin" ]; then
+    # TODO: This has to be (re)checked for current versions (0.98.9+).
+    # make macosx-thr
     # The threaded version of the 0.98 beta doesn't work on OS X.
     if [ "$SAGE64" = "yes" ]; then
-        echo "Building 64 bit MacOSX"
+        echo "Building a 64-bit version of Tachyon on MacOS X."
         $MAKE macosx-64
     else
         $MAKE macosx
@@ -45,7 +63,7 @@ if [ $UNAME = "Darwin" ]; then
     finished
 fi
 
-if [ $UNAME = "FreeBSD" ]; then
+if [ "$UNAME" = "FreeBSD" ]; then
     # Tachyon doesn't have a threaded option for FreeBSD (though it shouldn't
     # be too difficult to add).  There's no need for an explicit 64-bit
     # version since the only difference is a slight performance optimisation.
@@ -53,33 +71,35 @@ if [ $UNAME = "FreeBSD" ]; then
     finished
 fi
 
-if [ $UNAME = "Linux" ]; then
+if [ "$UNAME" = "Linux" ]; then
     case "`uname -m`" in
-	i?86)
+	i[3456]86)
             $MAKE linux-thr;;
 	ia64)
             $MAKE linux-ia64-thr;;
 	amd64|x86_64)
             $MAKE linux-64-thr;;
-	ppc)
+	ppc|powerpc|ppc64|powerpc64)
             $MAKE linux-ppc;;
         armv7l)
             sed "s/-m32//g" ../../patches/Make-arch > Make-arch
             $MAKE linux-thr;;
-	*) # e.g. ppc64
-            echo "Sorry, your platform isn't supported by Tachyon and/or Sage. Exiting..."
+	*) # e.g. SPARC
+            echo "Error: Sorry, your platform isn't supported by Tachyon and/or Sage. Exiting..."
             exit 1
     esac
     finished
 fi
 
-if [ $UNAME = "SunOS" ]; then
-    if [ "x$SAGE64" = xyes ] ; then
-       # There was nothing suitable for 64-bit mode with
-       # gcc, so I made a new target. David Kirkby, May 2010.
-       $MAKE solaris-pthreads-gcc-64-bit
+if [ "$UNAME" = "SunOS" ]; then
+    if [ "x$SAGE64" = xyes ]; then
+        # There was nothing suitable for 64-bit mode with
+        # gcc, so I made a new target. David Kirkby, May 2010.
+        echo "Building a 64-bit version of Tachyon on Solaris."
+        $MAKE solaris-pthreads-gcc-64-bit
     else
-       $MAKE solaris-pthreads-gcc
+        echo "Building a 32-bit version of Tachyon on Solaris."
+        $MAKE solaris-pthreads-gcc
     fi
     finished
 fi
@@ -99,5 +119,5 @@ if [ "x$UNAME" = xHP-UX ]; then
 fi
 
 
-echo "Tachyon build for $UNAME not implemented (for SAGE) - please complain on sage-devel."
+echo "Error: Tachyon build for $UNAME not implemented (for Sage) - please complain on sage-devel."
 exit 1
