trac 22756: fix python3 build on OS X:
- use clang to compile
- test whether the _scproxy module builds

diff --git a/build/pkgs/python3/spkg-install b/build/pkgs/python3/spkg-install
--- a/build/pkgs/python3/spkg-install
+++ b/build/pkgs/python3/spkg-install
@@ -33,21 +33,23 @@ if [ "$SAGE_VALGRIND" = "yes" ]; then
     PYTHON_CONFIGURE="$PYTHON_CONFIGURE --without-pymalloc"
 fi
 
-if [ `uname` = "Darwin" ]; then
+if [ "$UNAME" = Darwin ]; then
     PYTHON_CONFIGURE="--disable-toolbox-glue $PYTHON_CONFIGURE"
+    if [ $MACOSX_VERSION -ge 16 ]; then
+        echo "OS X 10.$[$MACOSX_VERSION-4] Building with clang."
+        CC=clang
+    fi
+elif [ "$UNAME" = SunOS ]; then
+    # Enable some C99 features on Solaris. This in particular enables
+    # the isinf() and isfinite() functions. It works both for C and
+    # C++ code (which is not true for -std=c99).  See
+    # http://trac.sagemath.org/sage_trac/ticket/14265
+    export CFLAGS="-D__C99FEATURES__ $CFLAGS"
 fi
 
 if [ "$SAGE64" = yes ]; then
     echo "64 bit build of Python enabled"
     export CC="$CC -m64"
-fi
-
-# Enable some C99 features on Solaris. This in particular enables the
-# isinf() and isfinite() functions. It works both for C and C++ code
-# (which is not true for -std=c99).
-# See http://trac.sagemath.org/sage_trac/ticket/14265
-if [ "$UNAME" = SunOS ]; then
-    export CFLAGS="-D__C99FEATURES__ $CFLAGS"
 fi
 
 
@@ -65,6 +67,14 @@ build()
     if [ $? -ne 0 ]; then
         echo >&2 "Error building Python."
         exit 1
+    fi
+
+    # On OS X, test to see if _scproxy built before installing.
+    if [ "$UNAME" = "Darwin" ]; then
+        if [ -z `find build -name _scproxy.so` ]; then
+            echo >&2 "Error: the _scproxy module failed to build."
+            exit 1
+        fi
     fi
 
     # Remove old libraries
@@ -88,7 +98,6 @@ build()
         exit 1
     fi
 }
-
 
 build
 
@@ -131,6 +140,15 @@ for module in ctypes math hashlib crypt readline socket ; do
         import_errors=true
     fi
 done
+
+if [ "$UNAME" = "Darwin" ]; then
+    if python3 -c "import _scproxy"; then
+        echo "_scproxy module imported OK"
+    else
+        echo >&2 "_scproxy module failed to import"
+        import_errors=true
+    fi
+fi
 
 if $import_errors; then
     echo >&2 "Error: One or more modules failed to import."
