Update to jmol 14.2.4_2014.08.03

diff --git a/build/pkgs/jmol/spkg-install b/build/pkgs/jmol/spkg-install
--- a/build/pkgs/jmol/spkg-install
+++ b/build/pkgs/jmol/spkg-install
@@ -14,13 +14,6 @@ if [ ! -d "$SPKGDIR"/patches ]; then
    exit 1
 fi
 
-#no longer needed as of Jmol/JSmol 14+
-#cp "$SPKGDIR"/patches/Jmol.js "$SPKGDIR"/src/jmol/
-#if [ $? -ne 0 ]; then
-#   echo "Error copying Jmol.js patch. Exiting."
-#   exit 1
-#fi
-
 # Check for sagenb location
 if [ ! -d "$SAGE_ROOT/devel/sagenb/sagenb/data/jmol" ]; then
     echo "No old Jmol install in notebook. Skipping removal of Jmol from notebook."
@@ -29,62 +22,62 @@ else
     rm -r "$SAGE_ROOT/devel/sagenb/sagenb/data/jmol"
 fi
 
-if [ ! -d "$SAGE_LOCAL"/share/jmol ]; then
-    echo "Directory "$SAGE_LOCAL"/share/jmol does not exist.  Creating directory..."
-    mkdir "$SAGE_LOCAL/share/jmol"
-else
-    echo "Deleting all files from "$SAGE_LOCAL"/share/jmol/..."
-    rm -r "$SAGE_LOCAL"/share/jmol/*
-    echo "Replacing jmol directory and contents..."
-fi
-
-# "install" the Jmol files...
-cp -r "$SPKGDIR"/src/* "$SAGE_LOCAL"/share/jmol/
-
-#Modified launch script for the Jmol java application 
-#in Sage command line mode.
-cp -f "$SPKGDIR"/patches/jmol "$SAGE_LOCAL"/share/jmol/
-if [ $? -ne 0 ]; then
-   echo "Error copying jmol script patch. Exiting."
-   exit 1
-fi
-
-if [ ! -d "$SAGE_LOCAL"/bin ]; then
-   echo "Directory "$SAGE_LOCAL"/bin does not exist.  Your Sage install is broken. Exiting."
-   exit 1
-else
-    echo "Copying jmol script to $SAGE_LOCAL/bin."
-    cp -f "$SPKGDIR"/patches/jmol "$SAGE_LOCAL"/bin/
-    chmod ugo+x "$SAGE_LOCAL"/bin/jmol
-fi
-
-echo "Installing applet web directory"
-mkdir "$SAGE_LOCAL/share/jmol/appletweb"
-# Not needed for Jmol/JSmol 14+
-#cp "$SPKGDIR"/src/jmol/Jmol.js "$SAGE_LOCAL/share/jmol/appletweb"
-
-if [ ! -d "$SPKGDIR"/patches/appletweb ]; then
-   echo "Error finding patches/appletweb directory. Exiting."
-   exit 1
-fi
-cp -r "$SPKGDIR"/patches/appletweb/* "$SAGE_LOCAL"/share/jmol/appletweb
 
 #pure javascript for web and java applet in separate /share/jsmol directory.
 if [ ! -d "$SAGE_LOCAL"/share/jsmol ]; then
     echo "Directory "$SAGE_LOCAL"/share/jsmol does not exist.  Creating directory..."
-    mkdir "$SAGE_LOCAL/share/jsmol"
+    mkdir -p "$SAGE_LOCAL"/share/jsmol
 else
     echo "Deleting all files from "$SAGE_LOCAL"/share/jsmol/..."
     rm -r "$SAGE_LOCAL"/share/jsmol/*
     echo "Replacing jsmol directory and contents..."
 fi
 
-# "install" the JSmol files...unzip /"$SPKGDIR"/jsmol.zip
-if [ ! -e "$SPKGDIR"/src/jsmol.zip ]; then
-    echo "File "$SPKGDIR"/jsmol.zip does not exist.  Cannot create JSmol (javascript) files. Exiting."
-    exit 1
+echo "Installing the JSmol files..."
+cp -r "$SPKGDIR"/src/jsmol/* "$SAGE_LOCAL"/share/jsmol/
+if [ $? -ne 0 ]; then
+   echo "Error installing jmol files. Exiting."
+   exit 1
 fi
-unzip -q "$SPKGDIR"/src/jsmol.zip -d "$SAGE_LOCAL"/share/
+
+# "install" the Jmol files...
+if [ ! -d "$SAGE_LOCAL"/share/jmol ]; then
+    echo "Directory "$SAGE_LOCAL"/share/jmol does not exist.  Creating directory..."
+    mkdir -p "$SAGE_LOCAL/share/jmol"
+else
+    echo "Deleting all files from "$SAGE_LOCAL"/share/jmol/..."
+    rm -r "$SAGE_LOCAL"/share/jmol/*
+    echo "Replacing jmol directory and contents..."
+fi
+
+# Jsmol is stuck inside the jmol directory, remove
+rm -r "$SPKGDIR"/src/jsmol
+if [ $? -ne 0 ]; then
+   echo "Error removing the contained jsmol files. Exiting."
+   exit 1
+fi
+
+echo "Installing the Jmol files..."
+cp -r "$SPKGDIR"/src/* "$SAGE_LOCAL"/share/jmol/
+if [ $? -ne 0 ]; then
+   echo "Error installing jmol files. Exiting."
+   exit 1
+fi
+
+echo "Overwriting the Jmol launcher..."
+cp -f "$SPKGDIR"/patches/jmol "$SAGE_LOCAL"/share/jmol/ && chmod ugo+x "$SAGE_LOCAL"/bin/jmol
+if [ $? -ne 0 ]; then
+   echo "Error overwriting the jmol launcher. Exiting."
+   exit 1
+fi
+
+echo "Installing applet web directory"
+mkdir -p "$SAGE_LOCAL"/share/jmol/appletweb
+cp -r "$SPKGDIR"/patches/appletweb/* "$SAGE_LOCAL"/share/jmol/appletweb/
+if [ $? -ne 0 ]; then
+   echo "Error installing the applet web directory"
+   exit 1
+fi
 
 if [ $? -ne 0 ]; then
    echo "Error installing Jmol."
