Jmol/JSmol to 14.0.11
Update Jmol and JSmol to 14.0.11 to support pure javascript 3-D plots in
browswers.

diff --git a/build/pkgs/jmol/spkg-install b/build/pkgs/jmol/spkg-install
--- a/build/pkgs/jmol/spkg-install
+++ b/build/pkgs/jmol/spkg-install
@@ -14,23 +14,12 @@ if [ ! -d "$SPKGDIR"/patches ]; then
    exit 1
 fi
 
-cp "$SPKGDIR"/patches/Jmol.js "$SPKGDIR"/src/jmol/
-if [ $? -ne 0 ]; then
-   echo "Error copying Jmol.js patch. Exiting."
-   exit 1
-fi
-
-cp "$SPKGDIR"/patches/jmol "$SPKGDIR"/src/jmol/
-if [ $? -ne 0 ]; then
-   echo "Error copying jmol script patch. Exiting."
-   exit 1
-fi
-
-cp "$SPKGDIR"/patches/testjava.sh "$SPKGDIR"/src/jmol/
-if [ $? -ne 0 ]; then
-   echo "Error adding testjava.sh to jmol directory. Exiting."
-   exit 1
-fi
+#no longer needed as of Jmol/JSmol 14+
+#cp "$SPKGDIR"/patches/Jmol.js "$SPKGDIR"/src/jmol/
+#if [ $? -ne 0 ]; then
+#   echo "Error copying Jmol.js patch. Exiting."
+#   exit 1
+#fi
 
 # Check for sagenb location
 if [ ! -d "$SAGE_ROOT/devel/sagenb/sagenb/data/jmol" ]; then
@@ -50,20 +39,36 @@ else
 fi
 
 # "install" the Jmol files...
-cp -r "$SPKGDIR"/src/jmol/* "$SAGE_LOCAL"/share/jmol/
+cp -r "$SPKGDIR"/src/* "$SAGE_LOCAL"/share/jmol/
+
+#Modified launch script for the Jmol java application 
+#in Sage command line mode.
+cp -f "$SPKGDIR"/patches/jmol "$SAGE_LOCAL"/share/jmol/
+if [ $? -ne 0 ]; then
+   echo "Error copying jmol script patch. Exiting."
+   exit 1
+fi
+
+#shell script to check for JVM
+cp "$SPKGDIR"/patches/testjava.sh "$SAGE_LOCAL"/share/jmol/
+if [ $? -ne 0 ]; then
+   echo "Error adding testjava.sh to jmol directory. Exiting."
+   exit 1
+fi
 
 if [ ! -d "$SAGE_LOCAL"/bin ]; then
    echo "Directory "$SAGE_LOCAL"/bin does not exist.  Your Sage install is broken. Exiting."
    exit 1
 else
     echo "Copying jmol script to $SAGE_LOCAL/bin."
-    cp -f "$SPKGDIR"/src/jmol/jmol "$SAGE_LOCAL"/bin/
+    cp -f "$SPKGDIR"/patches/jmol "$SAGE_LOCAL"/bin/
     chmod ugo+x "$SAGE_LOCAL"/bin/jmol
 fi
 
 echo "Installing applet web directory"
 mkdir "$SAGE_LOCAL/share/jmol/appletweb"
-cp "$SPKGDIR"/src/jmol/Jmol.js "$SAGE_LOCAL/share/jmol/appletweb"
+# Not needed for Jmol/JSmol 14+
+#cp "$SPKGDIR"/src/jmol/Jmol.js "$SAGE_LOCAL/share/jmol/appletweb"
 
 if [ ! -d "$SPKGDIR"/patches/appletweb ]; then
    echo "Error finding patches/appletweb directory. Exiting."
@@ -71,6 +76,22 @@ if [ ! -d "$SPKGDIR"/patches/appletweb ]; then
 fi
 cp -r "$SPKGDIR"/patches/appletweb/* "$SAGE_LOCAL"/share/jmol/appletweb
 
+#pure javascript for web and java applet in separate /share/jsmol directory.
+if [ ! -d "$SAGE_LOCAL"/share/jsmol ]; then
+    echo "Directory "$SAGE_LOCAL"/share/jsmol does not exist.  Creating directory..."
+    mkdir "$SAGE_LOCAL/share/jsmol"
+else
+    echo "Deleting all files from "$SAGE_LOCAL"/share/jsmol/..."
+    rm -r "$SAGE_LOCAL"/share/jsmol/*
+    echo "Replacing jsmol directory and contents..."
+fi
+
+# "install" the JSmol files...unzip /"$SPKGDIR"/jsmol.zip
+if [ ! -e "$SPKGDIR"/src/jsmol.zip ]; then
+    echo "File "$SPKGDIR"/jsmol.zip does not exist.  Cannot create JSmol (javascript) files. Exiting."
+    exit 1
+fi
+unzip -q "$SPKGDIR"/src/jsmol.zip -d "$SAGE_LOCAL"/share/
 
 if [ $? -ne 0 ]; then
    echo "Error installing Jmol."
