When nodejs installed, activate its nodeenv in sage-env

diff --git a/build/pkgs/nodejs/spkg-install b/build/pkgs/nodejs/spkg-install
--- a/build/pkgs/nodejs/spkg-install
+++ b/build/pkgs/nodejs/spkg-install
@@ -28,6 +28,12 @@ if [ ! -f "$nodeenv_activate" ]; then
 fi
 
 . "$nodeenv_activate"
+
+if [ $? -ne 0 ]; then
+    echo "Error activating nodeenv containing nodejs ... exiting"
+    exit 1
+fi
+
 active_ver=`node --version | grep -oP "\d+\.\d+\.\d+"`
 
 if [ $? -ne 0 ]; then
@@ -43,3 +49,5 @@ if [ ! "$nodejs_ver" = "$active_ver" ]; then
     echo "Expected $nodejs_ver but found $active_ver"
     exit 1
 fi
+
+ln -sf "$nodeenv_activate" "$SAGE_LOCAL/share/nodejs/activate"
diff --git a/src/bin/sage-env b/src/bin/sage-env
--- a/src/bin/sage-env
+++ b/src/bin/sage-env
@@ -669,3 +669,15 @@ fi
 # tell it where to find it. See Trac Ticket #15091
 
 export TERMINFO="$SAGE_LOCAL/share/terminfo"
+
+# If nodejs is installed, activate the nodeenv containing it.
+
+nodeenv_activate=`resolvelinks "$SAGE_LOCAL/share/nodejs/activate"`
+
+if [ -f "$nodeenv_activate" ]; then
+    . "$nodeenv_activate"
+
+    if [ $? -ne 0 ]; then
+        echo >&2 "Warning: failed to activate the nodeenv containing nodejs"
+    fi
+fi
