improved spkg-install

diff --git a/build/pkgs/ets/spkg-install b/build/pkgs/ets/spkg-install
--- a/build/pkgs/ets/spkg-install
+++ b/build/pkgs/ets/spkg-install
@@ -1,6 +1,52 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+if [ "$SAGE_LOCAL" = "" ]; then
+   echo "SAGE_LOCAL undefined ... exiting";
+   echo "Maybe run 'sage -sh'?"
+   exit 1
+fi
+
+
+# check wether dependencies are installed
+
+Package=vtk-5.2
+Package_installed=`cd $SAGE_ROOT/spkg/installed/; ls $Package`
+if [ $? -ne 0 ]; then
+    echo "Failed to find $Package  Please install the $Package spkg"
+    exit 1
+fi
+
+Package=wxPython-2.8.9.1
+Package_installed=`cd $SAGE_ROOT/spkg/installed/; ls $Package`
+if [ $? -ne 0 ]; then
+    echo "Failed to find $Package  Please install the $Package spkg"
+    exit 1
+fi
+
+Package=reportlab-2.2
+Package_installed=`cd $SAGE_ROOT/spkg/installed/; ls $Package`
+if [ $? -ne 0 ]; then
+    echo "Failed to find $Package  Please install the $Package spkg"
+    exit 1
+fi
+
+Package=pil-1.1.6
+Package_installed=`cd $SAGE_ROOT/spkg/installed/; ls $Package`
+if [ $? -ne 0 ]; then
+    echo "Failed to find $Package  Please install the $Package spkg"
+    exit 1
+fi
+
+Package=swig-1.3.31
+Package_installed=`cd $SAGE_ROOT/spkg/installed/; ls $Package`
+if [ $? -ne 0 ]; then
+    echo "Failed to find $Package  Please install the $Package spkg"
+    exit 1
+fi
 
 cd src
+
+# Work around the way numpy is installed
 
 echo "Creating ~/.numpy-site.cfg"
 
