Upgrade meataxe spkg to SharedMeatAxe 1.0 (dynamic library)

diff --git a/build/pkgs/meataxe/spkg-install b/build/pkgs/meataxe/spkg-install
--- a/build/pkgs/meataxe/spkg-install
+++ b/build/pkgs/meataxe/spkg-install
@@ -1,20 +1,12 @@
-if [ -z "$SAGE_LOCAL" ]; then
-    echo >&2 "SAGE_LOCAL undefined ... exiting"
-    echo >&2 "Maybe run 'sage --sh'?"
-    exit 1
-fi
-
 cd src
-
-## The following *could* be put into Makefile.conf
 
 # This is the place where arithmetic tables and some other input files are
 # searched by default.
-export MTXLIB="$DOT_SAGE/meataxe"
+export MTXLIB="$DOT_SAGE"/meataxe
+
 # Directory where executables are installed.
-export MTXBIN="$SAGE_LOCAL/bin"
-# Default compiler flags
-export CFLAGS1="-std=gnu99 -O -Wall -fPIC"
+export MTXBIN="$SAGE_LOCAL"/bin
+
 # Field size up to GF(256)
 export ZZZ=0
 
@@ -22,62 +14,27 @@ export ZZZ=0
 # But upstream doesn't provide the required sources.
 #export ZZZ=1
 
-# The following is just to make MeatAxe's Makefile happy
-touch Makefile.conf
-
 # We create a directory for the multiplication tables
 mkdir -p $MTXLIB
 
 if [ $? -ne 0 ]; then
-    echo >&2 "Error creating directory for multiplication tables."
+    echo >&2 "Error creating directory for ultiplication tables."
     exit 1
 fi
 
-## Install! Aparently MeatAxe would rebuild everything when
-## testing, and "make check" also installs. So, if a test
-## is requested then we do it in one go.
+# We delete a static meataxe library that might be leftover
+# from installation of MeatAxe (as opposed to SharedMeatAxe).
+rm -f "$SAGE_LOCAL"/lib/libmtx.a
 
-if [ "x$SAGE_CHECK" = xyes ]; then
-    $MAKE check
-else
-    $MAKE
-fi
+sdh_configure
+sdh_make
+sdh_make_install
 
-if [ $? -ne 0 ]; then
-    echo >&2 "Error installing MeatAxe."
-    exit 1
-fi
-
-## Surprisingly, MeatAxe's Makefile does NOT install the binaries
-## in MTXBIN. Hence, we do it manually.
-
-mv bin/* "$MTXBIN"
-if [ $? -ne 0 ]; then
-    echo >&2 "Error copying MeatAxe executables."
-    exit 1
-fi
-
-# We move the meataxe library to a permanent location
-mv tmp/libmtx.a "$SAGE_LOCAL/lib"
-if [ $? -ne 0 ]; then
-    echo >&2 "Error copying MeatAxe library."
-    exit 1
-fi
-
-cp src/meataxe.h "$SAGE_LOCAL/include/"
-if [ $? -ne 0 ]; then
-    echo >&2 "Error copying MeatAxe header."
-    exit 1
-fi
-
-# Are we supposed to install the documentation?
 if [ "x$SAGE_SPKG_INSTALL_DOCS" = xyes ] ; then
-    mkdir -p $SAGE_SHARE/doc/meataxe/
-    cp -r doc/* $SAGE_SHARE/doc/meataxe/
-    if [ $? -ne 0 ]; then
-        echo "Error copying documentation."
-        exit 1
-    else
-        echo "The documentation can be found in $SAGE_SHARE/doc/meataxe/"
-    fi
+    $MAKE doc
+if [ $? -ne 0 ]; then
+    echo >&2 "Error documenting SharedMeatAxe."
+    exit 1
 fi
+fi
+
