gdbm-1.8.3: fixed issue with Makefile.in in wrong place and fixed spkg-install permissions

diff --git a/build/pkgs/gdbm/spkg-install b/build/pkgs/gdbm/spkg-install
--- a/build/pkgs/gdbm/spkg-install
+++ b/build/pkgs/gdbm/spkg-install
@@ -6,7 +6,11 @@ if [ "$SAGE_LOCAL" = "" ]; then
    exit 1
 fi
 
-cp Makefile.in src/
+cp patches/Makefile.in src/
+if [ $? -ne 0 ]; then
+   echo "Error copying Makefile for gdbm."
+   exit 1
+fi
 
 cd src
 
