Minor fixes to spkg-install

diff --git a/build/pkgs/openblas/spkg-install b/build/pkgs/openblas/spkg-install
--- a/build/pkgs/openblas/spkg-install
+++ b/build/pkgs/openblas/spkg-install
@@ -6,8 +6,18 @@ if [ -z "$SAGE_LOCAL" ]; then
     exit 1
 fi
 
-PKG_DIR=$(pwd)
 cd xianyi-OpenBLAS*
+
+# Patch sources
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
 
 if [ "x$SAGE_DEBUG" = "xyes" ]; then
     OPENBLAS_CONFIGURE="$OPENBLAS_CONFIGURE DEBUG=1"
@@ -18,19 +28,20 @@ if [ "x$SAGE_FAT_BINARY" = "xyes" ]; then
     OPENBLAS_CONFIGURE="$OPENBLAS_CONFIGURE TARGET=PRESCOTT"
 fi
 
-echo "Building OpenBLAS: make $OPENBLAS_CONFIGURE"
+echo "Building OpenBLAS: $MAKE $OPENBLAS_CONFIGURE"
 
 $MAKE $OPENBLAS_CONFIGURE
 if [ $? -ne 0 ]; then
-    echo "Error building OpenBLAS"
+    echo >&2 "Error building OpenBLAS"
+    exit 1
 fi
 
-$MAKE install PREFIX="$SAGE_LOCAL" NO_STATIC=1
+$MAKE install PREFIX="$SAGE_LOCAL" NO_STATIC=1 $OPENBLAS_CONFIGURE
 if [ $? -ne 0 ]; then
-    echo "Error installing OpenBLAS"
+    echo >&2 "Error installing OpenBLAS"
     exit 1
 fi
 
 
-cd "$PKG_DIR"
+cd ..
 ./write_pc_file.py
