Add hg update when pulling as part of the install

diff --git a/src/spkg-install b/src/spkg-install
--- a/src/spkg-install
+++ b/src/spkg-install
@@ -29,9 +29,16 @@ if [ -d "$DEVEL/sage-main" ]; then
     cd "$DEVEL/sage-main"
     hg pull "$SAGE_SERVER"/hg/sage-main
     if [ $? -ne 0 ]; then
-        echo "Error pulling in new SAGE source code using hg."
+        echo "Error pulling in new SAGE source code."
         exit 1
     fi
+    # Make the pulled in changes take effect.
+    hg update
+    if [ $? -ne 0 ]; then
+        echo "Error applying pulled in changes to new SAGE source code."
+        exit 1
+    fi
+
     "$SAGE_ROOT/sage" -b main
     if [ $? -ne 0 ]; then
         echo "Error building new version of SAGE."
