updates spkg-install to install python api

diff --git a/build/pkgs/gambit/spkg-install b/build/pkgs/gambit/spkg-install
--- a/build/pkgs/gambit/spkg-install
+++ b/build/pkgs/gambit/spkg-install
@@ -19,3 +19,12 @@ if [ $? -ne 0 ]; then
     echo >&2 "Error installing Gambit."
     exit 1
 fi
+
+cd src/python
+python setup.py build
+python setup.py install
+
+if [ $? -ne 0 ]; then
+    echo "Error installing Cython"
+    exit 1
+fi
