#9312 Fix GLPK spkg for SAGE64 (But I actually done a lot more)
 * Updated to the latest upstream code, version 4.44.
 * Added code to allow a 64-bit build on any platform.
   If SAGE64 is set to "yes", the compiler flag -m64 is added
   by default. That flag works with GCC and SunStudio, but not
   all compilers - IBM's compiler for AIX and HP's for HP-UX
   both use different flags to create a 64-bit build.
   If the compiler does not use -m64 for 64-bit builds, then
   the environment variable CFLAG64 can be set to indicate what
   flag gets added.
 * Added a file spkg-check so the self-test code is built.
   This includes code which will add the appropriate flag
   for 64-bit builds if the test procedures need code to be
   compiled. (Sometimes running 'make test' actually needs
   the compiler flags set properly, so I do it just in case.
   It appears to be unnecessary with this version of GLPK,
   but might with later releases.
 * Added the configure option --with-gmp which will speed up
   processing of large integers (see src/INSTALL)
 * Added the configure option --disable-static since there is
   no need to build static libraries. (see src/INSTALL)
 * Added the configure option --with-zlib. Adding this allows
   GLPK API routines and the stand-alone solver to read and
   write compressed data files performing compression and
   decompression "on the fly" (see src/INSTALL)
 * Removed linking of the 'ld' library in spkg-install, as the
   reason for it being added was not clear.
 * Corrected SPKG.txt to indicate this code is GPL 3.
   (see src/COPYING)
 * Added the ChangeLog section to the SPKG.txt file
 * Added zlib, python and mpir as dependencies in SPKG.txt
 * Checked that the configure script actually does configure
   properly, if not exits.
 * Checked that 'make' does build the code properly, if not exits.
 * Checked that 'make install' does actually install the library
 * Checked that running 'python setup.py install' does actually work.
   If this is not done, code can appear to install properly as it
   passes 'configure', 'make' and 'make install'. So unusually there
   are 4 cases where spkg-install can fail.
 * The 'patch' directory is left - I think this should be removed
   but I'll leave it to those that know the software better
   than me to mess with this.

diff --git a/build/pkgs/glpk/spkg-install b/build/pkgs/glpk/spkg-install
--- a/build/pkgs/glpk/spkg-install
+++ b/build/pkgs/glpk/spkg-install
@@ -4,26 +4,67 @@ if [ "$SAGE_LOCAL" = "" ]; then
    exit 1
 fi
 
-
 # The version of libtool in this glpk package requires that
 # RM/MV/CP if they are set include the -f option
 # See for example the discussion at:
 # http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=523750
 
-: ${CP=cp}; CP="$CP -f"; export CP
-: ${MV=mv}; MV="$MV -f"; export MV
-: ${RM=rm}; RM="$RM -f"; export RM
+# It was agreed some time back to remove these environment variables.
+# nobody in their right mind will want to set them.
 
-cd src &&
-LIBS=-ldl ./configure --prefix=$SAGE_LOCAL &&
-make prefix=$SAGE_LOCAL &&
-make install &&
-cd .. &&
-python setup.py install &&
-echo "********************************************************************************" &&
-echo "" &&
-echo "    ATTENTION: YOU HAVE TO REBUILD THE SAGE LIBRARY TO GET THIS TO WORK" &&
-echo "    exit any running sage instances and call \"sage -b\"" &&
-echo "" &&
-echo "********************************************************************************"
+unset MV && export MV
+unset RM && export RM
+unset CP && export CP
+
+# Let the user set an environment variable CFLAG64 to indicate the flag
+# for the C compiler to build 64-bit code. If not set, asssume it is -m64
+# as that is what is used by both GCC and SunStudio, but -m64 is not used
+# by IBM's compiler on AIX or HP's compiier on HP-UX
+
+if [ -z $CFLAG64 ] ; then
+  CFLAG64=-m64 # -m64 is used by gcc and SunStudio.
+fi
+
+CPPFLAGS="-I $SAGE_LOCAL/include" && export CPPFLAGS
+LDFLAGS="-L$SAGE_LOCAL/lib" &&  export LDFLAGS
+
+if [ "x$SAGE64" = xyes ] ; then
+   echo "Building a 64-bit version of GLPK"
+   CFLAGS="$CFLAGS $CFLAG64" && export CFLAGS
+   LDFLAGS="$LDFLAGS $CFLAG64" && export LDFLAGS
+   CPPFLAGS="$CPPFLAGS $CFLAG64" && export CPPLFLAGS
+   # Very rarly is it needed to add '-m64' to CPPFLAGS,
+   # but potentially it can be.
+fi
+
+cd src
+
+./configure --prefix=$SAGE_LOCAL --with-gmp --with-zlib --disable-static
+
+if [ $? -ne 0 ]; then
+    echo "An error occured whilst configuring GLPK"
+    exit 1
+fi
+
+$MAKE
+if [ $? -ne 0 ]; then
+    echo "An error occured whilst building GLPK"
+    exit 1
+fi
+
+# There are two cases where this can fail to install - at the point of
+# installing the C source code and at the point of using Python.
+
+$MAKE install
+if [ $? -ne 0 ]; then
+    echo "An error occured whilst installing GLPK (during the \"make install\" process)"
+    exit 1
+fi
+cd ..
+
+python setup.py install
+if [ $? -ne 0 ]; then
+    echo "An error occured whilst installing GLPK (during the \"python setup.py install\" process)"
+    exit 1
+fi
 
