Update to gcc-4.8.3, add OSX 10.10 patch

diff --git a/build/pkgs/gcc/spkg-install b/build/pkgs/gcc/spkg-install
--- a/build/pkgs/gcc/spkg-install
+++ b/build/pkgs/gcc/spkg-install
@@ -6,12 +6,25 @@ if [ -z "$SAGE_LOCAL" ]; then
     exit 1
 fi
 
+# Apply fixes to upstream source
+echo "Applying patches..."
+cd src
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    echo "Using $patch"
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
 # Exit on error
 set -e
 
 # Build in a separate directory, not in src/ (a.k.a. a VPATH build).
 # This is the recommended way to build GCC.
+cd ..
 mkdir gcc-build
 cd gcc-build
 
