/usr/bin/env bash;  change == to =; add support for cygwin; improve error messages and checking

diff --git a/build/pkgs/readline/spkg-install b/build/pkgs/readline/spkg-install
--- a/build/pkgs/readline/spkg-install
+++ b/build/pkgs/readline/spkg-install
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env bash
 ###########################################
 ## Readline 5.2
 ###########################################
@@ -20,18 +20,29 @@ build()
 
 build
 
-if [ `uname` == 'Darwin' ]; then
+if [ $? -ne 0 ]; then
+    echo "Error building and installing readline."
+    exit 1
+fi
+
+if [ $UNAME = "Darwin" ]; then
   DYLIB_NAME=$SAGE_LOCAL/lib/libreadline.dylib
+elif [ $UNAME = "CYGWIN" ]; then
+  # It is of course very lame that readline names the file .dll.a, but that's what it does.
+  DYLIB_NAME=$SAGE_LOCAL/lib/libreadline.dll.a
 else
   DYLIB_NAME=$SAGE_LOCAL/lib/libreadline.so
 fi
 
+# Make sure that the install worked, despite whatever the error
+# code of build was.
 if [ -f $DYLIB_NAME -a -f $SAGE_LOCAL/lib/libreadline.a ]; then
+  # Fix permissions.
   chmod 755 $SAGE_LOCAL/lib/libreadline.*
   chmod 755 $SAGE_LOCAL/lib/libhistory.*
   exit 0
 else
-  echo "Error building readline"
+  echo "Readline's build claims to have finished, but files that should have been built weren't."
   exit 1
 fi
 
