switch to ncurses

diff --git a/build/pkgs/readline/spkg-install b/build/pkgs/readline/spkg-install
--- a/build/pkgs/readline/spkg-install
+++ b/build/pkgs/readline/spkg-install
@@ -165,7 +165,11 @@ for patch in ../patches/*.patch; do
 done
 
 echo "Configuring readline..."
-./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib"
+./configure \
+    --prefix="$SAGE_LOCAL" \
+    --libdir="$SAGE_LOCAL/lib" \
+    --with-curses \
+    --enable-shared --disable-static
 if [[ $? -ne 0 ]]; then
     echo >&2 "Error configuring readline."
     exit 1
@@ -215,21 +219,13 @@ esac
 
 # Make sure that the install worked, despite whatever the
 # exit code of 'make' or 'make install' was:
-if [[ -f "$SAGE_LOCAL/lib/$DYLIB_NAME" && -f "$SAGE_LOCAL"/lib/libreadline.a ]]; then
-    # Both the shared and the static library are present, i.e.
-    # have successfully been (re)installed.
-    # Fix permissions:
+if [[ -f "$SAGE_LOCAL/lib/$DYLIB_NAME" ]]; then
     echo "Fixing permissions of libraries..."
     chmod 755 "$SAGE_LOCAL"/lib/libreadline.*
     chmod 755 "$SAGE_LOCAL"/lib/libhistory.*
-    # It's pretty wrong to also make the static library executable:
-    chmod 644 "$SAGE_LOCAL"/lib/lib{readline,history}.a
-    exit 0
 else
     # One or both of the readline libraries are missing, i.e.
     # haven't been installed.
-    echo >&2 "Error: Readline's build claims to have finished, but files"
-    echo >&2 "that should have been built and installed weren't."
-    echo >&2 "(In particular, libreadline.a or $DYLIB_NAME, or both.)"
+    echo >&2 "Error: Readline's build claims to have finished, but $DYLIB_NAME was not installed.)"
     exit 1
 fi
