#9523 Upgrade the Readline spkg to 6.1 cleaning up where necessary

diff --git a/build/pkgs/readline/spkg-install b/build/pkgs/readline/spkg-install
--- a/build/pkgs/readline/spkg-install
+++ b/build/pkgs/readline/spkg-install
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 ###########################################
-## Readline 6.0
+## Readline 6.1
 ###########################################
 
 if [ -z "$SAGE_LOCAL" ]; then
@@ -9,156 +9,49 @@ if [ -z "$SAGE_LOCAL" ]; then
     exit 1
 fi
 
-set -e
+if [ "x$CFLAG64" = x ] ; then
+   CFLAG64=-m64
+fi
 
-# Add a sensible default optimisation flag. Change if necessary.
-OPTIMIZATION_FLAGS="-O2"
-
-# Most packages do not need all these set.
-# But it is better to do them all each time, rather than omit
-# a flag by mistake.
-
-CFLAGS="$CFLAGS $OPTIMIZATION_FLAGS "
-CXXFLAGS="$CXXFLAGS $OPTIMIZATION_FLAGS "
-FCFLAGS="$FCFLAGS $OPTIMIZATION_FLAGS "
-F77FLAGS="$F77FLAGS $OPTIMIZATION_FLAGS "
-#CPPFLAGS="$CPPFLAGS -I$SAGE_LOCAL/include"
-#LDFLAGS="$LDFLAGS -L$SAGE_LOCAL/lib"
-
-# Compile for 64-bit if SAGE64 is set to 'yes' or '1'
-if [ "x$SAGE64" = "xyes" ] || [ "x$SAGE64" = "x1" ]  ; then
+# Compile for 64-bit if SAGE64 is set to 'yes'
+if [ "x$SAGE64" = xyes ] ; then
    echo "Building a 64-bit version of Readline"
-   CFLAGS="$CFLAGS -m64 "
-   CXXFLAGS="$CXXFLAGS -m64 "
-   FCFLAGS="$FCFLAGS -m64 "
-   F77FLAGS="$F77FLAGS -m64 "
+   CFLAGS="$CFLAGS $CFLAG64"
+   CPPFLAGS="$CPPFLAGS $CFLAG64"
    # Some packages may need LDFLAGS and/or ABI set here.
-   LDFLAGS="$LDFLAGS -m64 "
-   # ABI=64
+   LDFLAGS="$LDFLAGS $CFLAG64"
+fi
+
+if [ "x$SAGE_DEBUG" = "xyes" ] ; then
+   CFLAGS="$CFLAGS -g -O0"
 else
-   echo "Building a 32-bit version of Readline"
-fi
-
-# If SAGE_DEBUG is set either unset (the default), or set to  'yes'
-# then add debugging information.
-# Since both the Sun and GNU compilers accept -g to give debugging information,
-# there is no need to do anything specific to one compiler or the other.
-
-if [ "x$SAGE_DEBUG" = "x" ] || [ "x$SAGE_DEBUG" = "xyes" ] ; then
-   echo "Code will be built with debugging information present. Set 'SAGE_DEBUG' to 'no' if you don't want that."
-   # Actually anything other than 'yes' or '1' will cause
-   # no debugging information to be added.
-   CFLAGS="$CFLAGS -g "
-   CXXFLAGS="$CXXFLAGS -g "
-   FCFLAGS="$FCFLAGS -g "
-   F77FLAGS="$F77FLAGS -g "
-else
-   echo "No debugging information will be used during the build of this package."
-   echo "Unset SAGE_DEBUG if you want debugging information present (-g added)."
-fi
-
-# Add appropriate flag(s) to show all warnings.
-# This test of a compiler is not perfect by any means, but
-# is better than nothing.
-if "$CC" -flags > /dev/null 2>&1 ; then
-   SUN_COMPILER=1
-   # The Sun compilers are fussy, and adding extra
-   # warnings will just show too many.
-else
-   # Assume gcc if not the Sun C compiler.
-   # Add -Wall to show all warnings.
-   CFLAGS="$CFLAGS -Wall "
-   CXXFLAGS="$CXXFLAGS -Wall "
-   FCFLAGS="$FCFLAGS -Wall "
-   F77FLAGS="$F77FLAGS -Wall "
-   GNU_COMPILER=1
-fi
-
-# Determine if the C++ compiler is the Sun or GNU compiler.
-# Just to check we are not mixing GNU and non-GNU.
-if "$CXX" -flags > /dev/null 2>&1 ; then
-   SUN_COMPILER=1
-else
-   GNU_COMPILER=1
-fi
-
-
-# Determine if the Fortran compiler is the Sun or GNU compiler.
-if [ -z "$SAGE_FORTRAN" ] ; then
-   echo "No Fortran compiler has been defined. This is not normally a problem."
-else
-   if "$SAGE_FORTRAN" -flags > /dev/null 2>&1 ;  then
-      SUN_COMPILER=1
-   else
-      GNU_COMPILER=1
-   fi
-fi
-
-# Check if SAGE_FORTRAN_LIB is defined, that the file actually exists.
-# SAGE_FORTRAN_LIB does not always need to be defined, but if it is defined, then
-# the file should exist.
-
-if [ -n "$SAGE_FORTRAN_LIB" ] &&  [ ! -e "$SAGE_FORTRAN_LIB" ]; then
-   echo "SAGE_FORTRAN_LIB is defined as $SAGE_FORTRAN_LIB, but does not exist."
-   exit 1
-fi
-
-# Checks that the user is not mixing the Sun and GNU compilers. This problem
-# has been seen on code built with the aid of SCons, but in general could
-# happen with any code if the user has specified a C compiler but not a C++ one.
-# This problem is even more likely to occur with the Fortran compiler - I've done
-# it myself when building Sage!
-
-if [ "x$SUN_COMPILER" = "x1" ] && [ "x$GNU_COMPILER" = "x1" ] ; then
-   echo "You are mixing the Sun and GNU C/C++/Fortran compilers."
-   echo "Such a combination will lead to problems."
-   echo "Check CC, CXX & SAGE_FORTRAN carefully."
-   echo "Exiting ..."
-   exit 1
+   CFLAGS="$CFLAGS -g -O2"
 fi
 
 # These are all used by GNU to specify compilers.
 echo "Using CC=$CC"
-echo "Using CXX=$CXX"
-echo "Using FC=$FC"
-echo "Using F77=$F77"
 
-# Used by Sage in connection with Fortran.
-echo "Using SAGE_FORTRAN=$SAGE_FORTRAN"
-echo "Using SAGE_FORTRAN_LIB=$SAGE_FORTRAN_LIB"
 
 # Flags which may be set.
 echo "The following environment variables will be exported."
 echo "Using CFLAGS=$CFLAGS"
-echo "Using CXXFLAGS=$CXXFLAGS"
-echo "Using FCFLAGS=$FCFLAGS"
-echo "Using F77FLAGS=$F77FLAGS"
 echo "Using CPPFLAGS=$CPPFLAGS"
 echo "Using LDFLAGS=$LDFLAGS"
-echo "Using ABI=$ABI"
 echo "configure scripts and/or makefiles might override these later"
 echo " "
 
-# export everything. Probably not necessary in most cases.
 export CFLAGS
-export CXXFLAGS
-export FCFLAGS
-export F77FLAGS
 export CPPFLAGS
 export LDFLAGS
-export ABI
 
 # End of pretty general spkg-install file.
 # Now do the specific things needed for this package (Readline)
 
-
-echo "Deleting old readline headers and libs"
+echo "Deleting old readline headers and libs..."
 rm -rf "$SAGE_LOCAL"/include/readline/
 rm -rf "$SAGE_LOCAL"/lib/libreadline.*
 
 # OVERWRITE_READLINE=false; export OVERWRITE_READLINE
-
-set +e # We want the exit codes!
 
 # First we check for OpenSUSE 11.x, since there bash is linked dynamically with a
 # more recent readline such that bash crashes when we build Sage's readline, so
@@ -249,23 +142,23 @@ fi
 
 cd src/
 
-build()
-{
-    ./configure --prefix="$SAGE_LOCAL" $CONF_FLAGS
-    if [ $? -ne 0 ]; then
-        echo "Error configuring readline."
-        exit 1
-    fi
-    make install
-}
-
-build
+./configure --prefix="$SAGE_LOCAL"
 if [ $? -ne 0 ]; then
-    echo "Error building and installing readline."
+  echo "Error configuring readline."
+  exit 1
+fi
+
+$MAKE
+if [ $? -ne 0 ]; then
+    echo "Error building readline."
     exit 1
 fi
 
-set -e
+$MAKE install
+if [ $? -ne 0 ]; then
+    echo "Error installing readline."
+    exit 1
+fi
 
 if [ "$UNAME" = "Darwin" ]; then
   DYLIB_NAME="$SAGE_LOCAL"/lib/libreadline.dylib
@@ -273,7 +166,7 @@ elif [ "$UNAME" = "CYGWIN" ]; then
   # It is of course very lame that readline names the file .dll.a, but that's what it does.
   DYLIB_NAME="$SAGE_LOCAL"/lib/libreadline.dll.a
 elif [ "$UNAME" = "OpenBSD" ]; then
-  DYLIB_NAME="$SAGE_LOCAL"/lib/libreadline.so.6.0
+  DYLIB_NAME="$SAGE_LOCAL"/lib/libreadline.so.6.1  # Untested. David Kirkby, 11th November 2010
 elif [ "$UNAME" = "FreeBSD" ]; then
   DYLIB_NAME="$SAGE_LOCAL"/lib/libreadline.so.6
 elif [ "$UNAME" = "HP-UX" ]; then
@@ -281,17 +174,6 @@ elif [ "$UNAME" = "HP-UX" ]; then
 else
   DYLIB_NAME="$SAGE_LOCAL"/lib/libreadline.so
 fi
-
-# # We only enter this block on openSUSE 11.1.
-# if [ $OVERWRITE_READLINE = "true" ]; then
-#   echo "Overwriting libreadline.so.6.0 with the system one."
-#   rm -f $SAGE_LOCAL/lib/libreadline.so.6.0
-#   if [ `uname -p` = "x86_64" ]; then
-#     cp /lib64/libreadline.so.* $SAGE_LOCAL/lib
-#   else
-#     cp /lib/libreadline.so.* $SAGE_LOCAL/lib
-#   fi
-# fi
 
 # Make sure that the install worked, despite whatever the error
 # code of build was.
