#7821: readline-6.0.p1 fails on FreeBSD

diff --git a/build/pkgs/readline/spkg-install b/build/pkgs/readline/spkg-install
--- a/build/pkgs/readline/spkg-install
+++ b/build/pkgs/readline/spkg-install
@@ -197,6 +197,12 @@ if [ $UNAME = "Linux" -a -n "`uname -r | grep ARCH`" ]; then
 fi
 
 
+cp patches/shobj-conf src/support/
+if [ $? -ne 0 ]; then
+    echo "Error copying patch over."
+    exit 1
+fi
+
 cd src/
 
 build()
@@ -245,10 +251,6 @@ if [ -f "$DYLIB_NAME" -a -f "$SAGE_LOCAL"/lib/libreadline.a ]; then
   # Fix permissions.
   chmod 755 "$SAGE_LOCAL"/lib/libreadline.*
   chmod 755 "$SAGE_LOCAL"/lib/libhistory.*
-  if [ "$UNAME" = "FreeBSD" ]; then
-    ln -s libreadline.so.6 $"SAGE_LOCAL"/lib/libreadline.so
-    ln -s libhistory.so.6 "$SAGE_LOCAL"/lib/libhistory.so
-  fi
   exit 0
 else
   echo "Readline's build claims to have finished, but files that should have been built weren't."
