Trac #14699: Cleanup spkg, restore upstream sources

diff --git a/build/pkgs/iml/spkg-check b/build/pkgs/iml/spkg-check
--- a/build/pkgs/iml/spkg-check
+++ b/build/pkgs/iml/spkg-check
@@ -1,24 +1,27 @@
 #!/usr/bin/env bash
 
-if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
-fi
-
-if [ "$SAGE64" = "yes" ]; then
-   CFLAGS="-O2 -g -m64 "; export CFLAGS
-   CPPFLAGS="-O2 -g -m64 "; export CPPFLAGS
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage -sh'?"
+    exit 1
 fi
 
 cd src
 
-echo "Testing the IML library"
-
-make check
-
-if [ $? -ne 0 ]; then
-    echo "Error testing IML"
-    exit 1
+if [ "$SAGE_DEBUG" = "yes" ]; then
+    export CFLAGS="-O0 -g $CFLAGS"
+else
+    export CFLAGS="-O2 -g $CFLAGS"
 fi
 
+if [ "$SAGE64" = "yes" ]; then
+    CFLAGS="-m64 $CFLAGS"
+fi
+
+
+echo "Testing the IML library"
+$MAKE check
+if [ $? -ne 0 ]; then
+    echo >&2 "Error testing IML."
+    exit 1
+fi
diff --git a/build/pkgs/iml/spkg-install b/build/pkgs/iml/spkg-install
--- a/build/pkgs/iml/spkg-install
+++ b/build/pkgs/iml/spkg-install
@@ -1,43 +1,63 @@
 #!/usr/bin/env bash
 
-if [ "$SAGE_LOCAL" = "" ]; then
-   echo "SAGE_LOCAL undefined ... exiting";
-   echo "Maybe run 'sage -sh'?"
-   exit 1
+if [ -z "$SAGE_LOCAL" ]; then
+    echo >&2 "SAGE_LOCAL undefined ... exiting"
+    echo >&2 "Maybe run 'sage --sh'?"
+    exit 1
 fi
-
-if [ "$SAGE64" = "yes" ]; then
-   echo "64 bit build"
-   CFLAGS="-O2 -g -m64 "; export CFLAGS
-   CPPFLAGS="-O2 -g -m64 "; export CPPFLAGS
-fi
-
-cp patches/configure src
 
 cd src
 
-if [ -f "$SAGE_LOCAL"/lib/libatlas.so ]; then
-    ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" --enable-shared --with-gmp-include="$SAGE_LOCAL"/include --with-gmp-lib="$SAGE_LOCAL"/lib --with-atlas-include="$SAGE_LOCAL"/include --with-atlas-lib="$SAGE_LOCAL"/lib
+# Apply patches.
+for patch in ../patches/*.patch; do
+    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+    patch -p1 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
+
+
+if [ "$SAGE_DEBUG" = "yes" ]; then
+    echo "Building a debug version of IML."
+    export CFLAGS="-O0 -g $CFLAGS"
 else
-    ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" --enable-shared --with-gmp-include="$SAGE_LOCAL"/include --with-gmp-lib="$SAGE_LOCAL"/lib --with-atlas-include="`pwd`" --with-atlas-lib=/usr/lib/
+    export CFLAGS="-O2 -g $CFLAGS"
+fi
+
+if [ "$SAGE64" = "yes" ]; then
+    echo "Building a 64-bit version of IML."
+    CFLAGS="-m64 $CFLAGS"
+fi
+
+if [ -d "$SAGE_LOCAL/include/atlas" ]; then
+    # We actually installed ATLAS
+    echo "Using ATLAS headers installed by Sage"
+    ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
+        --enable-shared --with-default="$SAGE_LOCAL"
+else
+    # We symlinked from a system-wide installation, so let's use GSL's header
+    # Note that setting --with-atlas-lib to /usr/lib does not really make sense
+    echo "Using system-wide ATLAS, using headers copied from GSL"
+    ./configure --prefix="$SAGE_LOCAL" --libdir="$SAGE_LOCAL/lib" \
+        --enable-shared --with-default="$SAGE_LOCAL" \
+        --with-atlas-include="`pwd`" --with-atlas-lib=/usr/lib
 fi
 
 if [ $? -ne 0 ]; then
-    echo "Error configuring IML"
+    echo >&2 "Error configuring IML."
     exit 1
 fi
 
-make
-
+$MAKE
 if [ $? -ne 0 ]; then
-    echo "Error building IML"
+    echo >&2 "Error building IML."
     exit 1
 fi
 
-make install
-
+$MAKE install
 if [ $? -ne 0 ]; then
-    echo "Error installing IML"
+    echo >&2 "Error installing IML."
     exit 1
 fi
-
