#11883: upgrade to version 7.2.alpha6: according to the web site, the previous version "is old enough that you are almost certainly better off going with the much more recent and only somewhat experimental version", namely 7.2.alpha6.
Also apply a fix so it builds on OS X 10.7 Lion.  Fix taken from the
repository
https://github.com/ivmai/libatomic_ops/tree/master/src/atomic_ops/sysdeps/gcc,
and is mentioned at
http://comments.gmane.org/gmane.comp.programming.garbage-collection.boehmgc/4675.
(There must be a better description of these patches, but I haven't
found it.)

diff --git a/build/pkgs/boehm_gc/spkg-install b/build/pkgs/boehm_gc/spkg-install
--- a/build/pkgs/boehm_gc/spkg-install
+++ b/build/pkgs/boehm_gc/spkg-install
@@ -6,14 +6,14 @@ if [ "$SAGE_LOCAL" = "" ]; then
    exit 1
 fi
 
-# Apply patches
-
-if [ $UNAME = "Darwin" ]; then
-   # See
-   # http://duriansoftware.com/joe/PSA:-avoiding-the-%22ucontext-routines-are-deprecated%22-error-on-Mac-OS-X-Snow-Leopard.html
-   echo "Patching mach_dep.c -- needed for OS X 10.6"
-   $CP patches/mach_dep.c src/
-fi
+# Apply patches.
+for patch in patches/*.patch; do
+    patch -p0 <"$patch"
+    if [ $? -ne 0 ]; then
+        echo >&2 "Error applying '$patch'"
+        exit 1
+    fi
+done
 
 if [ "$SAGE64" = "yes" ]; then
    echo "64 bit build"
