Update spkg-install to be more standard compliant

diff --git a/build/pkgs/boehm_gc/spkg-install b/build/pkgs/boehm_gc/spkg-install
--- a/build/pkgs/boehm_gc/spkg-install
+++ b/build/pkgs/boehm_gc/spkg-install
@@ -1,3 +1,28 @@
-src/configure --prefix=$SAGE_LOCAL --enable-large-config
+#!/usr/bin/env bash
+
+if [ "$SAGE_LOCAL" = "" ]; then
+   echo "SAGE_LOCAL undefined ... exiting";
+   echo "Maybe run 'sage -sh'?"
+   exit 1
+fi
+
+cd src
+
+./configure --prefix=$SAGE_LOCAL --enable-large-config
+if [ $? -ne 0 ]; then
+   echo "Error configuring BoehmGC."
+   exit 1
+fi
+
 make
+if [ $? -ne 0 ]; then
+   echo "Error building BoehmGC."
+   exit 1
+fi
+
 make install
+if [ $? -ne 0 ]; then
+   echo "Error installing BoehmGC."
+   exit 1
+fi
+
