.github/workflows/docker.yml: Add trac-merge, upstream artifact code from https://github.com/sagemath/cysignals/tree/main/.github/workflows and https://trac.sagemath.org/ticket/33791 cygwin.yml

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -69,6 +69,30 @@ on:
       max_parallel:
         type: string
         default: 20
+      #
+      # Publishing to GitHub Packages
+      #
+      docker_push_repository:
+        required: false
+        type: string
+      #
+      # For use in upstream CIs
+      #
+      upstream_artifact:
+        required: false
+        type: string
+      sage_repo:
+        required: false
+        type: string
+      sage_trac_git:
+        required: false
+        type: string
+      sage_trac_ticket:
+        required: false
+        type: string
+      sage_ref:
+        required: false
+        type: string
 
 jobs:
   linux:
@@ -84,9 +108,12 @@ jobs:
       LOGS_ARTIFACT_NAME: logs-commit-${{ github.sha }}-tox-docker-${{ matrix.tox_system_factor }}-${{ matrix.tox_packages_factor }}
       DOCKER_TARGETS: with-system-packages configured with-targets-pre with-targets with-targets-optional
     steps:
-      - uses: actions/checkout@v2
+      - name: Check out SageMath
+        uses: actions/checkout@v2
         with:
-          fetch-depth: 500
+          repository: ${{ inputs.sage_repo }}
+          ref: ${{ inputs.sage_ref }}
+          fetch-depth: 2000
       - name: fetch tags
         run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
       - name: free disk space
@@ -100,13 +127,38 @@ jobs:
           dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 50
           sudo apt-get --fix-broken --yes remove $(dpkg-query -f '${Package}\n' -W | grep -E '^(ghc-|google-cloud-sdk|google-chrome|firefox|mysql-server|dotnet-sdk|hhvm|mono)') || echo "(error ignored)"
           df -h
+      - name: Check out git-trac-command
+        uses: actions/checkout@v2
+        with:
+          repository: sagemath/git-trac-command
+          path: git-trac-command
+        if: inputs.sage_trac_git != ''
+      - name: Check out SageMath from trac.sagemath.org
+        shell: bash {0}
+        # Random sleep and retry to limit the load on trac.sagemath.org
+        run: |
+          git config --global user.email "ci-sage@example.com"
+          git config --global user.name "ci-sage workflow"
+          if [ ! -d .git ]; then git init; fi; git remote add trac ${{ inputs.sage_trac_git }} && x=1 && while [ $x -le 5 ]; do x=$(( $x + 1 )); sleep $(( $RANDOM % 60 + 1 )); if git-trac-command/git-trac fetch ${{ inputs.sage_trac_ticket }}; then git merge FETCH_HEAD || echo "(ignored)"; exit 0; fi; sleep 40; done; exit 1
+        if: inputs.sage_trac_git != ''
+
+      - name: Download upstream artifact
+        uses: actions/download-artifact@v2
+        with:
+          path: upstream
+          name: ${{ inputs.upstream_artifact }}
+        if: inputs.upstream_artifact
       - name: Install test prerequisites
         run: |
           sudo DEBIAN_FRONTEND=noninteractive apt-get update
           sudo DEBIAN_FRONTEND=noninteractive apt-get install tox
           sudo apt-get clean
           df -h
+      - name: Update Sage packages from upstream artifact
+        run: |
+          (export PATH=$(pwd)/build/bin:$PATH; (cd upstream && bash -x update-pkgs.sh) && sed -i.bak '/upstream/d' .dockerignore && echo "/:toolchain:/i ADD upstream upstream" | sed -i.bak -f - build/bin/write-dockerfile.sh && git diff)
       - name: Try to login to ghcr.io
+        if: inputs.docker_push_repository != ''
         # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
         run: |
             TOKEN="${{ secrets.DOCKER_PKG_GITHUB_TOKEN }}"
@@ -114,7 +166,7 @@ jobs:
               TOKEN="${{ secrets.GITHUB_TOKEN }}"
             fi
             if echo "$TOKEN" | docker login ghcr.io -u ${{ github.actor }} --password-stdin; then
-              echo "DOCKER_PUSH_REPOSITORY=ghcr.io/${{ github.repository }}/" >> $GITHUB_ENV
+              echo "DOCKER_PUSH_REPOSITORY=${{ inputs.docker_push_repository }}" >> $GITHUB_ENV
               echo "DOCKER_CONFIG_FILE=$HOME/.docker/config.json" >> $GITHUB_ENV
             fi
             # From the docker documentation via .ci/update-env.sh:
@@ -127,21 +179,21 @@ jobs:
             case "$GITHUB_REF_NAME" in
               +([0-9]).+([0-9])?(.+([0-9])) )
                 EXTRA_DOCKER_TAGS="latest dev $EXTRA_DOCKER_TAGS";;
-              +([0-9]).+([0-9])?(.+([0-9])).@(beta|rc)+([0-9]) )
+              +([0-9]).+([0-9])?(.+([0-9]))?(.)@(a|alpha|b|beta|rc)+([0-9]) )
                 EXTRA_DOCKER_TAGS="dev $EXTRA_DOCKER_TAGS";;
             esac
             echo "EXTRA_DOCKER_TAGS=$EXTRA_DOCKER_TAGS" >> $GITHUB_ENV
-      - name: Build and test
+      - name: Configure and build Sage distribution within a Docker container
         run: |
           set -o pipefail; EXTRA_DOCKER_BUILD_ARGS="--build-arg USE_MAKEFLAGS=\"-k V=0 SAGE_NUM_THREADS=3\"" tox -e $TOX_ENV -- $TARGETS 2>&1 | sed "/^configure: notice:/s|^|::warning file=artifacts/$LOGS_ARTIFACT_NAME/config.log::|;/^configure: warning:/s|^|::warning file=artifacts/$LOGS_ARTIFACT_NAME/config.log::|;/^configure: error:/s|^|::error file=artifacts/$LOGS_ARTIFACT_NAME/config.log::|;"
-      - name: Copy logs from the docker image or build container
+      - name: Copy logs from the Docker image or build container
         run: |
           mkdir -p "artifacts/$LOGS_ARTIFACT_NAME"
           cp -r .tox/$TOX_ENV/Dockerfile .tox/$TOX_ENV/log "artifacts/$LOGS_ARTIFACT_NAME"
           if [ -f .tox/$TOX_ENV/Dockertags ]; then CONTAINERS=$(docker create $(tail -1 .tox/$TOX_ENV/Dockertags) /bin/bash || true); fi
           if [ -n "$CONTAINERS" ]; then for CONTAINER in $CONTAINERS; do for ARTIFACT in /sage/logs; do docker cp $CONTAINER:$ARTIFACT artifacts/$LOGS_ARTIFACT_NAME && HAVE_LOG=1; done; if [ -n "$HAVE_LOG" ]; then break; fi; done; fi
         if: always()
-      - uses: actions/upload-artifact@v1
+      - uses: actions/upload-artifact@v2
         with:
           path: artifacts
           name: ${{ env.LOGS_ARTIFACT_NAME }}
